#!/bin/bash
#set -euo pipefail

ADDOPT=""

if [ "$1" == "hls" ]
then
   EXT=ts
   FILES="*.${EXT}"
else
   EXT="$1"
   FILES="00000[0-9].${EXT}"
fi

. "${BASH_SOURCE%/*}/funcs.sh" "$1"

if [ "$1" == "hls" ]
then
   XDIRNAME="${DIRNAME}/snowboard.mp4"
else
   XDIRNAME="${DIRNAME}/frame_test_pal.mp4"
fi
REFPATH="${TMPPATH}/first"
SECOND_PATH="${TMPPATH}/second"

rm -rf "${REFPATH}" "${SECOND_PATH}"
mkdir -p "${REFPATH}" "${SECOND_PATH}"

echo "First pass: generate/fill cache"
cp -vpf "${XDIRNAME}"/${FILES} "${REFPATH}/"

echo "Second pass: read from cache"
cp -vpf "${XDIRNAME}"/${FILES} "${SECOND_PATH}/"

echo "Create hash lists"
(
    cd "${REFPATH}"
    sha256sum ${FILES} | sort -k2 > "${TMPPATH}/first.sha256"
)

(
    cd "${SECOND_PATH}"
    sha256sum ${FILES} | sort -k2 > "${TMPPATH}/second.sha256"
)

echo "Compare hashes"
diff -u "${TMPPATH}/first.sha256" "${TMPPATH}/second.sha256"

echo "OK"
