#!/bin/bash

. "${BASH_SOURCE%/*}/funcs.sh" "$1"

# Fixes to make these checks work with Libav 12
#
# Change...
# ^TXXX=DESCRIPTION -> TXXX=comment
# ^TDRL             -> TDRC
# ^desc             -> ?cmt (but keep ^description=)
#
get_metadata() {
        local -n outvar=$2    # -n makes it a nameref.
        echo Checking $1
        cat "$1" > /dev/null
        outvar=`./metadata "$1" | fgrep = | sort -u | sed -r 's/^encoder=.*//I'`
}

# Detect FFmpeg or Libav version
# FFmpeg versions prior to 3.2.x store a title in the file and the encoder version, nothing else...
FFMPEGVERSION=`./metadata -v | sed -n 's/^FFmpeg[^0-9]\([0-9]*\.[0-9]*\).*$/\1/p' | head -n 1`
LIBAVVERSION=`./metadata -v | sed -n 's/^Libav[^0-9]\([0-9]*\.[0-9]*\).*$/\1/p' | head -n 1`

if [ -z "${FFMPEGVERSION}" ] && [ -z "${LIBAVVERSION}" ];
then
	FFMPEGVERSION=`./metadata -v | sed -n 's/^FFmpeg \(.*\)$/\1/p' | head -n 1`
	LIBAVVERSION=`./metadata -v | sed -n 's/^Libav \(.*\)$/\1/p' | head -n 1`
fi

if [ ! -z "${FFMPEGVERSION}" ];
then
	echo "FFmpeg version is ${FFMPEGVERSION}"

	LIBRARY=ffmpeg
	if  [[ "${FFMPEGVERSION}" == N* ]];
	then
		echo "FFmpeg Nightly Build"
		VERSION=N
        elif (( $(echo "${FFMPEGVERSION} > 3.2" | bc -l) )); then
                echo "FFmpeg > 3.2.x"
		VERSION=3.2+
        else
        	echo "FFmpeg <= 3.2.x"
		VERSION=3.2-
        fi
elif [ ! -z "${LIBAVVERSION}" ];
then
	echo "Libav version is ${LIBAVVERSION}"

	# Using Libav, no known version differences
	LIBRARY=libav
	VERSION=
else
	echo "Internal error: FFmpeg/Libav version unknown."
	exit 99
fi

TAGFILE=tags/${LIBRARY}${VERSION}/obama.$1.tag
get_metadata "$DIRNAME/obama.$1" TAGS
echo "Compare file: ${TAGFILE}" 
echo "Tags found:"
echo "$TAGS"
cmp -b ${TAGFILE} <(echo "$TAGS")
printf "*** PASS ***\n\n"

TAGFILE=tags/${LIBRARY}${VERSION}/raven.$1.tag
get_metadata "$DIRNAME/raven.$1" TAGS
echo "Compare file: ${TAGFILE}"
echo "Tags found:"
echo "${TAGS}"
cmp -b ${TAGFILE} <(echo "$TAGS")
printf "*** PASS ***\n\n"

echo OK
