#!/bin/bash

. "${BASH_SOURCE%/*}/funcs.sh" "$1"

get_metadata() {
	local -n outvar=$2    # -n makes it a nameref.
	echo Checking $1
	outvar=`mutagen-inspect "$1" | fgrep = | sort | sed -r 's/^.*=Lavf.*//'`
}

if [ "$DESTTYPE" == "mp4" ];
then
# mp4

get_metadata "$DIRNAME/obama.mp4" TAGS
echo Tags found: 
echo "$TAGS"
cmp -s - <(echo "$TAGS")<<END
?ART=Barack Obama
?alb=US State of the Union 2011
?cpy=Public Domain
?day=2011-01-25
?gen=Spoken
?nam=The Internet [excerpt]

trkn=(1, 0)
END
echo "Pass"

get_metadata "$DIRNAME/raven.mp4" TAGS
echo Tags found: 
echo "$TAGS"
cmp -s - <(echo "$TAGS")<<END
?ART=Edgar Allen Poe
?alb=The Raven
?cmt=www.librivox.org
?day=2007
?gen=Speech
?nam=the_raven

trkn=(1, 0)
END
echo "Pass"

elif [ "$DESTTYPE" == "mp3" ];
then

# mp3
get_metadata "$DIRNAME/obama.mp3" TAGS
echo Tags found: 
echo "$TAGS"
cmp -s - <(echo "$TAGS")<<END
TALB=US State of the Union 2011
TCON=Spoken
TCOP=Public Domain
TDRC=2011-01-25
TIT2=The Internet [excerpt]
TPE1=Barack Obama
TPOS=0
TRCK=1

TXXX=DISCTOTAL=0
TXXX=TRACKTOTAL=1
END
echo "Pass"

get_metadata "$DIRNAME/raven.mp3" TAGS
echo Tags found: 
echo "$TAGS"
cmp -s - <(echo "$TAGS")<<END
TALB=The Raven
TCON=Speech
TDRC=2007
TIT2=the_raven
TPE1=Edgar Allen Poe
TRCK=01

TXXX=ENSEMBLE=Edgar Allen Poe
TXXX=comment=www.librivox.org
END
echo "Pass"

elif [ "$DESTTYPE" == "wav" ];
then
# wav
echo WAVs have no tags.
else
echo "Internal error, unknown type $DESTTYPE. Fix script!"
exit 99
fi

echo OK
