#!/bin/bash

ADDOPT=""

. "${BASH_SOURCE%/*}/funcs.sh" "$1"

# Should be 250 files for 250 frames in source
FILES=250

echo "Checking number of files is ${FILES}"
[ $(ls "${DIRNAME}"/frame_test_pal.mp4/ -1 | wc -l) = ${FILES} ]
echo "Number of files OK"

echo "Checking access with full name"
for i in 000204 000004 000104 000207 000007 000107
do
	FILE="${DIRNAME}"/frame_test_pal.mp4/${i}.${FILEEXT}
        cp -vpf "${FILE}" "${TMPPATH}" > /dev/null
        #cp -vpf "${FILE}" "${TMPPATH}" > /dev/null
done

echo "Checking access with regular expression"
for i in 00024[4-79] 00008[4-79] 00018[4-79]
do
        echo ">> Expression ${i}.*"
        for FILE in "${DIRNAME}"/frame_test_pal.mp4/${i}.*
	do
		FILENAME="${FILE##*/}"
                cp -vpf "${FILE}" "${TMPPATH}" > /dev/null
                #cp -vpf "${FILE}" "${TMPPATH}" > /dev/null
	done 2>/dev/null
done
echo "Access OK"

echo "Pass"

echo "OK"
