#!/bin/bash

. "${BASH_SOURCE%/*}/funcs.sh" "$1"

# Ensure log contains file sizes, predicted and actual
cat "${DIRNAME}/raven_e.${FILEEXT}" > /dev/null
cat "${DIRNAME}/raven_d.${FILEEXT}" > /dev/null

if [ "${DESTTYPE}" == "mp4" ];
then
    # mp4
    check_filesize "raven_e" 490440 494236
    check_filesize "raven_d" 354319 355298
elif [ "${DESTTYPE}" == "mp3" ];
then
    # mp3
    check_filesize "raven_e" 466981 490440
    check_filesize "raven_d" 343527
elif [ "${DESTTYPE}" == "wav" ];
then
    # wav
    check_filesize "raven_e" 5137772
    check_filesize "raven_d" 4316536
elif [ "${DESTTYPE}" == "ogg" ];
then
    # ogg
    check_filesize "raven_e" 356669 356771
    check_filesize "raven_d" 264179
elif [ "${DESTTYPE}" == "webm" ];
then
    # webm
    check_filesize "raven_e" 429358 489821
    check_filesize "raven_d" 262919 353367
elif [ "${DESTTYPE}" == "opus" ];
then
    # opus
    check_filesize "raven_e" 421675 482727 
    check_filesize "raven_d" 255780 347272 
elif [ "${DESTTYPE}" == "mov" ];
then
    # mov
    check_filesize "raven_e" 491651 495447
    check_filesize "raven_d" 355300 356142
elif [ "${DESTTYPE}" == "aiff" ];
then
    # aiff
    check_filesize "raven_e" 5137724 5140125
    check_filesize "raven_d" 4316488
elif [ "${DESTTYPE}" == "prores" ];
then
    # prores
    check_filesize "raven_e" 5140125 5140129
    check_filesize "raven_d" 4318641 4318666
elif [ "${DESTTYPE}" == "alac" ];
then
    # alac
    check_filesize "raven_e" 3986423 3986427
    check_filesize "raven_d" 3277326 3277330
elif [ "${DESTTYPE}" == "ts" ];
then
    # ts
    check_filesize "raven_e" 725868 811220 
    check_filesize "raven_d" 479964 545388 
else
echo "Internal error, unknown type ${DESTTYPE}. Fix script!"
exit 99
fi

