#!/bin/bash

. "${BASH_SOURCE%/*}/funcs.sh" "hls"

DIRNAME="${DIRNAME}"/snowboard.mp4

SEGMENTS=3

echo "Checking number of HLS segments is ${SEGMENTS}"
[ $(ls "${DIRNAME}"/*.ts -1 | wc -l) = ${SEGMENTS} ]

echo "OK"
