#!/bin/bash

. "${BASH_SOURCE%/*}/funcs.sh" "hls"

DIRNAME="${DIRNAME}"/snowboard.mp4

SEGMENTS=3

echo "Checking number of HLS segments is ${SEGMENTS}"
[ $(ls "${DIRNAME}"/*.ts -1 | wc -l) = ${SEGMENTS} ]
echo "Number of files OK"

echo "Checking file names"
[ "$(ls --ignore='*.ts' -w 1000 -m "${DIRNAME}")" = "hls.html, index_0_av.m3u8, master.m3u8" ]
echo "File names OK"

cat "${DIRNAME}"/*.ts > /dev/null

echo "File sizes"
check_filesize "000001.ts" 1535020 1599880
check_filesize "000002.ts" 1532764 1569612
check_filesize "000003.ts" 1201508 1231588
echo "File sizes OK"

echo "Pass"

echo "OK"
