#!/bin/bash

ADDOPT=""

. "${BASH_SOURCE%/*}/funcs.sh" "$1"

# Ensure log contains file sizes, predicted and actual
echo "Transcoding ${DIRNAME}/raven_e.flac.${FILEEXT}"
cp -v "${DIRNAME}/raven_e.flac.${FILEEXT}" /dev/null
cp -v "${DIRNAME}/raven_e.flac.${FILEEXT}" /dev/null
echo "Transcoding ${DIRNAME}/raven_d.ogg.${FILEEXT}"
cp -v "${DIRNAME}/raven_d.ogg.${FILEEXT}" /dev/null
cp -v "${DIRNAME}/raven_d.ogg.${FILEEXT}" /dev/null

if [ "${DESTTYPE}" == "mp4" ];
then
    # mp4
    check_filesize "raven_e.flac" 485435 494238
    check_filesize "raven_d.ogg" 349440 355298
elif [ "${DESTTYPE}" == "mp3" ];
then
    # mp3
    check_filesize "raven_e.flac" 466980 490440
    check_filesize "raven_d.ogg" 342690 343527
elif [ "${DESTTYPE}" == "wav" ];
then
    # wav
    check_filesize "raven_e.flac" 5137707 5137772
    check_filesize "raven_d.ogg" 4316344 4316536
elif [ "${DESTTYPE}" == "ogg" ];
then
    # ogg
    check_filesize "raven_e.flac" 356664 489113
    check_filesize "raven_d" 264179
elif [ "${DESTTYPE}" == "webm" ];
then
    # webm
    check_filesize "raven_e.flac" 429344 548761
    check_filesize "raven_d.ogg" 262845 393946
elif [ "${DESTTYPE}" == "opus" ];
then
    # opus
    check_filesize "raven_e.flac" 421675 548761
    check_filesize "raven_d.ogg" 255740 393946
elif [ "${DESTTYPE}" == "mov" ];
then
    # mov
    check_filesize "raven_e.flac" 486622 495447
    check_filesize "raven_d.ogg" 342690 356142
elif [ "${DESTTYPE}" == "aiff" ];
then
    # aiff
    check_filesize "raven_e.flac" 5137707 5140125
    check_filesize "raven_d.ogg" 4316344 4316488
elif [ "${DESTTYPE}" == "prores" ];
then
    # prores
    check_filesize "raven_e.flac" 5137707 5140129
    check_filesize "raven_d.ogg" 4316344 4318666
elif [ "${DESTTYPE}" == "alac" ];
then
    # alac
    check_filesize "raven_e.flac" 3952038 3986427
    check_filesize "raven_d.ogg" 3276205 3320221
elif [ "${DESTTYPE}" == "ts" ];
then
    # ts
    check_filesize "raven_e.flac" 489113 811408
    check_filesize "raven_d.ogg" 351126 545388
elif [ "${DESTTYPE}" == "flac" ];
then
    # flac
    check_filesize "raven_e.flac" 3037626 3596355
    check_filesize "raven_d.ogg"  1132018 1132062
else
echo "Internal error, unknown type ${DESTTYPE}. Fix script!"
exit 99
fi

