#!/bin/bash

ADDOPT=""

. "${BASH_SOURCE%/*}/funcs.sh" "hls"

DIRNAME="${DIRNAME}"/snowboard.mp4

cat "${DIRNAME}"/*.ts > /dev/null

echo "File sizes"
check_filesize "000001.ts" 1535020 1599880
check_filesize "000002.ts" 1523928 1569612
check_filesize "000003.ts" 1193612 1231588
echo "File sizes OK"

echo "OK"
