#!/bin/bash

ADDOPT=""

. "${BASH_SOURCE%/*}/funcs.sh" "hls"

XDIRNAME="${DIRNAME}"/snowboard.mp4

SEGMENTS=3

echo "Checking number of HLS segments is ${SEGMENTS}"
[ $(ls "${XDIRNAME}"/*.ts -1 | wc -l) = ${SEGMENTS} ]

echo "OK"
