#!/bin/bash

. "${BASH_SOURCE%/*}/funcs.sh" "$1"

check_audio() {
    TGTFILE="$1.${DESTTYPE}"
    SRCFILE="$1.$2"
    EXPECTED="$3"
    
    cp "$DIRNAME/${TGTFILE}" /tmp/ 2>&-
    
#    RESULT="$(./fpcompare "${SRCDIR}/${SRCFILE}" "$DIRNAME/${TGTFILE}" 2>&-)"
    RESULT="$(./fpcompare "${SRCDIR}/${SRCFILE}" "$DIRNAME/${TGTFILE}")"
    
    rm -f "/tmp/${TGTFILE}" 
    
    SIZE=$(stat -c %s "$DIRNAME/${TGTFILE}")
    echo "File  : ${TGTFILE}"
    echo "Result: ${RESULT} (expected ${EXPECTED})"

    
    if [ $(echo "${RESULT} <= ${EXPECTED}" | bc) -eq 1 ]
    then
        echo "Pass"
    else
        echo "FAIL!"
        exit 1
    fi
}

if [ "$DESTTYPE" == "mp4" ];
then
	# mp4
	check_audio "obama" "flac" 0.08
	check_audio "raven" "ogg" 0.08
elif [ "$DESTTYPE" == "mp3" ];
then
	# mp3
	check_audio "obama" "flac" 0.6
	check_audio "raven" "ogg" 0.4
elif [ "$DESTTYPE" == "wav" ];
then
	# wav
	check_audio "obama" "flac" 0.0
	check_audio "raven" "ogg" 0.0
elif [ "$DESTTYPE" == "ogg" ];
then
	# ogg
	check_audio "obama" "flac" 0.2
	check_audio "raven" "ogg" 0.0
else
	echo "Internal error, unknown type $DESTTYPE. Fix script!"
	exit 99
fi

echo OK
