#!/bin/bash

set -o pipefail

echo -e 'Automatically generated by Makefile\n' > ChangeLog.tmp

git log --pretty="format:%d %h / %aD%n %an <%ae>%n  * %s%n" \
	| sed -E -e 'N;N;N' \
	-e 's|^ \(.*tag: ([0-9\.]+).*\)[^\n]* (.{5,6} [0-9]{4}) .*|Changes for version \1 (\2):\n|' \
	-e 's|^ \(.*\)||' >> ChangeLog.tmp \
	&& mv -f ChangeLog.tmp ChangeLog \
	|| ( rm -f ChangeLog.tmp ; exit 1 )

