#!/bin/bash

#COMPILER=gcc
#TOOLKIT=ffmpeg
#FFMPEGVER=4.1
#CONFIGUREOPT=

COMPILER=$1
TOOLKIT=$2
FFMPEGVER=$3
CONFIGUREOPT=$4

if [ -z ${CONFIGUREOPT} ];
then
    echo "Building for ${TOOLKIT} ${FFMPEGVER} with ${COMPILER}"
else
    echo "Building for ${TOOLKIT} ${FFMPEGVER} with ${COMPILER} (configure ${CONFIGUREOPT})"
fi

FFMPEG_BUILD="$HOME/dev/builds/$TOOLKIT-$FFMPEGVER"

if [ ! -d ${FFMPEG_BUILD} ];
then
    echo "*** ERROR *** FFmpeg not found in ${FFMPEG_BUILD}"
    exit 99
fi

echo "Using FFmpeg in ${FFMPEG_BUILD}"

# 32+64 bit
#export LIB32="${FFMPEG_BUILD}/lib"
#export LIB64="${FFMPEG_BUILD}/lib64"
#export LD_LIBRARY_PATH="${LIB64}:${LIB32}"
#export LDFLAGS="-L${LIB64} -L${LIB32} -Wl,-rpath,${LD_LIBRARY_PATH}"
#export PKG_CONFIG_PATH="${FFMPEG_BUILD}/lib/pkgconfig:${FFMPEG_BUILD}/lib64/pkgconfig"

# 64 bit only
export LIB="${FFMPEG_BUILD}/lib"
export LD_LIBRARY_PATH="${LIB}"
export LDFLAGS="-L${LIB} -Wl,-rpath,${LD_LIBRARY_PATH}"
export PKG_CONFIG_PATH="${FFMPEG_BUILD}/lib/pkgconfig"

export CPLUS_INCLUDE_PATH="${FFMPEG_BUILD}/include"
export CFLAGS=-I"${FFMPEG_BUILD}/include"
export CPPFLAGS=-I"${FFMPEG_BUILD}/include"

rm -Rf autom4te.cache config
./autogen.sh
if [ ${COMPILER} = "clang" ];
then
    echo "Using clang"
    CC=clang CXX=clang++ ./configure ${CONFIGUREOPT}
elif [ ${COMPILER} = "gcc" ];
then
    echo "Using gcc"
    CC=gcc  CXX="g++" ./configure ${CONFIGUREOPT}
else
    echo "Using default compiler"
    ./configure ${CONFIGUREOPT}
fi

make -s clean all check
