FFmpegfs Fuse Multi Media Filesystem: src/blurayparser.h File Reference
blurayparser.h File Reference
Bluray parser.
#include <string>
Functions
int check_bluray (const std::string &path, void *buf=nullptr, fuse_fill_dir_t filler=nullptr)
Get number of titles on Bluray.
Detailed Description
Bluray parser.
This is only available if built with -DUSE_LIBBLURAY parameter.
Author
Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Copyright
Copyright (C) 2018-2022 Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Definition in file blurayparser.h.
Function Documentation
check_bluray()
int check_bluray (const std::string & path, void * buf = nullptr, fuse_fill_dir_t filler = nullptr)
Get number of titles on Bluray.
Parameters
[in] path - Path to check
[in,out] buf - The buffer passed to the readdir() operation.
[in,out] filler - Function to add an entry in a readdir() operation (see https://libfuse.github.io/doxygen/fuse_8h.html#a7dd132de66a5cc2add2a4eff5d435660)
Note
buf and filler can be nullptr. In that case the call will run faster, so these parameters should only be passed if to be filled in.
Returns
-errno or number or titles on Bluray
Definition at line 626 of file blurayparser.cc.
References add_dotdot(), append_sep(), check_path(), load_path(), parse_bluray(), and Logging::trace().
Referenced by ffmpegfs_getattr(), and ffmpegfs_readdir().