FFmpegfs Fuse Multi Media Filesystem: BlurayIO Class Reference
BlurayIO Class Reference
Bluray I/O class.
#include <blurayio.h>
Public Member Functions
BlurayIO ()
Create BlurayIO object.
virtual ~BlurayIO ()
Free BlurayIO object.
virtual VIRTUALTYPE type () const override
Get type of the virtual file.
virtual size_t bufsize () const override
Get the ideal buffer size.
virtual int open (LPVIRTUALFILE virtualfile) override
Open a virtual file.
virtual size_t read (void *data, size_t size) override
Read data from file.
virtual int error () const override
Get last error.
virtual int64_t duration () const override
Get the duration of the file, in AV_TIME_BASE fractional seconds.
virtual size_t size () const override
Get the file size.
virtual size_t tell () const override
Get current read position.
virtual int seek (int64_t offset, int whence) override
Seek to position in file.
virtual bool eof () const override
Check if at end of file.
virtual void close () override
Close virtual file.
Public Member Functions inherited from FileIO
FileIO ()
Create FileIO object.
virtual ~FileIO ()
Free FileIO object.
LPVIRTUALFILE virtualfile ()
Get virtual file object.
const std::string & filename () const
Get source filename.
const std::string & path () const
Path to source file (without file name)
Protected Attributes
BLURAY * m_bd
Bluray disk handle.
bool m_is_eof
true if at end of virtual file
int m_errno
Last errno.
size_t m_rest_size
Rest bytes in buffer.
size_t m_rest_pos
Position in buffer.
int64_t m_cur_pos
Current position in virtual file.
int64_t m_start_pos
Start offset in bytes.
int64_t m_end_pos
End offset in bytes (not including this byte)
bool m_full_title
If true, ignore m_chapter_no and provide full track.
uint32_t m_title_idx
Track index (track number - 1)
unsigned m_chapter_idx
Chapter index (chapter number - 1)
unsigned m_angle_idx
Selected angle index (angle number -1)
uint8_t m_data [192 *1024]
Buffer for read() data.
int64_t m_duration
Track/chapter duration, in AV_TIME_BASE fractional seconds.
Private Member Functions
void _close ()
Close virtual file. Non-virtual version to be safely called from constructor/destructor.
Additional Inherited Members
Static Public Member Functions inherited from FileIO
static FileIO * alloc (VIRTUALTYPE type)
Allocate the correct object for type().
Protected Member Functions inherited from FileIO
void set_virtualfile (LPVIRTUALFILE virtualfile)
Set the virtual file object.
Detailed Description
Bluray I/O class.
Definition at line 48 of file blurayio.h.
Member Function Documentation
bufsize()
size_t BlurayIO::bufsize () const override virtual
Get the ideal buffer size.
Returns
Return the ideal buffer size.
Implements FileIO.
Definition at line 70 of file blurayio.cc.
References m_data.
duration()
int64_t BlurayIO::duration () const override virtual
Get the duration of the file, in AV_TIME_BASE fractional seconds.
Returns
Returns the duration of the file, in AV_TIME_BASE fractional seconds.
Implements FileIO.
Definition at line 242 of file blurayio.cc.
References m_duration.
eof()
bool BlurayIO::eof () const override virtual
Check if at end of file.
Returns
Returns true if at end of file.
Implements FileIO.
Definition at line 302 of file blurayio.cc.
References m_cur_pos, and m_end_pos.
error()
int BlurayIO::error () const override virtual
Get last error.
Returns
errno value of last error.
Implements FileIO.
Definition at line 237 of file blurayio.cc.
References m_errno.
open()
int BlurayIO::open (LPVIRTUALFILE virtualfile) override virtual
Open a virtual file.
Parameters
[in] virtualfile - LPCVIRTUALFILE of file to open
Returns
Upon successful completion, open() returns 0.
On error, an nonzero value is returned and errno is set to indicate the error.
Implements FileIO.
Definition at line 75 of file blurayio.cc.
References Logging::debug(), Logging::error(), m_angle_idx, VIRTUALFILE::BLURAY_CHAPTER::m_angle_no, m_bd, VIRTUALFILE::m_bluray, m_chapter_idx, VIRTUALFILE::BLURAY_CHAPTER::m_chapter_no, m_duration, VIRTUALFILE::m_duration, m_end_pos, m_full_title, VIRTUALFILE::m_full_title, m_rest_pos, m_rest_size, m_start_pos, m_title_idx, VIRTUALFILE::BLURAY_CHAPTER::m_title_no, FileIO::path(), FileIO::set_virtualfile(), FileIO::virtualfile(), and Logging::warning().
read()
size_t BlurayIO::read (void * data, size_t size) override virtual
Read data from file.
Parameters
[out] data - buffer to store read bytes in. Must be large enough to hold up to size bytes.
[in] size - number of bytes to read
Returns
Upon successful completion, read() returns the number of bytes read.
This may be less than size.
On error, the value 0 is returned and errno is set to indicate the error.
If at end of file, 0 may be returned but errno not set. error() will return 0 if at EOF.
Implements FileIO.
Definition at line 177 of file blurayio.cc.
References Logging::error(), m_bd, m_cur_pos, m_data, m_end_pos, m_rest_pos, m_rest_size, FileIO::path(), and size().
seek()
int BlurayIO::seek (int64_t offset, int whence) override virtual
Seek to position in file.
Repositions the offset of the open file to the argument offset according to the directive whence.
Parameters
[in] offset - offset in bytes
[in] whence - how to seek:
SEEK_SET: The offset is set to offset bytes.
SEEK_CUR: The offset is set to its current location plus offset bytes.
SEEK_END: The offset is set to the size of the file plus offset bytes.
Returns
Upon successful completion, seek() returns the resulting offset location as measured in bytes from the beginning of the file.
On error, the value -1 is returned and errno is set to indicate the error.
Implements FileIO.
Definition at line 257 of file blurayio.cc.
References m_bd, m_cur_pos, m_end_pos, and m_start_pos.
size()
size_t BlurayIO::size () const override virtual
Get the file size.
Returns
Returns the file size.
Implements FileIO.
Definition at line 247 of file blurayio.cc.
References m_end_pos, and m_start_pos.
Referenced by read().
tell()
size_t BlurayIO::tell () const override virtual
Get current read position.
Returns
Gets the current read position.
Implements FileIO.
Definition at line 252 of file blurayio.cc.
References m_bd, and m_start_pos.
type()
VIRTUALTYPE BlurayIO::type () const override virtual
Get type of the virtual file.
Returns
Returns the type of the virtual file.
Implements FileIO.
Definition at line 65 of file blurayio.cc.
References VIRTUALTYPE_BLURAY.
The documentation for this class was generated from the following files:
src/blurayio.h
src/blurayio.cc