FFmpegfs Fuse Multi Media Filesystem: FFmpegfs_Format Class Reference
FFmpegfs_Format Class Reference
The FFmpegfs_Format class.
#include <ffmpeg_utils.h>
Public Member Functions
FFmpegfs_Format ()
Construct FFmpegfs_Format object.
bool init (const std::string &desttype)
Get codecs for the selected destination type.
const std::string & format_name () const
Convert destination type to "real" type, i.e., the file extension to be used.
const std::string & desttype () const
Get destination type.
const std::string & fileext () const
Get file extension.
FILETYPE filetype () const
Get selected filetype.
AVCodecID video_codec () const
Get video codec_id.
bool is_video_codec_supported (AVCodecID codec_id) const
Check if video codec/file format combination is supported.
std::string video_codec_list () const
Create a list of supported audio codecs for current audio codec.
AVCodecID audio_codec () const
Get audio codec_id.
bool is_audio_codec_supported (AVCodecID codec_id) const
Check if audio codec/file format combination is supported.
std::string audio_codec_list () const
Create a list of supported audio codecs for current audio codec.
AVSampleFormat sample_format () const
Get sample format (bit width)
bool is_sample_fmt_supported () const
Check if audio codec/sample format combination is supported.
std::string sample_fmt_list () const
Create a list of supported sample formats for current audio codec.
AVCodecID subtitle_codec (AVCodecID codec_id) const
Get subtitle codec_id.
bool is_multiformat () const
Check if this is some sort of multi file format (any of the following: is_frameset() or is_hls()).
bool is_frameset () const
Check for an export frame format.
bool is_hls () const
Check for HLS format.
bool albumart_supported () const
Check if album arts are supported.
Protected Attributes
const Format_Options m_empty_options
Set of empty (invalid) options as default.
const Format_Options * m_cur_opts
Currently selected options. Will never be nullptr.
std::string m_desttype
Destination type: mp4, mp3 or other.
FILETYPE m_filetype
File type, MP3, MP4, OPUS etc.
Static Protected Attributes
static const OPTIONS_MAP m_options_map
Map of options. One entry per supported destination type.
Private Types
typedef std::map< FILETYPE, const Format_Options > OPTIONS_MAP
Map of options. One entry per supported destination type.
Detailed Description
The FFmpegfs_Format class.
Definition at line 393 of file ffmpeg_utils.h.
Member Typedef Documentation
OPTIONS_MAP
typedef std::map<FILETYPE, const Format_Options> FFmpegfs_Format::OPTIONS_MAP private
Map of options. One entry per supported destination type.
Definition at line 395 of file ffmpeg_utils.h.
Constructor & Destructor Documentation
FFmpegfs_Format()
FFmpegfs_Format::FFmpegfs_Format ()
Construct FFmpegfs_Format object.
Definition at line 861 of file ffmpeg_utils.cc.
Member Function Documentation
albumart_supported()
bool FFmpegfs_Format::albumart_supported () const
Check if album arts are supported.
Returns
true if album arts are supported or false if not
Definition at line 927 of file ffmpeg_utils.cc.
References Format_Options::m_albumart_supported, and m_cur_opts.
Referenced by FFmpeg_Transcoder::open_output_filestreams().
audio_codec()
AVCodecID FFmpegfs_Format::audio_codec () const
Get audio codec_id.
Returns
Returns audio codec_id
Definition at line 947 of file ffmpeg_utils.cc.
References Format_Options::audio_codec(), and m_cur_opts.
Referenced by FFmpeg_Transcoder::calculate_predicted_filesize(), FFmpeg_Transcoder::can_copy_stream(), FFmpeg_Transcoder::open_output_filestreams(), and transcoder_set_filesize().
audio_codec_list()
std::string FFmpegfs_Format::audio_codec_list () const
Create a list of supported audio codecs for current audio codec.
Returns
Returns comma separated list of formats, or empty if not available.
Definition at line 957 of file ffmpeg_utils.cc.
References Format_Options::audio_codec_list(), and m_cur_opts.
desttype()
const std::string & FFmpegfs_Format::desttype () const
Get destination type.
Returns
Destination type
Definition at line 892 of file ffmpeg_utils.cc.
References m_desttype.
Referenced by Cache_Entry::Cache_Entry(), FFmpeg_Transcoder::calculate_predicted_filesize(), init(), FFmpeg_Transcoder::open_output_file(), FFmpeg_Transcoder::open_output_filestreams(), transcode(), and transcoder_set_filesize().
fileext()
const std::string & FFmpegfs_Format::fileext () const
Get file extension.
Returns
File extension
Definition at line 902 of file ffmpeg_utils.cc.
References m_cur_opts, and Format_Options::m_fileext.
Referenced by FFmpeg_Transcoder::encode_finish(), ffmpegfs_getattr(), ffmpegfs_readdir(), load_path(), make_hls_fileset(), and virtual_name().
filetype()
FILETYPE FFmpegfs_Format::filetype () const
Get selected filetype.
Returns
Returns selected filetype.
Definition at line 907 of file ffmpeg_utils.cc.
References m_filetype.
Referenced by FFmpeg_Transcoder::calculate_predicted_filesize(), FFmpeg_Transcoder::open_output_file(), FFmpeg_Transcoder::open_output_filestreams(), FFmpeg_Transcoder::produce_audio_dts(), transcoder_read(), transcoder_set_filesize(), and FFmpeg_Transcoder::write_output_file_header().
format_name()
const std::string & FFmpegfs_Format::format_name () const
Convert destination type to "real" type, i.e., the file extension to be used.
Note
Currently "prores" is mapped to "mov".
Returns
Destination type
Definition at line 897 of file ffmpeg_utils.cc.
References m_cur_opts, and Format_Options::m_format_name.
Referenced by FFmpeg_Transcoder::open_output_filestreams().
init()
bool FFmpegfs_Format::init (const std::string & desttype)
Get codecs for the selected destination type.
Parameters
[in] desttype - Destination type (MP4, WEBM etc.).
Returns
Returns true if format was found; false if not.
Definition at line 868 of file ffmpeg_utils.cc.
References desttype(), get_filetype(), m_cur_opts, m_desttype, m_empty_options, m_filetype, and m_options_map.
is_audio_codec_supported()
bool FFmpegfs_Format::is_audio_codec_supported (AVCodecID codec_id) const
Check if audio codec/file format combination is supported.
Parameters
[in] codec_id - Codec ID to check
Returns
Returns true if supported, false if not.
Definition at line 952 of file ffmpeg_utils.cc.
References Format_Options::is_audio_codec_supported(), and m_cur_opts.
is_frameset()
bool FFmpegfs_Format::is_frameset () const
Check for an export frame format.
Returns
Returns true for formats that export all frames as images.
Definition at line 917 of file ffmpeg_utils.cc.
References m_filetype.
Referenced by ffmpegfs_getattr(), ffmpegfs_readdir(), FFmpeg_Transcoder::is_frameset(), and is_multiformat().
is_hls()
bool FFmpegfs_Format::is_hls () const
Check for HLS format.
Returns
Returns true for formats that create an HLS set including the m3u file.
Definition at line 922 of file ffmpeg_utils.cc.
References m_filetype.
Referenced by ffmpegfs_getattr(), ffmpegfs_readdir(), FFmpeg_Transcoder::is_hls(), and is_multiformat().
is_multiformat()
bool FFmpegfs_Format::is_multiformat () const
Check if this is some sort of multi file format (any of the following: is_frameset() or is_hls()).
Returns
Returns true for a multi file format.
Definition at line 912 of file ffmpeg_utils.cc.
References is_frameset(), and is_hls().
Referenced by ffmpegfs_getattr(), ffmpegfs_readdir(), invalidate_stale_cache_file(), FFmpeg_Transcoder::is_multiformat(), start_transcoder_thread(), transcode(), transcoder_new(), and virtual_name().
is_sample_fmt_supported()
bool FFmpegfs_Format::is_sample_fmt_supported () const
Check if audio codec/sample format combination is supported.
Returns
Returns true if supported, false if not.
Definition at line 967 of file ffmpeg_utils.cc.
References Format_Options::is_sample_fmt_supported(), and m_cur_opts.
is_video_codec_supported()
bool FFmpegfs_Format::is_video_codec_supported (AVCodecID codec_id) const
Check if video codec/file format combination is supported.
Parameters
[in] codec_id - Codec ID to check
Returns
Returns true if supported, false if not.
Definition at line 937 of file ffmpeg_utils.cc.
References Format_Options::is_video_codec_supported(), and m_cur_opts.
sample_fmt_list()
std::string FFmpegfs_Format::sample_fmt_list () const
Create a list of supported sample formats for current audio codec.
Returns
Returns comma separated list of formats, or empty if not available.
Definition at line 972 of file ffmpeg_utils.cc.
References m_cur_opts, and Format_Options::sample_fmt_list().
sample_format()
AVSampleFormat FFmpegfs_Format::sample_format () const
Get sample format (bit width)
Returns
Returns sample format
Definition at line 962 of file ffmpeg_utils.cc.
References m_cur_opts, and Format_Options::sample_format().
Referenced by FFmpeg_Transcoder::add_stream().
subtitle_codec()
AVCodecID FFmpegfs_Format::subtitle_codec (AVCodecID codec_id) const
Get subtitle codec_id.
Parameters
[in] codec_id - Input stream codec ID
Returns
Returns subtitle codec_id that matches the input stream codec ID, or AV_CODEC_ID_NONE of no match.
Definition at line 977 of file ffmpeg_utils.cc.
References m_cur_opts, and Format_Options::subtitle_codec().
Referenced by FFmpeg_Transcoder::add_external_subtitle_stream(), FFmpeg_Transcoder::add_subtitle_streams(), and FFmpeg_Transcoder::open_subtitles().
video_codec()
AVCodecID FFmpegfs_Format::video_codec () const
Get video codec_id.
Returns
Returns video codec_id
Definition at line 932 of file ffmpeg_utils.cc.
References m_cur_opts, and Format_Options::video_codec().
Referenced by FFmpeg_Transcoder::calculate_predicted_filesize(), FFmpeg_Transcoder::can_copy_stream(), FFmpeg_Transcoder::encode_image_frame(), ffmpegfs_readdir(), FFmpeg_Transcoder::open_bestmatch_video(), FFmpeg_Transcoder::open_output(), FFmpeg_Transcoder::open_output_file(), FFmpeg_Transcoder::open_output_filestreams(), FFmpeg_Transcoder::open_output_frame_set(), and transcoder_set_filesize().
video_codec_list()
std::string FFmpegfs_Format::video_codec_list () const
Create a list of supported audio codecs for current audio codec.
Returns
Returns comma separated list of formats, or empty if not available.
Definition at line 942 of file ffmpeg_utils.cc.
References m_cur_opts, and Format_Options::video_codec_list().
Member Data Documentation
m_cur_opts
const Format_Options* FFmpegfs_Format::m_cur_opts protected
Currently selected options. Will never be nullptr.
Definition at line 512 of file ffmpeg_utils.h.
Referenced by albumart_supported(), audio_codec(), audio_codec_list(), fileext(), format_name(), init(), is_audio_codec_supported(), is_sample_fmt_supported(), is_video_codec_supported(), sample_fmt_list(), sample_format(), subtitle_codec(), video_codec(), and video_codec_list().
m_desttype
std::string FFmpegfs_Format::m_desttype protected
Destination type: mp4, mp3 or other.
Definition at line 514 of file ffmpeg_utils.h.
Referenced by desttype(), and init().
m_empty_options
const Format_Options FFmpegfs_Format::m_empty_options protected
Set of empty (invalid) options as default.
Definition at line 511 of file ffmpeg_utils.h.
Referenced by init().
m_filetype
FILETYPE FFmpegfs_Format::m_filetype protected
File type, MP3, MP4, OPUS etc.
Definition at line 515 of file ffmpeg_utils.h.
Referenced by filetype(), init(), is_frameset(), and is_hls().
m_options_map
const FFmpegfs_Format::OPTIONS_MAP FFmpegfs_Format::m_options_map static protected
Map of options. One entry per supported destination type.
Definition at line 329 of file ffmpeg_utils.h.
Referenced by init().
The documentation for this class was generated from the following files:
src/ffmpeg_utils.h
src/ffmpeg_utils.cc