FFmpegfs Fuse Multi Media Filesystem: FFmpeg_Frame Class Reference
FFmpeg_Frame Class Reference
The FFmpeg_Frame class.
#include <ffmpeg_frame.h>
Public Member Functions
FFmpeg_Frame (int stream_index=INVALID_STREAM)
Construct FFmpeg_Frame object.
FFmpeg_Frame (const FFmpeg_Frame &frame)
Copy construct from FFmpeg_Frame object.
FFmpeg_Frame (const AVFrame *frame)
Copy construct from AVFrame struct.
virtual ~FFmpeg_Frame ()
Destruct FFmpeg_Frame object.
int res () const
Get result of last operation.
AVFrame * clone ()
Clone frame to a new AVFrame * struct. Needs to be freed by a av_frame_free() call.
void unref ()
Unreference underlying frame.
void free ()
Free underlying frame.
AVFrame * get ()
Access the underlying frame.
operator AVFrame * ()
operator AVFrame *: Do as if we were a pointer to AVFrame
operator const AVFrame * () const
operator const AVFrame *: Do as if we were a const pointer to AVFrame
AVFrame * operator-> ()
operator ->: Do as if we were a pointer to AVFrame
FFmpeg_Frame & operator= (const FFmpeg_Frame &frame) noexcept
Make copy from other FFmpeg_Frame object.
FFmpeg_Frame & operator= (const AVFrame *frame) noexcept
Make copy from AVFrame structure.
Public Attributes
int m_stream_idx
Stream index frame belongs to, or -1 (INVALID_STREAM)
Protected Attributes
AVFrame * m_frame
Pointer to underlying AVFrame struct.
int m_res
0 if last operation was successful, or negative AVERROR value
Detailed Description
The FFmpeg_Frame class.
Definition at line 40 of file ffmpeg_frame.h.
Constructor & Destructor Documentation
FFmpeg_Frame() [1/3]
FFmpeg_Frame::FFmpeg_Frame (int stream_index = INVALID_STREAM) explicit
Construct FFmpeg_Frame object.
Parameters
[in] stream_index - Index of stream
Definition at line 48 of file ffmpeg_frame.cc.
References m_frame, and m_res.
FFmpeg_Frame() [2/3]
FFmpeg_Frame::FFmpeg_Frame (const FFmpeg_Frame & frame)
Copy construct from FFmpeg_Frame object.
Parameters
[in] frame - Pointer to source FFmpeg_Frame object.
Note
Do not declare explicit, breaks use in std::variant
Definition at line 56 of file ffmpeg_frame.cc.
References m_frame, and m_res.
FFmpeg_Frame() [3/3]
FFmpeg_Frame::FFmpeg_Frame (const AVFrame * frame)
Copy construct from AVFrame struct.
Parameters
[in] frame - Pointer to source AVFrame struct.
Note
Do not declare explicit, breaks use in std::variant
Definition at line 73 of file ffmpeg_frame.cc.
References m_frame, and m_res.
Member Function Documentation
clone()
AVFrame * FFmpeg_Frame::clone ()
Clone frame to a new AVFrame * struct. Needs to be freed by a av_frame_free() call.
Returns
Returns cloned AVFrame * struct, or nullptr on error.
Definition at line 95 of file ffmpeg_frame.cc.
References m_frame.
get()
AVFrame * FFmpeg_Frame::get ()
Access the underlying frame.
Returns
Returns the unerlying AVFrame * struct, or nullptr not valid.
Definition at line 122 of file ffmpeg_frame.cc.
References m_frame.
operator->()
AVFrame * FFmpeg_Frame::operator-> ()
operator ->: Do as if we were a pointer to AVFrame
Returns
Pointer to AVFrame struct.
Definition at line 137 of file ffmpeg_frame.cc.
References m_frame.
operator=() [1/2]
FFmpeg_Frame & FFmpeg_Frame::operator= (const AVFrame * frame) noexcept
Make copy from AVFrame structure.
Parameters
[in] frame - Pointer to source AVFrame structure.
Returns
Reference to new FFmpeg_Frame object.
Definition at line 160 of file ffmpeg_frame.cc.
References INVALID_STREAM.
operator=() [2/2]
FFmpeg_Frame & FFmpeg_Frame::operator= (const FFmpeg_Frame & frame) noexcept
Make copy from other FFmpeg_Frame object.
Parameters
[in] frame - Reference to source FFmpeg_Frame object.
Returns
Reference to new FFmpeg_Frame object.
Definition at line 142 of file ffmpeg_frame.cc.
res()
int FFmpeg_Frame::res () const
Get result of last operation.
Returns
Returns 0 if last operation was successful, or negative AVERROR value.
Definition at line 117 of file ffmpeg_frame.cc.
References m_res.
Referenced by FFmpeg_Transcoder::create_audio_frame(), FFmpeg_Transcoder::decode_audio_frame(), FFmpeg_Transcoder::decode_video_frame(), FFmpeg_Transcoder::encode_image_frame(), FFmpeg_Transcoder::encode_video_frame(), and FFmpeg_Transcoder::send_filters().
The documentation for this class was generated from the following files:
src/ffmpeg_frame.h
src/ffmpeg_frame.cc