FFmpegfs Fuse Multi Media Filesystem: Logging::Logger Class Reference
Logging::Logger Class Reference
Logging helper class.
Public Member Functions
Logger (LOGLEVEL loglevel, const std::string &filename)
Construct Logger object.
Logger ()
Construct Logger object.
virtual ~Logger ()
Destroy Logger object.
Private Attributes
const LOGLEVEL m_loglevel
Log level required to write log entry.
const std::string m_filename
Name of file for which this log entry was written. May be empty.
Static Private Attributes
static const std::map< LOGLEVEL, int > m_syslog_level_map
Map our log levels to syslog levels.
static const std::map< LOGLEVEL, std::string > m_level_name_map
Map log level enums to strings.
static const std::map< LOGLEVEL, std::string > m_level_colour_map
Map log level enums to colours (logging to stderr only)
Detailed Description
Logging helper class.
Definition at line 113 of file logging.h.
Constructor & Destructor Documentation
Logger() [1/2]
Logging::Logger::Logger (LOGLEVEL loglevel, const std::string & filename) inline
Construct Logger object.
Parameters
[in] loglevel - The maximum level of log output to write.
[in] filename - Name of file for which this log entry was written. May be empty.
Definition at line 121 of file logging.h.
Logger() [2/2]
Logging::Logger::Logger () inline explicit
Construct Logger object.
Definition at line 127 of file logging.h.
~Logger()
Logging::Logger::~Logger () virtual
Destroy Logger object.
Definition at line 109 of file logging.cc.
References COLOUR_DARK_GRAY, COLOUR_LIGHT_PURPLE, COLOUR_LIGHT_RED, COLOUR_RESET, Logging::LOGERROR, FFMPEGFS_PARAMS::m_basepath, m_filename, m_level_name_map, Logging::m_logging, m_loglevel, FFMPEGFS_PARAMS::m_mountpath, Logging::m_mutex, m_syslog_level_map, params, replace_start(), strsprintf(), transcoder_cache_path(), and trim().
Member Data Documentation
m_filename
const std::string Logging::Logger::m_filename private
Name of file for which this log entry was written. May be empty.
Definition at line 137 of file logging.h.
Referenced by ~Logger().
m_level_colour_map
const std::map< Logging::LOGLEVEL, std::string > Logging::Logger::m_level_colour_map static private
Initial value:
=
{
    { LOGERROR,     COLOUR_RED },
    { LOGWARN,      COLOUR_YELLOW },
    { LOGINFO,      COLOUR_WHITE },
    { LOGDEBUG,     COLOUR_GREEN },
    { LOGTRACE,     COLOUR_BLUE },
}
Map log level enums to colours (logging to stderr only)
Definition at line 84 of file logging.h.
m_level_name_map
const std::map< Logging::LOGLEVEL, std::string > Logging::Logger::m_level_name_map static private
Initial value:
=
{
    { LOGERROR,     "ERROR  " },
    { LOGWARN,      "WARNING" },
    { LOGINFO,      "INFO   " },
    { LOGDEBUG,     "DEBUG  " },
    { LOGTRACE,     "TRACE  " },
}
Map log level enums to strings.
Definition at line 75 of file logging.h.
Referenced by ~Logger().
m_loglevel
const LOGLEVEL Logging::Logger::m_loglevel private
Log level required to write log entry.
Definition at line 135 of file logging.h.
Referenced by ~Logger().
m_syslog_level_map
const std::map< Logging::LOGLEVEL, int > Logging::Logger::m_syslog_level_map static private
Initial value:
=
{
    { LOGERROR,     LOG_ERR },
    { LOGWARN,      LOG_WARNING },
    { LOGINFO,      LOG_INFO },
    { LOGDEBUG,     LOG_DEBUG },
    { LOGTRACE,     LOG_DEBUG },
}
Map our log levels to syslog levels.
Definition at line 66 of file logging.h.
Referenced by ~Logger().
The documentation for this class was generated from the following files:
src/logging.h
src/logging.cc