FFmpegfs Fuse Multi Media Filesystem: FileIO Class Reference
FileIO Class Reference abstract
Base class for I/O.
#include <fileio.h>
Public Member Functions
FileIO ()
Create FileIO object.
virtual ~FileIO ()
Free FileIO object.
virtual VIRTUALTYPE type () const =0
Get type of the virtual file.
virtual size_t bufsize () const =0
Get the ideal buffer size.
virtual int open (LPVIRTUALFILE virtualfile)=0
Open a virtual file.
virtual size_t read (void *data, size_t size)=0
Read data from file.
virtual int error () const =0
Get last error.
virtual int64_t duration () const =0
Get the duration of the file, in AV_TIME_BASE fractional seconds.
virtual size_t size () const =0
Get the file size.
virtual size_t tell () const =0
Get current read position.
virtual int seek (int64_t offset, int whence)=0
Seek to position in file.
virtual bool eof () const =0
Check if at end of file.
virtual void close ()=0
Close virtual file.
LPVIRTUALFILE virtualfile ()
Get virtual file object.
const std::string & filename () const
Get source filename.
const std::string & path () const
Path to source file (without file name)
Static Public Member Functions
static FileIO * alloc (VIRTUALTYPE type)
Allocate the correct object for type().
Protected Member Functions
void set_virtualfile (LPVIRTUALFILE virtualfile)
Set the virtual file object.
Private Attributes
std::string m_path
Source path (directory without file name)
LPVIRTUALFILE m_virtualfile
Virtual file object of current file.
Detailed Description
Base class for I/O.
Definition at line 232 of file fileio.h.
Member Function Documentation
alloc()
FileIO * FileIO::alloc (VIRTUALTYPE type) static
Allocate the correct object for type().
Free with delete if no longer required.
Parameters
[in] type - VIRTUALTYPE of new object
Returns
Upon successful completion, FileIO of requested type.
On error (out of memory), returns a nullptr.
Definition at line 71 of file fileio.cc.
References type(), VIRTUALTYPE_BLURAY, VIRTUALTYPE_DISK, VIRTUALTYPE_DVD, and VIRTUALTYPE_VCD.
Referenced by FFmpeg_Transcoder::open_input_file().
bufsize()
virtual size_t FileIO::bufsize () const pure virtual
Get the ideal buffer size.
Returns
Return the ideal buffer size.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
Referenced by FFmpeg_Transcoder::open_input_file().
duration()
virtual int64_t FileIO::duration () const pure virtual
Get the duration of the file, in AV_TIME_BASE fractional seconds.
This is only possible for file formats that are aware of the play time. May be AV_NOPTS_VALUE if the time is not known.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
Referenced by FFmpeg_Transcoder::calculate_predicted_filesize(), and FFmpeg_Transcoder::open_input_file().
eof()
virtual bool FileIO::eof () const pure virtual
Check if at end of file.
Returns
Returns true if at end of file.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
Referenced by FFmpeg_Transcoder::input_read().
error()
virtual int FileIO::error () const pure virtual
Get last error.
Returns
errno value of last error.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
Referenced by FFmpeg_Transcoder::input_read().
filename()
const std::string & FileIO::filename () const
Get source filename.
Returns
Returns source filename.
Definition at line 131 of file fileio.cc.
References VIRTUALFILE::m_destfile, and m_virtualfile.
Referenced by Buffer::init(), Buffer::make_cachefile_name(), Buffer::map_file(), Buffer::reallocate(), Buffer::remove_file(), and Buffer::unmap_file().
open()
virtual int FileIO::open (LPVIRTUALFILE virtualfile) pure virtual
Open a virtual file.
Parameters
[in] virtualfile - LPCVIRTUALFILE of file to open
Returns
Upon successful completion, open() returns 0.
On error, an nonzero value is returned and errno is set to indicate the error.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
Referenced by FFmpeg_Transcoder::open_input_file().
path()
const std::string & FileIO::path () const
Path to source file (without file name)
Returns
Returns path to source file.
Definition at line 126 of file fileio.cc.
References m_path.
Referenced by BlurayIO::open(), DvdIO::open(), VcdIO::open(), BlurayIO::read(), and DvdIO::read().
read()
virtual size_t FileIO::read (void * data, size_t size) pure virtual
Read data from file.
Parameters
[out] data - buffer to store read bytes in. Must be large enough to hold up to size bytes.
[in] size - number of bytes to read
Returns
Upon successful completion, read() returns the number of bytes read.
This may be less than size.
On error, the value 0 is returned and errno is set to indicate the error.
If at end of file, 0 may be returned by errno not set. error() will return 0 if at EOF.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
Referenced by FFmpeg_Transcoder::input_read().
seek()
virtual int FileIO::seek (int64_t offset, int whence) pure virtual
Seek to position in file.
Repositions the offset of the open file to the argument offset according to the directive whence.
Parameters
[in] offset - offset in bytes
[in] whence - how to seek:
SEEK_SET: The offset is set to offset bytes.
SEEK_CUR: The offset is set to its current location plus offset bytes.
SEEK_END: The offset is set to the size of the file plus offset bytes.
Returns
Upon successful completion, seek() returns the resulting offset location as measured in bytes from the beginning of the file.
On error, the value -1 is returned and errno is set to indicate the error.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
Referenced by FFmpeg_Transcoder::seek().
set_virtualfile()
void FileIO::set_virtualfile (LPVIRTUALFILE virtualfile) protected
Set the virtual file object.
Parameters
[in] virtualfile - LPCVIRTUALFILE of file to set.
Definition at line 104 of file fileio.cc.
References VIRTUALFILE::m_origfile, m_path, m_virtualfile, remove_filename(), and virtualfile().
Referenced by BlurayIO::open(), Buffer::open(), DiskIO::open(), DvdIO::open(), and VcdIO::open().
size()
virtual size_t FileIO::size () const pure virtual
Get the file size.
Returns
Returns the file size.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
Referenced by FFmpeg_Transcoder::seek().
tell()
virtual size_t FileIO::tell () const pure virtual
Get current read position.
Returns
Gets the current read position.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
type()
virtual VIRTUALTYPE FileIO::type () const pure virtual
Get type of the virtual file.
Returns
Returns the type of the virtual file.
Implemented in VcdIO, DvdIO, DiskIO, Buffer, and BlurayIO.
Referenced by alloc().
virtualfile()
LPVIRTUALFILE FileIO::virtualfile ()
Get virtual file object.
Returns
Current virtual file object or nullptr if unset.
Definition at line 121 of file fileio.cc.
References m_virtualfile.
Referenced by FFmpeg_Transcoder::encode_finish(), Buffer::have_frame(), Buffer::init(), BlurayIO::open(), Buffer::open(), DiskIO::open(), DvdIO::open(), VcdIO::open(), Buffer::read_frame(), set_virtualfile(), and Buffer::write_frame().
The documentation for this class was generated from the following files:
src/fileio.h
src/fileio.cc