FFmpegfs Fuse Multi Media Filesystem: VcdIO Class Reference
VcdIO Class Reference
Video CD and Super Video CD I/O class.
#include <vcdio.h>
Public Member Functions
VcdIO ()
Create VcdIO object.
virtual ~VcdIO ()
Free VcdIO object.
virtual VIRTUALTYPE type () const override
Get type of the virtual file.
virtual size_t bufsize () const override
Get the ideal buffer size.
virtual int open (LPVIRTUALFILE virtualfile) override
Open a virtual file.
virtual size_t read (void *data, size_t size) override
Read data from file.
virtual int error () const override
Get last error.
virtual int64_t duration () const override
Get the duration of the file, in AV_TIME_BASE fractional seconds.
virtual size_t size () const override
Get the file size.
virtual size_t tell () const override
Get current read position.
virtual int seek (int64_t offset, int whence) override
Seek to position in file.
virtual bool eof () const override
Check if at end of file.
virtual void close () override
Close virtual file.
Public Member Functions inherited from FileIO
FileIO ()
Create FileIO object.
virtual ~FileIO ()=default
Free FileIO object.
LPVIRTUALFILE virtualfile ()
Get virtual file object.
const std::string & filename () const
Get source filename.
const std::string & path () const
Path to source file (without file name)
Protected Attributes
FILE * m_fpi
File pointer to source media.
bool m_full_title
If true, ignore m_chapter_no and provide full track.
int m_track_no
Track number (1..)
int m_chapter_no
Chapter number (1..)
uint64_t m_start_pos
Start offset in bytes.
uint64_t m_end_pos
End offset in bytes (not including this byte)
Private Member Functions
void _close ()
Close virtual file. Non-virtual version to be safely called from constructor/destructor.
Additional Inherited Members
Static Public Member Functions inherited from FileIO
static FileIO * alloc (VIRTUALTYPE type)
Allocate the correct object for type().
Protected Member Functions inherited from FileIO
void set_virtualfile (LPVIRTUALFILE virtualfile)
Set the virtual file object.
Detailed Description
Video CD and Super Video CD I/O class.
Definition at line 45 of file vcdio.h.
Constructor & Destructor Documentation
~VcdIO()
VcdIO::~VcdIO () virtual
Free VcdIO object.
Close file pointers
Definition at line 53 of file vcdio.cc.
References _close().
Member Function Documentation
bufsize()
size_t VcdIO::bufsize () const override virtual
Get the ideal buffer size.
Returns
Return the ideal buffer size.
Implements FileIO.
Definition at line 63 of file vcdio.cc.
duration()
int64_t VcdIO::duration () const override virtual
Get the duration of the file, in AV_TIME_BASE fractional seconds.
Returns
Could work for VCD, but always returns AV_NOPTS_VALUE.
Todo:
Implement duration of video CD chapters
Implements FileIO.
Definition at line 125 of file vcdio.cc.
eof()
bool VcdIO::eof () const override virtual
Check if at end of file.
Returns
Returns true if at end of file.
Implements FileIO.
Definition at line 194 of file vcdio.cc.
References m_end_pos, and m_fpi.
error()
int VcdIO::error () const override virtual
Get last error.
Returns
errno value of last error.
Implements FileIO.
Definition at line 120 of file vcdio.cc.
References m_fpi.
open()
int VcdIO::open (LPVIRTUALFILE virtualfile) override virtual
Open a virtual file.
Parameters
[in] virtualfile - LPCVIRTUALFILE of file to open
Returns
Upon successful completion, open() returns 0.
On error, an nonzero value is returned and errno is set to indicate the error.
Implements FileIO.
Definition at line 68 of file vcdio.cc.
References Logging::info(), VCDUTILS::locate_video(), VIRTUALFILE::VCD_CHAPTER::m_chapter_no, m_chapter_no, VIRTUALFILE::VCD_CHAPTER::m_end_pos, m_end_pos, m_fpi, VIRTUALFILE::m_full_title, m_full_title, VIRTUALFILE::VCD_CHAPTER::m_start_pos, m_start_pos, VIRTUALFILE::VCD_CHAPTER::m_track_no, m_track_no, VIRTUALFILE::m_vcd, FileIO::path(), seek(), FileIO::set_virtualfile(), size(), and FileIO::virtualfile().
read()
size_t VcdIO::read (void * data, size_t size) override virtual
Read data from file.
Parameters
[out] data - buffer to store read bytes in. Must be large enough to hold up to size bytes.
[in] size - number of bytes to read
Returns
Upon successful completion, read() returns the number of bytes read.
This may be less than size.
On error, the value 0 is returned and errno is set to indicate the error.
If at end of file, 0 may be returned by errno not set. error() will return 0 if at EOF.
Implements FileIO.
Definition at line 105 of file vcdio.cc.
References m_end_pos, m_fpi, and size().
seek()
int VcdIO::seek (int64_t offset, int whence) override virtual
Seek to position in file.
Repositions the offset of the open file to the argument offset according to the directive whence.
Parameters
[in] offset - offset in bytes
[in] whence - how to seek:
SEEK_SET: The offset is set to offset bytes.
SEEK_CUR: The offset is set to its current location plus offset bytes.
SEEK_END: The offset is set to the size of the file plus offset bytes.
Returns
Upon successful completion, seek() returns the resulting offset location as measured in bytes from the beginning of the file.
On error, the value -1 is returned and errno is set to indicate the error.
Implements FileIO.
Definition at line 153 of file vcdio.cc.
References m_end_pos, m_fpi, and m_start_pos.
Referenced by open().
size()
size_t VcdIO::size () const override virtual
Get the file size.
Returns
Returns the file size.
Implements FileIO.
Definition at line 130 of file vcdio.cc.
References m_end_pos, m_fpi, and m_start_pos.
Referenced by open(), and read().
tell()
size_t VcdIO::tell () const override virtual
Get current read position.
Returns
Gets the current read position.
Implements FileIO.
Definition at line 148 of file vcdio.cc.
References m_fpi, and m_start_pos.
type()
VIRTUALTYPE VcdIO::type () const override virtual
Get type of the virtual file.
Returns
Returns the type of the virtual file.
Implements FileIO.
Definition at line 58 of file vcdio.cc.
References VIRTUALTYPE_VCD.
The documentation for this class was generated from the following files:
src/vcdio.h
src/vcdio.cc