FFmpegfs Fuse Multi Media Filesystem: Logging Class Reference
Logging Class Reference
Logging facility
#include <logging.h>
Classes
class Logger
Logging helper class.
Public Types
enum class level {
LOGERROR = 1 , LOGWARN = 2 , LOGINFO = 3 , LOGDEBUG = 4 ,
LOGTRACE = 5
}
Logging level types enum.
Public Member Functions
Logging (const std::string &logfile, level max_level, bool to_stderr, bool to_syslog)
bool GetFail () const
Check whether either failbit or badbit is set.
Static Public Member Functions
static bool init_logging (const std::string &logfile, Logging::level max_level, bool to_stderr, bool to_syslog)
Initialise the logging facility.
template<typename... Args>
static void trace (const char *filename, const std::string &format_string, Args &&...args)
Write trace level log entry.
template<typename... Args>
static void trace (const std::string &filename, const std::string &format_string, Args &&...args)
Write trace level log entry.
template<typename... Args>
static void debug (const char *filename, const std::string &format_string, Args &&...args)
Write debug level log entry.
template<typename... Args>
static void debug (const std::string &filename, const std::string &format_string, Args &&...args)
Write debug level log entry.
template<typename... Args>
static void info (const char *filename, const std::string &format_string, Args &&...args)
Write info level log entry.
template<typename... Args>
static void info (const std::string &filename, const std::string &format_string, Args &&...args)
Write info level log entry.
template<typename... Args>
static void warning (const char *filename, const std::string &format_string, Args &&...args)
Write warning level log entry.
template<typename... Args>
static void warning (const std::string &filename, const std::string &format_string, Args &&...args)
Write warning level log entry.
template<typename... Args>
static void error (const char *filename, const std::string &format_string, Args &&...args)
Write error level log entry.
template<typename... Args>
static void error (const std::string &filename, const std::string &format_string, Args &&...args)
Write error level log entry.
static void log_with_level (Logging::level loglevel, const std::string &filename, const std::string &message)
Write log entry.
Static Protected Member Functions
static std::string format_helper (const std::string &string_to_update, const size_t __attribute__((unused)) size)
Standard format_helper without parameters.
template<typename T , typename... Args>
static std::string format_helper (const std::string &string_to_search, const size_t index_to_replace, T &&val, Args &&...args)
format_helper with variadic parameters
template<typename... Args>
static std::string format (const std::string &format_string, Args &&...args)
format string with single token
Protected Attributes
friend Logger
Make logger class our friend.
std::ofstream m_logfile
Log file object for writing to disk.
const level m_max_level
The maximum level of log output to write.
const bool m_to_stderr
Whether to write log output to stderr.
const bool m_to_syslog
Whether to write log output to syslog.
Friends
Logger Log (level loglevel, const std::string &filename)
Make logger class our friend for our constructor.
Detailed Description
Logging facility
Within the log message text, escape sequences are supported for dynamically formatting the message.
Escape sequences have either the form n or %<format specifier>n, where the index n starts at 1.
The index specifies the position of the argument in the list. They can appear in any given order. An index can be used more than once, and not all indexes have to be present (in which case the argument will not be printed). The input value is automatically converted to string format and can be among std::string, char *, int, uint64_t and more.
The format specifier is the same as used in printf/sprintf.
int channels = 2;
int sample_rate = 44100:
Logging::debug(filename, "Audio %1 channels %2 KHz", channels, sample_rate);
Prints "Audio 2 channels 44100 KHz".
int channels = 2;
double sample_rate = 44.1:
Logging::debug(filename, "Audio %1 %<%.3f>2 KHz", channels == 2 ? "stereo" : "mono", sample_rate);
Prints "Audio stereo 44.100 KHz".
Definition at line 73 of file logging.h.
Member Enumeration Documentation
level
enum Logging::level strong
Logging level types enum.
Enumerator
LOGERROR
Error level.
LOGWARN
Warning level.
LOGINFO
Info level.
LOGDEBUG
Debug level.
LOGTRACE
Error level.
Definition at line 78 of file logging.h.
Constructor & Destructor Documentation
Logging()
Logging::Logging (const std::string & logfile, level max_level, bool to_stderr, bool to_syslog) explicit
Construct Logging object
Parameters
[in] logfile - The name of a file to write logging output to. If empty, no output will be written.
[in] max_level - The maximum level of log output to write.
[in] to_stderr - Whether to write log output to stderr.
[in] to_syslog - Whether to write log output to syslog.
Returns
Returns 0 if successful; if <0 on this is an FFmpeg AVERROR value
Definition at line 65 of file logging.cc.
References m_logfile, and m_to_syslog.
Referenced by init_logging().
Member Function Documentation
debug() [1/2]
template<typename... Args> static void Logging::debug (const char * filename, const std::string & format_string, Args &&... args) inline static
Write debug level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be nullptr.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 185 of file logging.h.
References format_helper(), log_with_level(), and LOGDEBUG.
Referenced by FFmpeg_Transcoder::add_albumart_stream(), FFmpeg_Transcoder::add_stream(), FFmpeg_Base::audio_info(), create_dvd_virtualfile(), FFmpeg_Transcoder::decode_frame(), FFmpeg_Transcoder::decode_video_frame(), ffmpegfs_getattr(), ffmpegfs_readdir(), get_source_properties(), FFmpeg_Transcoder::init_deinterlace_filters(), FFmpeg_Transcoder::init_resampler(), FFmpeg_Transcoder::init_rescaler(), kick_next(), link_up(), Cache::load_index(), BlurayIO::open(), DiskIO::open(), DvdIO::open(), FFmpeg_Transcoder::open_decoder(), Buffer::open_file(), FFmpeg_Transcoder::open_input_file(), FFmpeg_Transcoder::open_output_file(), FFmpeg_Transcoder::open_output_filestreams(), FFmpeg_Transcoder::open_output_frame_set(), Cache_Entry::outdated(), parse_bluray(), parse_dvd(), parse_embedded_cuesheet(), parse_vcd(), prepare_script(), FFmpeg_Transcoder::store_packet(), thread_pool::tear_down(), transcode_finish(), transcoder_free(), transcoder_init(), transcoder_new(), transcoder_thread(), Cache::upgrade_db(), and FFmpeg_Base::video_info().
debug() [2/2]
template<typename... Args> static void Logging::debug (const std::string & filename, const std::string & format_string, Args &&... args) inline static
Write debug level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be empty.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 196 of file logging.h.
References format_helper(), log_with_level(), and LOGDEBUG.
error() [1/2]
template<typename... Args> static void Logging::error (const char * filename, const std::string & format_string, Args &&... args) inline static
Write error level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be nullptr.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 254 of file logging.h.
References format_helper(), log_with_level(), and LOGERROR.
Referenced by FFmpeg_Transcoder::add_albumart_frame(), FFmpeg_Transcoder::add_albumart_stream(), FFmpeg_Transcoder::add_samples_to_fifo(), FFmpeg_Transcoder::add_stream(), FFmpeg_Transcoder::add_stream_copy(), FFmpeg_Transcoder::alloc_picture(), Cache::begin_transaction(), check_cuesheet(), Cache::check_min_version(), Buffer::clear(), Cache::column_exists(), FFmpeg_Transcoder::convert_samples(), FFmpeg_Transcoder::create_audio_frame(), create_bluray_virtualfile(), create_cuesheet_virtualfile(), create_dvd_virtualfile(), Cache::create_table_cache_entry(), create_vcd_virtualfile(), FFmpeg_Transcoder::decode(), FFmpeg_Transcoder::decode_audio_frame(), FFmpeg_Transcoder::decode_frame(), FFmpeg_Transcoder::decode_video_frame(), FFmpeg_Base::dict_set_with_check(), FFmpeg_Transcoder::encode_audio_frame(), FFmpeg_Transcoder::encode_image_frame(), FFmpeg_Transcoder::encode_video_frame(), Cache::end_transaction(), ffmpegfs_fgetattr(), ffmpegfs_read(), ffmpegfs_release(), find_original(), Buffer::flush(), FFmpeg_Transcoder::flush_delayed_audio(), FFmpeg_Transcoder::flush_delayed_video(), FFmpeg_Transcoder::get_hw_pix_fmt(), FFmpeg_Transcoder::hwdevice_ctx_add_ref(), FFmpeg_Transcoder::hwdevice_ctx_create(), FFmpeg_Transcoder::hwframe_copy_from_hw(), FFmpeg_Transcoder::hwframe_copy_to_hw(), FFmpeg_Transcoder::hwframe_ctx_set(), Buffer::init(), FFmpeg_Transcoder::init_audio_output_frame(), FFmpeg_Transcoder::init_converted_samples(), FFmpeg_Transcoder::init_deinterlace_filters(), FFmpeg_Transcoder::init_fifo(), FFmpeg_Base::init_frame(), FFmpeg_Transcoder::init_resampler(), FFmpeg_Transcoder::init_rescaler(), FFmpeg_Transcoder::input_read(), link_down(), link_up(), Cache::load_index(), Buffer::map_file(), BlurayIO::open(), DvdIO::open(), FFmpeg_Transcoder::open_bestmatch_decoder(), FFmpeg_Transcoder::open_decoder(), FFmpeg_Transcoder::open_input_file(), FFmpeg_Transcoder::open_output(), FFmpeg_Transcoder::open_output_file(), FFmpeg_Transcoder::open_output_filestreams(), FFmpeg_Transcoder::open_output_frame_set(), FFmpeg_Base::opt_set_with_check(), FFmpeg_Transcoder::output_write(), parse_cuesheet(), parse_dvd(), Cache::prepare_stmts(), FFmpeg_Transcoder::process_single_fr(), BlurayIO::read(), DvdIO::read(), FFmpeg_Transcoder::read_decode_convert_and_store(), Cache::read_info(), Buffer::reserve(), Cache::rollback_transaction(), FFmpeg_Transcoder::seek(), FFmpeg_Transcoder::send_filters(), FFmpeg_Transcoder::skip_decoded_frames(), FFmpeg_Transcoder::stack_seek_frame(), FFmpeg_Transcoder::stack_seek_segment(), start_timer(), stop_timer(), FFmpeg_Transcoder::store_packet(), stream_info(), Cache::table_exists(), transcoder_init(), transcoder_read_frame(), transcoder_set_filesize(), transcoder_thread(), Buffer::unmap_file(), Cache::upgrade_db(), FFmpeg_Transcoder::write_output_file_header(), and FFmpeg_Transcoder::write_output_file_trailer().
error() [2/2]
template<typename... Args> static void Logging::error (const std::string & filename, const std::string & format_string, Args &&... args) inline static
Write error level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be empty.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 265 of file logging.h.
References format_helper(), log_with_level(), and LOGERROR.
format()
template<typename... Args> static std::string Logging::format (const std::string & format_string, Args &&... args) inline static protected
format string with single token
Parameters
[in] format_string - format string to be searched
[in] args - arguments
Returns
Contents of format_string with all tokens replaced.
Definition at line 355 of file logging.h.
References format_helper().
format_helper() [1/2]
template<typename T , typename... Args> static std::string Logging::format_helper (const std::string & string_to_search, const size_t index_to_replace, T && val, Args &&... args) inline static protected
format_helper with variadic parameters
Calls itself recursively until all tokens are replaced.
Parameters
[in] string_to_search - format string to be searched
[in] index_to_replace - index numer (n) to be replaced. May be present 0...x times.
[in] val - replace value to fill into tokens
[in] args - further arguments
Returns
Contents of string_to_search with all tokens replaced.
Definition at line 301 of file logging.h.
References format_helper().
format_helper() [2/2]
std::string Logging::format_helper (const std::string & string_to_update, const size_t __attribute__((unused)) size) static protected
Standard format_helper without parameters.
Parameters
[in] string_to_update - original string
size - unused
Returns
Original string
Definition at line 185 of file logging.cc.
Referenced by debug(), error(), format(), format_helper(), info(), trace(), and warning().
GetFail()
bool Logging::GetFail () const
Check whether either failbit or badbit is set.
Returns
Returns true if either (or both) the failbit or the badbit error state flags is set for the stream.
Definition at line 133 of file logging.cc.
References m_logfile.
info() [1/2]
template<typename... Args> static void Logging::info (const char * filename, const std::string & format_string, Args &&... args) inline static
Write info level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be nullptr.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 208 of file logging.h.
References format_helper(), log_with_level(), and LOGINFO.
Referenced by FFmpeg_Transcoder::add_stream(), FFmpeg_Transcoder::can_copy_stream(), ffmpegfs_destroy(), ffmpegfs_init(), FFmpeg_Transcoder::get_hw_pix_fmt(), thread_pool::init(), link_down(), link_up(), maintenance_handler(), master_check(), VcdIO::open(), FFmpeg_Transcoder::open_decoder(), FFmpeg_Transcoder::open_input_file(), FFmpeg_Transcoder::open_output(), FFmpeg_Transcoder::open_output_filestreams(), FFmpeg_Transcoder::process_single_fr(), stop_timer(), transcode_until(), transcoder_read_frame(), transcoder_thread(), and Cache::upgrade_db().
info() [2/2]
template<typename... Args> static void Logging::info (const std::string & filename, const std::string & format_string, Args &&... args) inline static
Write info level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be empty.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 219 of file logging.h.
References format_helper(), log_with_level(), and LOGINFO.
init_logging()
bool Logging::init_logging (const std::string & logfile, Logging::level max_level, bool to_stderr, bool to_syslog) static
Initialise the logging facility.
Parameters
[in] logfile - The name of a file to write logging output to. If empty, no output will be written.
[in] max_level - The maximum level of log output to write.
[in] to_stderr - Whether to write log output to stderr.
[in] to_syslog - Whether to write log output to syslog.
Returns
On success, returns true. On error, returns false.
Note
Will only fail if the file could not be opened. Writing to stderr or syslog will never fail. errno is not set.
Definition at line 170 of file logging.cc.
References Logging().
Referenced by init_logging().
log_with_level()
void Logging::log_with_level (Logging::level loglevel, const std::string & filename, const std::string & message) static
Write log entry.
Parameters
[in] loglevel - The maximum level of log output to write.
[in] filename - Name of file for which this log entry was written. May be empty.
[in] message - Message to log
Definition at line 180 of file logging.cc.
References Log.
Referenced by debug(), error(), ffmpeg_log(), info(), trace(), and warning().
trace() [1/2]
template<typename... Args> static void Logging::trace (const char * filename, const std::string & format_string, Args &&... args) inline static
Write trace level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be nullptr.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 162 of file logging.h.
References format_helper(), log_with_level(), and LOGTRACE.
Referenced by FFmpeg_Transcoder::add_albumart_frame(), FFmpeg_Transcoder::add_stream(), Cache_Entry::Cache_Entry(), check_bluray(), check_cuesheet(), check_dvd(), check_vcd(), FFmpeg_Transcoder::close(), Cache::close(), Buffer::close_file(), create_bluray_virtualfile(), create_dvd_virtualfile(), FFmpeg_Transcoder::encode_video_frame(), FFmpeg_Transcoder::FFmpeg_Transcoder(), ffmpegfs_fgetattr(), ffmpegfs_getattr(), ffmpegfs_open(), ffmpegfs_read(), ffmpegfs_readdir(), ffmpegfs_readlink(), ffmpegfs_release(), ffmpegfs_statfs(), FFmpeg_Transcoder::init_rescaler(), thread_pool::loop_function(), Buffer::map_file(), master_check(), Cache_Entry::open(), Cache::open(), DvdIO::open(), Buffer::open_file(), FFmpeg_Transcoder::open_input_file(), parse_bluray(), parse_cuesheet(), parse_dvd(), parse_embedded_cuesheet(), prepare_script(), print_params(), FFmpeg_Transcoder::process_metadata(), FFmpeg_Transcoder::read_decode_convert_and_store(), Buffer::reallocate(), thread_pool::schedule_thread(), start_timer(), transcode_until(), transcoder_new(), transcoder_predict_filesize(), transcoder_read(), transcoder_read_frame(), transcoder_set_filesize(), Buffer::unmap_file(), FFmpeg_Transcoder::update_codec(), FFmpeg_Transcoder::update_format(), Cache_Entry::~Cache_Entry(), and FFmpeg_Transcoder::~FFmpeg_Transcoder().
trace() [2/2]
template<typename... Args> static void Logging::trace (const std::string & filename, const std::string & format_string, Args &&... args) inline static
Write trace level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be empty.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 173 of file logging.h.
References format_helper(), log_with_level(), and LOGTRACE.
warning() [1/2]
template<typename... Args> static void Logging::warning (const char * filename, const std::string & format_string, Args &&... args) inline static
Write warning level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be nullptr.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 231 of file logging.h.
References format_helper(), log_with_level(), and LOGWARN.
Referenced by FFmpeg_Transcoder::calculate_predicted_filesize(), FFmpeg_Transcoder::encode_video_frame(), ffmpegfs_readdir(), Cache::load_index(), BlurayIO::open(), FFmpeg_Transcoder::open_input_file(), parse_dvd(), parse_embedded_cuesheet(), prepare_script(), FFmpeg_Transcoder::purge_fifos(), DvdIO::read(), Buffer::remove_file(), FFmpeg_Transcoder::send_filters(), sighandler(), transcode_until(), transcoder_read_frame(), transcoder_set_filesize(), transcoder_thread(), and FFmpeg_Base::video_stream_setup().
warning() [2/2]
template<typename... Args> static void Logging::warning (const std::string & filename, const std::string & format_string, Args &&... args) inline static
Write warning level log entry.
Parameters
[in] filename - Name of file for which this log entry was written. May be empty.
[in] format_string - Format string in ffmpegfs logger format.
[in] args - 0 or more argments for format. See format.
Definition at line 242 of file logging.h.
References format_helper(), log_with_level(), and LOGWARN.
Friends And Related Function Documentation
Log
Logger Log (Logging::level loglevel, const std::string & filename) friend
Make logger class our friend for our constructor.
Parameters
[in] loglevel - Selected loglevel.
[in] filename - If logging to file, use this file name.
Definition at line 165 of file logging.cc.
Referenced by log_with_level().
The documentation for this class was generated from the following files:
src/logging.h
src/logging.cc