FFmpegfs Fuse Multi Media Filesystem: VcdChapter Class Reference
VcdChapter Class Reference
Video CD chapter.
#include <vcdchapter.h>
Public Member Functions
VcdChapter (bool is_svcd)
Construct VcdChapter object.
VcdChapter (const VCDCHAPTER &VcdChapter, bool is_svcd)
Construct VcdChapter object.
VcdChapter (int track_no, int min, int sec, int frame, bool is_svcd, int64_t duration)
Construct VcdChapter object.
virtual ~VcdChapter ()
Destroy VcdChapter object.
bool get_is_svcd () const
Check if this is a Super Video CD.
int get_track_no () const
Get the track number of this chapter.
int get_min () const
Get MSF (minutes, seconds, and fractional seconds/frames) minute.
int get_sec () const
Get MSF (minutes, seconds, and fractional seconds/frames) second.
int get_frame () const
Get MSF (minutes, seconds, and fractional seconds/frames) frame.
int64_t get_duration () const
Get chapter duration, in AV_TIME_BASE fractional seconds.
std::string get_filename () const
Get file name and path of source file (e.g. MPEG/AVSEQ##.MPG).
uint64_t get_start_pos () const
Get file position of chapter in bytes.
uint64_t get_end_pos () const
Get end position of chapter in bytes.
int64_t get_start_time () const
Get start position of chapter in AV_TIME_BASE units.
uint64_t get_size () const
Get the size of this chapter in bytes.
int get_lba () const
Get LBA (large block address) of chapter.
VcdChapter & operator= (VcdChapter const &other)
Assignment operator =.
int operator== (const VcdChapter &other) const
Comparison operator ==.
int operator< (const VcdChapter &other) const
Comparison operator <.
int operator<= (const VcdChapter &other) const
Comparison operator <=.
int operator> (const VcdChapter &other) const
Comparison operator >
int operator>= (const VcdChapter &other) const
Comparison operator >=.
int operator!= (const VcdChapter &other) const
Comparison operator !=.
Protected Member Functions
int read (FILE *fpi, int track_no)
Read file from disk.
Protected Attributes
bool m_is_svcd
true for SVCD, false for VCD
int m_track_no
Track no.
int m_min
MSF minute.
int m_sec
MSF second.
int m_frame
MSF frame.
int64_t m_duration
Chapter duration, in AV_TIME_BASE fractional seconds.
uint64_t m_start_pos
Start offset in bytes.
uint64_t m_end_pos
End offset in bytes (not including this byte)
Friends
class VcdEntries
Detailed Description
Video CD chapter.
Definition at line 60 of file vcdchapter.h.
Constructor & Destructor Documentation
VcdChapter() [1/3]
VcdChapter::VcdChapter (bool is_svcd) explicit
Construct VcdChapter object.
Parameters
[in] is_svcd - true for SVCD CD, false for VCD
Definition at line 37 of file vcdchapter.cc.
VcdChapter() [2/3]
VcdChapter::VcdChapter (const VCDCHAPTER & VcdChapter, bool is_svcd) explicit
Construct VcdChapter object.
Parameters
[in] VcdChapter - source object to copy from
[in] is_svcd - true for SVCD CD, false for VCD
Definition at line 50 of file vcdchapter.cc.
VcdChapter() [3/3]
VcdChapter::VcdChapter (int track_no, int min, int sec, int frame, bool is_svcd, int64_t duration) explicit
Construct VcdChapter object.
Parameters
[in] track_no - track number 1..
[in] min - Start minute
[in] sec - Start second
[in] frame - Start frame
[in] is_svcd - true for SVCD CD, false for VCD
[in] duration - Chapter duration, in AV_TIME_BASE fractional seconds
Definition at line 63 of file vcdchapter.cc.
Member Function Documentation
get_duration()
int64_t VcdChapter::get_duration () const
Get chapter duration, in AV_TIME_BASE fractional seconds.
Returns
Returns the chapter duration, in AV_TIME_BASE fractional seconds.
Definition at line 139 of file vcdchapter.cc.
References m_duration.
Referenced by create_vcd_virtualfile().
get_end_pos()
uint64_t VcdChapter::get_end_pos () const
Get end position of chapter in bytes.
Returns
Returns end position of chapter in bytes.
Definition at line 164 of file vcdchapter.cc.
References m_end_pos.
Referenced by create_vcd_virtualfile().
get_filename()
std::string VcdChapter::get_filename () const
Get file name and path of source file (e.g. MPEG/AVSEQ##.MPG).
Returns
Returns file name and path of source file.
Definition at line 144 of file vcdchapter.cc.
References m_is_svcd, and m_track_no.
get_frame()
int VcdChapter::get_frame () const
Get MSF (minutes, seconds, and fractional seconds/frames) frame.
Each timecode frame is one seventy-fifth of a second.
Returns
Returns MSF frame.
Definition at line 134 of file vcdchapter.cc.
References m_frame.
get_is_svcd()
bool VcdChapter::get_is_svcd () const
Check if this is a Super Video CD.
Returns
Returns true for SVCD, false for VCD.
Definition at line 114 of file vcdchapter.cc.
References m_is_svcd.
get_lba()
int VcdChapter::get_lba () const
Get LBA (large block address) of chapter.
Returns
Returns LBA of chapter.
Definition at line 193 of file vcdchapter.cc.
References m_frame, m_min, and m_sec.
get_min()
int VcdChapter::get_min () const
Get MSF (minutes, seconds, and fractional seconds/frames) minute.
Returns
Returns MSF minute.
Definition at line 124 of file vcdchapter.cc.
References m_min.
get_sec()
int VcdChapter::get_sec () const
Get MSF (minutes, seconds, and fractional seconds/frames) second.
Returns
Returns MSF second.
Definition at line 129 of file vcdchapter.cc.
References m_sec.
get_size()
uint64_t VcdChapter::get_size () const
Get the size of this chapter in bytes.
Returns
Returns chapter size in bytes.
Definition at line 169 of file vcdchapter.cc.
References m_end_pos, and m_start_pos.
Referenced by create_vcd_virtualfile().
get_start_pos()
uint64_t VcdChapter::get_start_pos () const
Get file position of chapter in bytes.
Returns
Returns file position of chapter in bytes.
Definition at line 159 of file vcdchapter.cc.
References m_start_pos.
Referenced by create_vcd_virtualfile().
get_start_time()
int64_t VcdChapter::get_start_time () const
Get start position of chapter in AV_TIME_BASE units.
Returns
Returns start position of chapter in AV_TIME_BASE units.
Definition at line 174 of file vcdchapter.cc.
References m_frame, m_min, and m_sec.
Referenced by VcdEntries::load_file(), and VcdEntries::scan_chapters().
get_track_no()
int VcdChapter::get_track_no () const
Get the track number of this chapter.
Returns
Returns track number.
Definition at line 119 of file vcdchapter.cc.
References m_track_no.
Referenced by create_vcd_virtualfile().
operator!=()
int VcdChapter::operator!= (const VcdChapter & other) const
Comparison operator !=.
Parameters
[in] other
Returns
Nonzero if this object is not equal, 0 if equal
Definition at line 343 of file vcdchapter.cc.
References m_frame, m_min, m_sec, and m_track_no.
operator<()
int VcdChapter::operator< (const VcdChapter & other) const
Comparison operator <.
Parameters
[in] other
Returns
Nonzero if this object is smaller, 0 if not
Definition at line 223 of file vcdchapter.cc.
References m_frame, m_min, m_sec, and m_track_no.
operator<=()
int VcdChapter::operator<= (const VcdChapter & other) const
Comparison operator <=.
Parameters
[in] other
Returns
Nonzero if this object is smaller or equal, 0 if not
Definition at line 273 of file vcdchapter.cc.
operator=()
VcdChapter & VcdChapter::operator= (VcdChapter const & other)
Assignment operator =.
Parameters
[in] other
Returns
this
Definition at line 198 of file vcdchapter.cc.
References m_duration, m_end_pos, m_frame, m_is_svcd, m_min, m_sec, m_start_pos, and m_track_no.
operator==()
int VcdChapter::operator== (const VcdChapter & other) const
Comparison operator ==.
Parameters
[in] other
Returns
Nonzero if equal, 0 if not
Definition at line 215 of file vcdchapter.cc.
References m_frame, m_min, m_sec, and m_track_no.
operator>()
int VcdChapter::operator> (const VcdChapter & other) const
Comparison operator >
Parameters
[in] other
Returns
Nonzero if this object is greater, 0 if not
Definition at line 283 of file vcdchapter.cc.
References m_frame, m_min, m_sec, and m_track_no.
operator>=()
int VcdChapter::operator>= (const VcdChapter & other) const
Comparison operator >=.
Parameters
[in] other
Returns
Nonzero if this object is greater or equal, 0 if not
Definition at line 333 of file vcdchapter.cc.
read()
int VcdChapter::read (FILE * fpi, int track_no) protected
Read file from disk.
Parameters
[in] fpi - Open file object to read from
[in] track_no - Track number 1...
Returns
Definition at line 81 of file vcdchapter.cc.
References BCD2DEC, m_frame, VCDMSF::m_frame, m_min, VCDMSF::m_min, m_sec, VCDMSF::m_sec, m_track_no, and SYNC.
Referenced by VcdEntries::scan_chapters().
The documentation for this class was generated from the following files:
src/vcd/vcdchapter.h
src/vcd/vcdchapter.cc