FFmpegfs Fuse Multi Media Filesystem: DvdIO Class Reference
DvdIO Class Reference
DVD I/O class.
#include <dvdio.h>
Public Member Functions
DvdIO ()
Create DvdIO object.
virtual ~DvdIO ()
Free DvdIO object.
virtual VIRTUALTYPE type () const override
Get type of the virtual file.
virtual size_t bufsize () const override
Get the ideal buffer size.
virtual int open (LPVIRTUALFILE virtualfile) override
Open a virtual file.
virtual size_t read (void *data, size_t size) override
Read data from file.
virtual int error () const override
Get last error.
virtual int64_t duration () const override
Get the duration of the file, in AV_TIME_BASE fractional seconds.
virtual size_t size () const override
Get the file size.
virtual size_t tell () const override
Get current read position.
virtual int seek (int64_t offset, int whence) override
Seek to position in file.
virtual bool eof () const override
Check if at end of file.
virtual void close () override
Close virtual file.
Public Member Functions inherited from FileIO
FileIO ()
Create FileIO object.
virtual ~FileIO ()=default
Free FileIO object.
LPVIRTUALFILE virtualfile ()
Get virtual file object.
const std::string & filename () const
Get source filename.
const std::string & path () const
Path to source file (without file name)
Protected Attributes
dvd_reader_t * m_dvd
DVD reader handle.
dvd_file_t * m_dvd_title
DVD title handle.
ifo_handle_t * m_vmg_file
DVD video manager handle.
ifo_handle_t * m_vts_file
DVD video title stream handle.
pgc_t * m_cur_pgc
Current program chain.
int m_start_cell
Start cell.
int m_end_cell
End cell (of title)
int m_cur_cell
Current cell.
int m_next_cell
Next cell to be processed.
bool m_goto_next_cell
If logc needs to go to next cell before next read.
unsigned int m_cur_block
Current processing block.
bool m_is_eof
true if at "end of file", i.e, end of chapter or title
int m_errno
errno of last operation
size_t m_rest_size
Rest bytes in buffer.
size_t m_rest_pos
Position in buffer.
size_t m_cur_pos
Current position in virtual file.
bool m_full_title
If true, ignore m_chapter_no and provide full track.
int m_title_idx
Track index (track number - 1)
int m_chapter_idx
Chapter index (chapter number - 1)
int m_angle_idx
Selected angle index (angle number -1)
unsigned char m_data [1024 *DVD_VIDEO_LB_LEN]
Buffer for read() data.
unsigned char m_buffer [1024 *DVD_VIDEO_LB_LEN]
Buffer for data extracted from VOB file.
int64_t m_duration
Track/chapter duration, in AV_TIME_BASE fractional seconds.
size_t m_size
Size of virtual file.
Private Types
enum DSITYPE { DSITYPE_CONTINUE , DSITYPE_EOF_CHAPTER , DSITYPE_EOF_TITLE }
Type of a DSI block.
typedef enum DvdIO::DSITYPE DSITYPE
Type of a DSI block.
Private Member Functions
void _close ()
Close virtual file. Non-virtual version to be safely called from constructor/destructor.
bool is_nav_pack (const unsigned char *buffer) const
Do a rough check if this is really a navigation packet.
bool get_packet_size (const uint8_t *p, size_t peek, size_t *size) const
return the size of the next packet
int get_pes_id (const uint8_t *buffer, size_t size) const
return the id of a Packetized Elementary Stream (PES) (should be valid)
size_t demux_pes (uint8_t *out, const uint8_t *in, size_t len) const
Extract only the interesting portion of the VOB input stream.
DSITYPE handle_DSI (void *_dsi_pack, size_t *cur_output_size, unsigned int *next_block, uint8_t *data)
Handle DSI (Data Search Information) packet.
void next_cell ()
Goto next DVD cell.
void rewind ()
Rewind to start of stream.
Additional Inherited Members
Static Public Member Functions inherited from FileIO
static FileIO * alloc (VIRTUALTYPE type)
Allocate the correct object for type().
Protected Member Functions inherited from FileIO
void set_virtualfile (LPVIRTUALFILE virtualfile)
Set the virtual file object.
Detailed Description
DVD I/O class.
Definition at line 47 of file dvdio.h.
Member Typedef Documentation
DSITYPE
typedef enum DvdIO::DSITYPE DvdIO::DSITYPE private
Type of a DSI block.
This is used to identify a DSI block on a DVD: Until end of a chapter we simply continue. At the end of chapters we may stop continue to the end of a title
Member Enumeration Documentation
DSITYPE
enum DvdIO::DSITYPE private
Type of a DSI block.
This is used to identify a DSI block on a DVD: Until end of a chapter we simply continue. At the end of chapters we may stop continue to the end of a title
Enumerator
DSITYPE_CONTINUE
Chapter continues.
DSITYPE_EOF_CHAPTER
End of chapter.
DSITYPE_EOF_TITLE
End of title.
Definition at line 56 of file dvdio.h.
Member Function Documentation
bufsize()
size_t DvdIO::bufsize () const override virtual
Get the ideal buffer size.
Returns
Return the ideal buffer size.
Implements FileIO.
Definition at line 82 of file dvdio.cc.
References m_data.
demux_pes()
size_t DvdIO::demux_pes (uint8_t * out, const uint8_t * in, size_t len) const private
Extract only the interesting portion of the VOB input stream.
Parameters
[out] out - Stream stripped from unnessessary data
[in] in - Input raw stream
[in] len - Length of input raw stream
Returns
Size of restulting data block.
Definition at line 390 of file dvdio.cc.
References get_packet_size(), get_pes_id(), PS_STREAM_ID, PS_STREAM_ID_AUDIO, PS_STREAM_ID_END_STREAM, PS_STREAM_ID_MAP, PS_STREAM_ID_PACK_HEADER, PS_STREAM_ID_SYSTEM_HEADER, and size().
Referenced by read().
duration()
int64_t DvdIO::duration () const override virtual
Get the duration of the file, in AV_TIME_BASE fractional seconds.
Returns
Returns the duration of the file, in AV_TIME_BASE fractional seconds.
Implements FileIO.
Definition at line 708 of file dvdio.cc.
References m_duration.
eof()
bool DvdIO::eof () const override virtual
Check if at end of file.
Returns
Returns true if at end of file.
Implements FileIO.
Definition at line 794 of file dvdio.cc.
References m_is_eof.
Referenced by open(), and seek().
error()
int DvdIO::error () const override virtual
Get last error.
Returns
errno value of last error.
Implements FileIO.
Definition at line 703 of file dvdio.cc.
References m_errno.
get_packet_size()
bool DvdIO::get_packet_size (const uint8_t * p, size_t peek, size_t * size) const private
return the size of the next packet
Parameters
[in] p - Buffer with PES data.
[in] peek - How many bytes to peek.
[in] size - Size of the next packet
Returns
Size ofr ID invalid.
Definition at line 238 of file dvdio.cc.
References PS_STREAM_ID, PS_STREAM_ID_DIRECTORY, PS_STREAM_ID_END_STREAM, PS_STREAM_ID_MAP, PS_STREAM_ID_PACK_HEADER, PS_STREAM_ID_SYSTEM_HEADER, and size().
Referenced by demux_pes().
get_pes_id()
int DvdIO::get_pes_id (const uint8_t * buffer, size_t size) const private
return the id of a Packetized Elementary Stream (PES) (should be valid)
Parameters
[in] buffer - Buffer with PES data.
[in] size - Size of buffer.
Returns
The id of a PES (should be valid)
Definition at line 286 of file dvdio.cc.
References PS_STREAM_ID, PS_STREAM_ID_EXTENDED, PS_STREAM_ID_PRIVATE_STREAM1, and size().
Referenced by demux_pes().
handle_DSI()
DvdIO::DSITYPE DvdIO::handle_DSI (void * _dsi_pack, size_t * cur_output_size, unsigned int * next_block, uint8_t * data) private
Handle DSI (Data Search Information) packet.
Parameters
[out] _dsi_pack - buffer with DSI packet.
[out] cur_output_size - Net size of packet.
[out] next_block - Address of next VOBU (Video Object Unit).
[out] data - Data extracted from DSI packet.
Returns
Definition at line 441 of file dvdio.cc.
References DSITYPE_CONTINUE, DSITYPE_EOF_CHAPTER, DSITYPE_EOF_TITLE, m_angle_idx, m_cur_block, m_cur_cell, m_cur_pgc, m_end_cell, m_next_cell, and next_cell().
Referenced by read().
is_nav_pack()
bool DvdIO::is_nav_pack (const unsigned char * buffer) const private
Do a rough check if this is really a navigation packet.
Parameters
[in] buffer - Buffer with data.
Returns
true if the pack is a NAV pack.
Definition at line 833 of file dvdio.cc.
Referenced by read().
open()
int DvdIO::open (LPVIRTUALFILE virtualfile) override virtual
Open a virtual file.
Parameters
[in] virtualfile - LPCVIRTUALFILE of file to open
Returns
Upon successful completion, open() returns 0.
On error, an nonzero value is returned and errno is set to indicate the error.
Implements FileIO.
Definition at line 87 of file dvdio.cc.
References Logging::debug(), eof(), Logging::error(), m_angle_idx, VIRTUALFILE::DVD_CHAPTER::m_angle_no, m_chapter_idx, VIRTUALFILE::DVD_CHAPTER::m_chapter_no, m_cur_pgc, m_duration, VIRTUALFILE::m_duration, m_dvd, VIRTUALFILE::m_dvd, m_dvd_title, m_end_cell, m_full_title, VIRTUALFILE::m_full_title, m_size, m_start_cell, m_title_idx, VIRTUALFILE::DVD_CHAPTER::m_title_no, m_vmg_file, m_vts_file, FileIO::path(), read(), rewind(), FileIO::set_virtualfile(), Logging::trace(), and FileIO::virtualfile().
read()
size_t DvdIO::read (void * data, size_t size) override virtual
Read data from file.
Parameters
[out] data - buffer to store read bytes in. Must be large enough to hold up to size bytes. Special case: If set to nullptr as many bytes as possible are "read" (and discarded). Can be used to determine the net file size of the virtual stream.
[in] size - number of bytes to read
Returns
Upon successful completion, read() returns the number of bytes read.
This may be less than size.
On error, the value 0 is returned and errno is set to indicate the error.
If at end of file, 0 may be returned by errno not set. error() will return 0 if at EOF.
Implements FileIO.
Definition at line 554 of file dvdio.cc.
References demux_pes(), DSITYPE_CONTINUE, DSITYPE_EOF_TITLE, Logging::error(), handle_DSI(), is_nav_pack(), m_buffer, m_cur_block, m_cur_cell, m_cur_pgc, m_cur_pos, m_data, m_dvd_title, m_errno, m_full_title, m_goto_next_cell, m_is_eof, m_next_cell, m_rest_pos, m_rest_size, next_cell(), FileIO::path(), size(), and Logging::warning().
Referenced by open(), and seek().
seek()
int DvdIO::seek (int64_t offset, int whence) override virtual
Seek to position in file.
Repositions the offset of the open file to the argument offset according to the directive whence.
Parameters
[in] offset - offset in bytes
[in] whence - how to seek:
SEEK_SET: The offset is set to offset bytes.
SEEK_CUR: The offset is set to its current location plus offset bytes.
SEEK_END: The offset is set to the size of the file plus offset bytes.
Returns
Upon successful completion, seek() returns the resulting offset location as measured in bytes from the beginning of the file.
On error, the value -1 is returned and errno is set to indicate the error.
Implements FileIO.
Definition at line 736 of file dvdio.cc.
References eof(), read(), rewind(), size(), and tell().
size()
size_t DvdIO::size () const override virtual
Get the file size.
Returns
Returns the file size.
Implements FileIO.
Definition at line 713 of file dvdio.cc.
References m_size.
Referenced by demux_pes(), get_packet_size(), get_pes_id(), read(), and seek().
tell()
size_t DvdIO::tell () const override virtual
Get current read position.
Returns
Gets the current read position.
Implements FileIO.
Definition at line 718 of file dvdio.cc.
References m_cur_pos.
Referenced by seek().
type()
VIRTUALTYPE DvdIO::type () const override virtual
Get type of the virtual file.
Returns
Returns the type of the virtual file.
Implements FileIO.
Definition at line 77 of file dvdio.cc.
References VIRTUALTYPE_DVD.
The documentation for this class was generated from the following files:
src/dvdio.h
src/dvdio.cc