FFmpegfs Fuse Multi Media Filesystem: VcdInfo Class Reference
VcdInfo Class Reference
The VcdInfo class.
#include <vcdinfo.h>
Public Member Functions
VcdInfo ()
Construct VcdInfo object.
virtual ~VcdInfo ()=default
Destruct VcdInfo object.
void clear ()
Reset this object.
int load_file (const std::string &path)
Load VCD from path.
const time_t & get_file_date () const
Date of disk (of INFO.VCD or SVD)
const std::string & get_id () const
Get disk ID.
VCDTYPE get_type () const
Get disk type.
std::string get_type_str () const
Get disk type as string.
VCDPROFILETAG get_profile_tag () const
Get disk profile tag.
std::string get_profile_tag_str () const
Get disk profile tag as string.
const std::string & get_album_id () const
Get album ID.
int get_number_of_cds () const
Get number of CDs in set.
int get_cd_number () const
Get CD number in set.
Protected Attributes
std::string m_disk_path
Path to disk.
time_t m_file_date
File date.
std::string m_id
ID of this CD.
VCDTYPE m_type
Type of CD.
VCDPROFILETAG m_profile_tag
System profile tag.
std::string m_album_id
Album ID.
int m_number_of_cds
Number of CDs in set.
int m_cd_number
Number of this CD in set.
Detailed Description
The VcdInfo class.
Definition at line 38 of file vcdinfo.h.
Member Function Documentation
load_file()
int VcdInfo::load_file (const std::string & path)
Load VCD from path.
Parameters
[in] path - path to locate VCD in
Returns
If successful, returns 0; otherwise, returns errno.
Definition at line 132 of file vcdinfo.cc.
References clear(), VCDUTILS::convert_txt2string(), VCDUTILS::get_directory(), VCDUTILS::locate_file(), m_album_id, VCDINFO::m_albumid, VCDINFO::m_cd_number, m_cd_number, m_disk_path, m_file_date, VCDINFO::m_ID, m_id, m_number_of_cds, VCDINFO::m_numberof_cds, VCDINFO::m_profile_tag, m_profile_tag, VCDINFO::m_type, and m_type.
The documentation for this class was generated from the following files:
src/vcd/vcdinfo.h
src/vcd/vcdinfo.cc