FFmpegfs Fuse Multi Media Filesystem: FFmpeg_Base Class Reference
FFmpeg_Base Class Reference abstract
The FFmpeg_Base class.
#include <ffmpeg_base.h>
Public Member Functions
FFmpeg_Base ()
Construct FFmpeg_Base object.
virtual ~FFmpeg_Base ()
Destruct FFmpeg_Base object.
Protected Member Functions
void video_stream_setup (AVCodecContext *output_codec_ctx, AVStream *output_stream, AVCodecContext *input_codec_ctx, AVRational framerate, AVPixelFormat enc_hw_pix_fmt) const
Set up video stream.
int dict_set_with_check (AVDictionary **pm, const char *key, const char *value, int flags, const char *filename=nullptr, bool nodelete=false) const
Call av_dict_set and check result code. Displays an error message if appropriate.
int dict_set_with_check (AVDictionary **pm, const char *key, int64_t value, int flags, const char *filename=nullptr, bool nodelete=false) const
Call av_dict_set and check result code. Displays an error message if appropriate.
int opt_set_with_check (void *obj, const char *key, const char *value, int flags, const char *filename=nullptr) const
Call av_opt_set and check result code. Displays an error message if appropriate.
void video_info (bool out_file, const AVFormatContext *format_ctx, const AVStream *stream) const
Print info of video stream to log.
void audio_info (bool out_file, const AVFormatContext *format_ctx, const AVStream *stream) const
Print info of audio stream to log.
void subtitle_info (bool out_file, const AVFormatContext *format_ctx, const AVStream *stream) const
Print info of subtitle stream to log.
virtual const char * filename () const =0
Return source filename. Must be implemented in child class.
virtual const char * destname () const =0
Return destination filename. Must be implemented in child class.
uint32_t pts_to_frame (AVStream *stream, int64_t pts) const
Convert PTS value to frame number.
int64_t frame_to_pts (AVStream *stream, uint32_t frame_no) const
FrameToPts.
int get_channels (const AVCodecParameters *codecpar) const
Get number of channels from AVCodecParameters.
void set_channels (AVCodecParameters *codecpar_out, const AVCodecParameters *codecpar_in) const
Set number of channels from AVCodecParameters.
int get_channels (const AVCodecContext *codec_ctx) const
Get number of channels from AVCodecContext.
void set_channels (AVCodecContext *codec_ctx_out, const AVCodecContext *codec_ctx_in) const
Set number of channels from AVCodecContext.
void set_channels (AVCodecContext *codec_ctx_out, int channels) const
Set number of channels from AVCodecContext.
int get_script_info (AVCodecContext *codec_ctx, int play_res_x, int play_res_y, const char *font, int font_size, int primary_color, int secondary_color, int outline_color, int back_color, int bold, int italic, int underline, int border_style, int alignment) const
Generate a suitable AVCodecContext.subtitle_header for SUBTITLE_ASS. Nicked from FFmpeg API's ff_ass_subtitle_header_full() function :)
Static Protected Member Functions
static std::string get_pix_fmt_name (AVPixelFormat pix_fmt)
Calls av_get_pix_fmt_name and returns a std::string with the pix format name.
static std::string get_sample_fmt_name (AVSampleFormat sample_fmt)
Calls av_get_sample_fmt_name and returns a std::string with the format name.
static std::string get_channel_layout_name (const AVChannelLayout *ch_layout)
Calls av_channel_layout_describe and returns a std::string with the channel layout.
Protected Attributes
VIRTUALFILE * m_virtualfile
Underlying virtual file object.
Detailed Description
The FFmpeg_Base class.
Definition at line 45 of file ffmpeg_base.h.
Member Function Documentation
audio_info()
void FFmpeg_Base::audio_info (bool out_file, const AVFormatContext * format_ctx, const AVStream * stream) const protected
Print info of audio stream to log.
Parameters
[in] out_file - true if file is output.
[in] format_ctx - AVFormatContext belonging to stream.
[in] stream - Stream to show information for.
Definition at line 248 of file ffmpeg_base.cc.
References Logging::debug(), destname(), ffmpeg_rescale_q_rnd(), filename(), format_bitrate(), format_duration(), format_samplerate(), get_channels(), and get_codec_name().
Referenced by FFmpeg_Transcoder::open_bestmatch_audio(), and FFmpeg_Transcoder::open_output().
destname()
virtual const char* FFmpeg_Base::destname () const protected pure virtual
Return destination filename. Must be implemented in child class.
Returns
Returns filename.
Implemented in FFmpeg_Transcoder.
Referenced by audio_info(), subtitle_info(), and video_info().
dict_set_with_check() [1/2]
int FFmpeg_Base::dict_set_with_check (AVDictionary ** pm, const char * key, const char * value, int flags, const char * filename = nullptr, bool nodelete = false) const protected
Call av_dict_set and check result code. Displays an error message if appropriate.
Parameters
[in] pm - pointer to a pointer to a dictionary struct.
[in] key - entry key to add to *pm.
[in] value - entry value to add to *pm.
[in] flags - AV_DICT_* flags.
[in] filename - Filename this frame is created for. Used for logging only, may be nullptr.
[in] nodelete - If true, does not delete tag if value is 0.
Returns
On success returns 0; on error negative AVERROR.
Definition at line 177 of file ffmpeg_base.cc.
References Logging::error(), ffmpeg_geterror(), and filename().
Referenced by FFmpeg_Transcoder::add_stream(), FFmpeg_Transcoder::add_subtitle_stream(), FFmpeg_Transcoder::copy_metadata(), FFmpeg_Transcoder::open_input_file(), FFmpeg_Transcoder::open_output_frame_set(), FFmpeg_Transcoder::process_metadata(), and FFmpeg_Transcoder::update_format().
dict_set_with_check() [2/2]
int FFmpeg_Base::dict_set_with_check (AVDictionary ** pm, const char * key, int64_t value, int flags, const char * filename = nullptr, bool nodelete = false) const protected
Call av_dict_set and check result code. Displays an error message if appropriate.
Parameters
[in] pm - pointer to a pointer to a dictionary struct.
[in] key - entry key to add to *pm.
[in] value - entry value to add to *pm.
[in] flags - AV_DICT_* flags.
[in] filename - Filename this frame is created for. Used for logging only, may be nullptr.
[in] nodelete - If true, does not delete tag if value is 0.
Returns
On success returns 0; on error negative AVERROR.
Definition at line 194 of file ffmpeg_base.cc.
References Logging::error(), ffmpeg_geterror(), and filename().
filename()
virtual const char* FFmpeg_Base::filename () const protected pure virtual
Return source filename. Must be implemented in child class.
Returns
Returns filename.
Implemented in FFmpeg_Transcoder.
Referenced by audio_info(), dict_set_with_check(), opt_set_with_check(), subtitle_info(), and video_info().
frame_to_pts()
int64_t FFmpeg_Base::frame_to_pts (AVStream * stream, uint32_t frame_no) const protected
FrameToPts.
Parameters
[in] stream - Source video stream.
[in] frame_no - Number of frame.
Returns
Returns PTS of frame in stream's time_base units.
Definition at line 329 of file ffmpeg_base.cc.
Referenced by FFmpeg_Transcoder::do_seek_frame(), and FFmpeg_Transcoder::encode_image_frame().
get_channel_layout_name()
std::string FFmpeg_Base::get_channel_layout_name (const AVChannelLayout * ch_layout) static protected
Calls av_channel_layout_describe and returns a std::string with the channel layout.
Parameters
[in] ch_layout - Channel layout
Returns
Returns a std::string with the channel layout.
Definition at line 303 of file ffmpeg_base.cc.
Referenced by FFmpeg_Transcoder::init_resampler().
get_channels() [1/2]
int FFmpeg_Base::get_channels (const AVCodecContext * codec_ctx) const protected
Get number of channels from AVCodecContext.
Parameters
[in] codec_ctx - AVCodecContext to check
Returns
Returns number of channels
Definition at line 354 of file ffmpeg_base.cc.
get_channels() [2/2]
int FFmpeg_Base::get_channels (const AVCodecParameters * codecpar) const protected
Get number of channels from AVCodecParameters.
Parameters
[in] codecpar - AVCodecParameters to check
Returns
Returns number of channels
Definition at line 336 of file ffmpeg_base.cc.
Referenced by FFmpeg_Transcoder::add_stream(), audio_info(), FFmpeg_Transcoder::calculate_predicted_filesize(), FFmpeg_Transcoder::convert_samples(), FFmpeg_Transcoder::init_audio_fifo(), and FFmpeg_Transcoder::init_converted_samples().
get_pix_fmt_name()
std::string FFmpeg_Base::get_pix_fmt_name (AVPixelFormat pix_fmt) static protected
Calls av_get_pix_fmt_name and returns a std::string with the pix format name.
Parameters
[in] pix_fmt - AVPixelFormat enum to convert.
Returns
Returns a std::string with the pix format name.
Definition at line 291 of file ffmpeg_base.cc.
Referenced by FFmpeg_Transcoder::init_rescaler(), and FFmpeg_Transcoder::open_output_frame_set().
get_sample_fmt_name()
std::string FFmpeg_Base::get_sample_fmt_name (AVSampleFormat sample_fmt) static protected
Calls av_get_sample_fmt_name and returns a std::string with the format name.
Parameters
[in] sample_fmt - AVSampleFormat enum to convert.
Returns
Returns a std::string with the format name.
Definition at line 297 of file ffmpeg_base.cc.
Referenced by FFmpeg_Transcoder::init_resampler().
get_script_info()
int FFmpeg_Base::get_script_info (AVCodecContext * codec_ctx, int play_res_x, int play_res_y, const char * font, int font_size, int primary_color, int secondary_color, int outline_color, int back_color, int bold, int italic, int underline, int border_style, int alignment) const protected
Generate a suitable AVCodecContext.subtitle_header for SUBTITLE_ASS. Nicked from FFmpeg API's ff_ass_subtitle_header_full() function :)
Parameters
[in] codec_ctx pointer to the AVCodecContext
[in] play_res_x subtitle frame width
[in] play_res_y subtitle frame height
[in] font name of the default font face to use
[in] font_size default font size to use
[in] primary_color default text color to use (ABGR)
[in] secondary_color default secondary text color to use (ABGR)
[in] outline_color default outline color to use (ABGR)
[in] back_color default background color to use (ABGR)
[in] bold 1 for bold text, 0 for normal text
[in] italic 1 for italic text, 0 for normal text
[in] underline 1 for underline text, 0 for normal text
[in] border_style 1 for outline, 3 for opaque box
[in] alignment position of the text (left, center, top...), defined after the layout of the numpad (1-3 sub, 4-6 mid, 7-9 top)
Returns
On success returns 0; on error negative AVERROR.
Definition at line 387 of file ffmpeg_base.cc.
References FFMPEFS_VERSION.
Referenced by FFmpeg_Transcoder::add_subtitle_stream().
opt_set_with_check()
int FFmpeg_Base::opt_set_with_check (void * obj, const char * key, const char * value, int flags, const char * filename = nullptr) const protected
Call av_opt_set and check result code. Displays an error message if appropriate.
Parameters
[in] obj - A struct whose first element is a pointer to an AVClass.
[in] key - the name of the field to set
[in] value - The value to set.
[in] flags - flags passed to av_opt_find2.
[in] filename - Filename this frame is created for. Used for logging only, may be nullptr.
Returns
On success returns 0; on error negative AVERROR.
Definition at line 211 of file ffmpeg_base.cc.
References Logging::error(), ffmpeg_geterror(), and filename().
Referenced by FFmpeg_Transcoder::update_codec().
pts_to_frame()
uint32_t FFmpeg_Base::pts_to_frame (AVStream * stream, int64_t pts) const protected
Convert PTS value to frame number.
Parameters
[in] stream - Source video stream.
[in] pts - PTS of current frame in stream's time_base units.
Returns
Returns frame number.
Definition at line 318 of file ffmpeg_base.cc.
Referenced by FFmpeg_Transcoder::encode_image_frame(), and FFmpeg_Transcoder::skip_decoded_frames().
set_channels() [1/3]
void FFmpeg_Base::set_channels (AVCodecContext * codec_ctx_out, const AVCodecContext * codec_ctx_in) const protected
Set number of channels from AVCodecContext.
Parameters
[in,out] codec_ctx_out - AVCodecContext to set channels for
[in] codec_ctx_in - AVCodecContext to copy channels from
Definition at line 363 of file ffmpeg_base.cc.
set_channels() [2/3]
void FFmpeg_Base::set_channels (AVCodecContext * codec_ctx_out, int channels) const protected
Set number of channels from AVCodecContext.
Parameters
[in,out] codec_ctx_out - AVCodecContext to set
[in] channels - Number of channels to set
Definition at line 372 of file ffmpeg_base.cc.
set_channels() [3/3]
void FFmpeg_Base::set_channels (AVCodecParameters * codecpar_out, const AVCodecParameters * codecpar_in) const protected
Set number of channels from AVCodecParameters.
Parameters
[in,out] codecpar_out - AVCodecParameters to set
[in] codecpar_in - AVCodecParameters to get channels from
Definition at line 345 of file ffmpeg_base.cc.
Referenced by FFmpeg_Transcoder::add_stream().
subtitle_info()
void FFmpeg_Base::subtitle_info (bool out_file, const AVFormatContext * format_ctx, const AVStream * stream) const protected
Print info of subtitle stream to log.
Parameters
[in] out_file - true if file is output.
[in] format_ctx - AVFormatContext belonging to stream.
[in] stream - Stream to show information for.
Definition at line 275 of file ffmpeg_base.cc.
References Logging::debug(), destname(), filename(), and get_codec_name().
Referenced by FFmpeg_Transcoder::open_output(), and FFmpeg_Transcoder::open_subtitles().
video_info()
void FFmpeg_Base::video_info (bool out_file, const AVFormatContext * format_ctx, const AVStream * stream) const protected
Print info of video stream to log.
Parameters
[in] out_file - true if file is output.
[in] format_ctx - AVFormatContext belonging to stream.
[in] stream - Stream to show information for.
Definition at line 223 of file ffmpeg_base.cc.
References Logging::debug(), destname(), ffmpeg_rescale_q_rnd(), filename(), format_bitrate(), format_duration(), and get_codec_name().
Referenced by FFmpeg_Transcoder::open_bestmatch_video(), and FFmpeg_Transcoder::open_output().
video_stream_setup()
void FFmpeg_Base::video_stream_setup (AVCodecContext * output_codec_ctx, AVStream * output_stream, AVCodecContext * input_codec_ctx, AVRational framerate, AVPixelFormat enc_hw_pix_fmt) const protected
Set up video stream.
Parameters
[in] output_codec_ctx - Output codec context.
[in] output_stream - Output stream object.
[in] input_codec_ctx - Input codec context.
[in] framerate - Frame rate of input stream.
[in] enc_hw_pix_fmt - Forcibly set destination pixel format. Set to AV_PIX_FMT_NONE for automatic selection.
Definition at line 73 of file ffmpeg_base.cc.
References Logging::warning().
Referenced by FFmpeg_Transcoder::add_stream().
The documentation for this class was generated from the following files:
src/ffmpeg_base.h
src/ffmpeg_base.cc