FFmpegfs Fuse Multi Media Filesystem: Buffer Class Reference
Buffer Class Reference
The Buffer class.
#include <buffer.h>
Classes
struct _tagCACHEINFO
Structure to hold current cache state.
Public Types
typedef struct Buffer::_tagCACHEINFO CACHEINFO
Structure to hold current cache state.
typedef struct Buffer::_tagCACHEINFO * LPCACHEINFO
Pointer version of CACHEINFO.
typedef CACHEINFO const * LPCCACHEINFO
Pointer to const version of CACHEINFO.
Public Member Functions
Buffer ()
Create Buffer object.
virtual ~Buffer ()
Free Buffer object.
virtual VIRTUALTYPE type () const
Get type of this virtual file.
bool init (bool erase_cache)
Initialise cache.
bool set_segment (uint32_t segment_no)
Set the current segment.
uint32_t segment_count ()
Get segment count.
uint32_t current_segment_no ()
Get currently selected segment.
bool segment_exists (uint32_t segment_no)
Check if segment exists. Returns true if it exists, or false if it still has to be decoded.
bool release (int flags=CACHE_CLOSE_NOOPT)
Release cache buffer.
virtual size_t bufsize () const
Size of this buffer.
virtual int open (LPVIRTUALFILE virtualfile)
Open a virtual file.
virtual size_t read (void *data, size_t size)
Not implemented.
size_t read_frame (std::vector< uint8_t > *data, uint32_t frame_no)
Write image data for the frame number into the Buffer.
virtual int error () const
Get last error.
virtual int64_t duration () const
Get the duration of the file, in AV_TIME_BASE fractional seconds.
virtual size_t size () const
Get the value of the internal buffer size pointer.
virtual size_t size (uint32_t segment_no) const
Get the value of the internal buffer size pointer.
virtual size_t tell () const
Get the value of the internal read position pointer.
virtual size_t tell (uint32_t segment_no) const
Get the value of the internal read position pointer.
virtual int seek (int64_t offset, int whence)
Seek to position in file.
virtual int seek (int64_t offset, int whence, uint32_t segment_no)
Seek to position in file.
virtual bool eof () const
Check if at end of file.
virtual bool eof (uint32_t segment_no) const
Check if at end of file.
virtual void close ()
Close buffer.
size_t write (const uint8_t *data, size_t length)
Write data to the current position into the buffer. The position pointer will be updated.
size_t write_frame (const uint8_t *data, size_t length, uint32_t frame_no)
Write image data for the frame number into the buffer.
bool flush ()
Flush buffer to disk.
bool clear ()
Clear (delete) buffer.
bool reserve (size_t size)
Reserve memory without changing size to reduce re-allocations.
size_t buffer_watermark (uint32_t segment_no=0) const
Return the current watermark of the file while transcoding.
bool copy (std::vector< uint8_t > *out_data, size_t offset, uint32_t segment_no=0)
Copy buffered data into output buffer.
bool copy (uint8_t *out_data, size_t offset, size_t bufsize, uint32_t segment_no=0)
Copy buffered data into output buffer.
const std::string & cachefile (uint32_t segment_no) const
Get cache filename.
bool have_frame (uint32_t frame_no)
Check if we have the requested frame number. Works only when processing a frame set.
void finished_segment ()
Finish decoded segment.
bool is_segment_finished (uint32_t segment_no) const
Return true if transcoding segement finished.
bool open_file (uint32_t index, uint32_t flags)
Open cache file if not already open.
bool close_file (uint32_t index, uint32_t flags)
Close cache file if not already closed.
Public Member Functions inherited from FileIO
FileIO ()
Create FileIO object.
virtual ~FileIO ()
Free FileIO object.
LPVIRTUALFILE virtualfile ()
Get virtual file object.
const std::string & filename () const
Get source filename.
const std::string & path () const
Path to source file (without file name)
Static Public Member Functions
static const std::string & make_cachefile_name (std::string &cachefile, const std::string &filename, const std::string &fileext, bool is_idx)
Make up a cache file name including full path.
static bool remove_file (const std::string &filename)
Remove (unlink) file.
Static Public Member Functions inherited from FileIO
static FileIO * alloc (VIRTUALTYPE type)
Allocate the correct object for type().
Protected Member Functions
bool remove_cachefile (uint32_t segment_no=0)
Remove the cachefile.
bool is_open ()
Check if the cache file is open.
Protected Member Functions inherited from FileIO
void set_virtualfile (LPVIRTUALFILE virtualfile)
Set the virtual file object.
Private Member Functions
uint8_t * write_prepare (size_t length)
Prepare write operation.
void increment_pos (size_t increment)
Increment buffer position.
bool reallocate (size_t newsize)
Reallocate buffer to new size.
bool map_file (const std::string &filename, int *fd, uint8_t **p, size_t *filesize, bool *isdefaultsize, off_t defaultsize) const
Map memory to file.
bool unmap_file (const std::string &filename, int *fd, uint8_t **p, size_t *filesize) const
Unmap memory from file.
LPCACHEINFO cacheinfo (uint32_t segment_no)
cacheinfo
LPCCACHEINFO const_cacheinfo (uint32_t segment_no) const
cacheinfo
Private Attributes
std::recursive_mutex m_mutex
Access mutex.
LPCACHEINFO m_cur_ci
Convenience pointer to current write segment.
uint32_t m_cur_open
Number of open files.
std::vector< CACHEINFO > m_ci
Cache info.
Detailed Description
The Buffer class.
Definition at line 55 of file buffer.h.
Constructor & Destructor Documentation
~Buffer()
Buffer::~Buffer () virtual
Free Buffer object.
Release memory and close files
Definition at line 50 of file buffer.cc.
References release().
Member Function Documentation
buffer_watermark()
size_t Buffer::buffer_watermark (uint32_t segment_no = 0) const
Return the current watermark of the file while transcoding.
While transcoding, this value reflects the current size of the transcoded file. This is the maximum byte offset until the file can be read so far.
Parameters
[in] segment_no - If > 0 returns watermark for specific segment. If 0, returns watermark for current write segment.
Returns
Returns the current watermark.
Definition at line 826 of file buffer.cc.
References const_cacheinfo().
Referenced by FFmpeg_Transcoder::encode_finish(), Cache_Entry::size(), transcode_finish(), transcoder_buffer_watermark(), transcoder_thread(), and write_frame().
bufsize()
size_t Buffer::bufsize () const virtual
Size of this buffer.
Returns
Not applicable, returns 0.
Implements FileIO.
Definition at line 60 of file buffer.cc.
Referenced by copy().
cachefile()
const std::string & Buffer::cachefile (uint32_t segment_no) const
Get cache filename.
Parameters
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Returns cache filename.
Definition at line 899 of file buffer.cc.
References const_cacheinfo().
Referenced by init(), and make_cachefile_name().
cacheinfo()
Buffer::LPCACHEINFO Buffer::cacheinfo (uint32_t segment_no) private
cacheinfo
Parameters
[in] segment_no - HLS segment file number [1..n] or 0 for current segment or 0 for current segment.
Returns
Definition at line 1060 of file buffer.cc.
References m_ci, m_cur_ci, and segment_count().
Referenced by seek().
clear()
bool Buffer::clear ()
Clear (delete) buffer.
Returns
Returns true on success; false on error. Check errno for details.
Definition at line 558 of file buffer.cc.
References Logging::error(), Buffer::_tagCACHEINFO::m_buffer, Buffer::_tagCACHEINFO::m_buffer_idx, Buffer::_tagCACHEINFO::m_buffer_pos, Buffer::_tagCACHEINFO::m_buffer_size, Buffer::_tagCACHEINFO::m_buffer_size_idx, Buffer::_tagCACHEINFO::m_buffer_watermark, Buffer::_tagCACHEINFO::m_cachefile, m_cur_ci, Buffer::_tagCACHEINFO::m_fd, Buffer::_tagCACHEINFO::m_fd_idx, m_mutex, Buffer::_tagCACHEINFO::m_seg_finished, and segment_count().
Referenced by Cache_Entry::clear().
close_file()
bool Buffer::close_file (uint32_t index, uint32_t flags)
Close cache file if not already closed.
Parameters
[in] index - Index of segment file number [0..n-1].
[in] flags - CACHE_FLAG_* options
Returns
Returns true on success or file already closed; false on error.
Definition at line 126 of file buffer.cc.
References m_ci, m_cur_open, Logging::trace(), and unmap_file().
Referenced by ffmpegfs_release(), release(), and set_segment().
const_cacheinfo()
Buffer::LPCCACHEINFO Buffer::const_cacheinfo (uint32_t segment_no) const private
cacheinfo
Parameters
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Definition at line 1077 of file buffer.cc.
References m_ci, and m_cur_ci.
Referenced by buffer_watermark(), cachefile(), copy(), is_segment_finished(), size(), and tell().
copy() [1/2]
bool Buffer::copy (std::vector< uint8_t > * out_data, size_t offset, uint32_t segment_no = 0)
Copy buffered data into output buffer.
Parameters
[in] out_data - Buffer to copy data to.
[in] offset - Offset in buffer to copy data from.
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Returns true on success; false on error.
Definition at line 839 of file buffer.cc.
Referenced by read_frame().
copy() [2/2]
bool Buffer::copy (uint8_t * out_data, size_t offset, size_t bufsize, uint32_t segment_no = 0)
Copy buffered data into output buffer.
Parameters
[in] out_data - Buffer to copy data to.
[in] offset - Offset in buffer to copy data from.
[in] bufsize - Size of out_data buffer.
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Returns true on success; false on error.
Definition at line 844 of file buffer.cc.
References bufsize(), const_cacheinfo(), m_mutex, and size().
current_segment_no()
uint32_t Buffer::current_segment_no ()
Get currently selected segment.
Returns
Current segment number [1..n] or 0 if none selected.
Definition at line 318 of file buffer.cc.
References m_ci, m_cur_ci, m_mutex, and segment_count().
Referenced by set_segment().
duration()
int64_t Buffer::duration () const virtual
Get the duration of the file, in AV_TIME_BASE fractional seconds.
Returns
Not applicable to buffer, always returns AV_NOPTS_VALUE.
Implements FileIO.
Definition at line 803 of file buffer.cc.
eof() [1/2]
bool Buffer::eof () const virtual
Check if at end of file.
Returns
Returns true if at end of buffer.
Implements FileIO.
Definition at line 986 of file buffer.cc.
eof() [2/2]
bool Buffer::eof (uint32_t segment_no) const virtual
Check if at end of file.
Parameters
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Returns true if at end of buffer.
Definition at line 991 of file buffer.cc.
References size(), and tell().
error()
int Buffer::error () const virtual
Get last error.
Returns
errno value of last error.
Implements FileIO.
Definition at line 981 of file buffer.cc.
flush()
bool Buffer::flush ()
Flush buffer to disk.
Returns
Returns true on success; false on error. Check errno for details.
Definition at line 530 of file buffer.cc.
References Logging::error(), Buffer::_tagCACHEINFO::m_buffer, Buffer::_tagCACHEINFO::m_buffer_idx, Buffer::_tagCACHEINFO::m_buffer_size, Buffer::_tagCACHEINFO::m_buffer_size_idx, Buffer::_tagCACHEINFO::m_cachefile, Buffer::_tagCACHEINFO::m_cachefile_idx, m_cur_ci, m_mutex, and segment_count().
Referenced by finished_segment(), Cache_Entry::flush(), and release().
have_frame()
bool Buffer::have_frame (uint32_t frame_no)
Check if we have the requested frame number. Works only when processing a frame set.
Parameters
[in] frame_no - 1...frames
Returns
Returns true of frame is already in cache, false if not.
Definition at line 1001 of file buffer.cc.
References Buffer::_tagCACHEINFO::m_buffer_idx, m_cur_ci, m_mutex, and FileIO::virtualfile().
Referenced by FFmpeg_Transcoder::process_single_fr(), and FFmpeg_Transcoder::skip_decoded_frames().
increment_pos()
void Buffer::increment_pos (size_t increment) private
Increment buffer position.
Increment the location of the internal pointer. This cannot fail and so returns void. It does not ensure the position is valid memory because that is done by the write_prepare methods via reallocate.
Parameters
[in] increment - Increment size.
Definition at line 722 of file buffer.cc.
References Buffer::_tagCACHEINFO::m_buffer_pos, and m_cur_ci.
Referenced by write().
init()
bool Buffer::init (bool erase_cache)
Initialise cache.
Parameters
[in] erase_cache - if true delete old file before opening.
Returns
Returns true on success; false on error.
Definition at line 164 of file buffer.cc.
References cachefile(), FFMPEGFS_PARAMS::current_format(), Logging::error(), FileIO::filename(), VIRTUALFILE::get_segment_count(), is_open(), m_ci, m_cur_ci, m_mutex, make_cachefile_name(), make_filename(), map_file(), mktree(), new_strdup(), params, remove_cachefile(), segment_count(), FileIO::virtualfile(), VIRTUALFLAG_FRAME, and VIRTUALFLAG_HLS.
Referenced by Cache_Entry::open().
is_open()
bool Buffer::is_open () protected
Check if the cache file is open.
Returns
Returns true if the cache file is open; false if not.
Definition at line 1020 of file buffer.cc.
References m_ci, m_mutex, and segment_count().
Referenced by init(), and release().
is_segment_finished()
bool Buffer::is_segment_finished (uint32_t segment_no) const
Return true if transcoding segement finished.
Parameters
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Returns true if finished, false if not.
Definition at line 1047 of file buffer.cc.
References const_cacheinfo().
Referenced by transcode_until().
make_cachefile_name()
const std::string & Buffer::make_cachefile_name (std::string & cachefile, const std::string & filename, const std::string & fileext, bool is_idx) static
Make up a cache file name including full path.
Parameters
[out] cachefile - Name of cache file.
[in] filename - Source file name.
[in] fileext - File extension (MP4, WEBM etc.).
[in] is_idx - If true, create index file; otherwise create a cache.
Returns
Returns the name of the cache file.
Definition at line 913 of file buffer.cc.
References cachefile(), FileIO::filename(), FFMPEGFS_PARAMS::m_mountpath, params, and transcoder_cache_path().
Referenced by init(), and make_hls_fileset().
map_file()
bool Buffer::map_file (const std::string & filename, int * fd, uint8_t ** p, size_t * filesize, bool * isdefaultsize, off_t defaultsize) const private
Map memory to file.
Parameters
[in] filename - Name of cache file to open.
[out] fd - The file descriptor of the open cache file.
[out] p - Memory pointer to cache file.
[out] filesize - Actual size of the cache file after this call.
[in,out] isdefaultsize -
In: If false, the file size will be the size of the existing file, returning the size in filesize. If the file does not exist, it will be sized to defaultsize. If true, the defaultsize will be used in any case, resizing an existing file if necessary.
Out: true if the file size was set to default.
[out] defaultsize - Default size of the file if it does not exist. This parameter can be zero in which case the size will be set to the system's page size.
Returns
Returns true if successful and fd, p, filesize, isdefaultsize filled in or false on error.
Definition at line 340 of file buffer.cc.
References close(), Logging::error(), FileIO::filename(), open(), and Logging::trace().
Referenced by init(), and open_file().
open()
int Buffer::open (LPVIRTUALFILE virtualfile) virtual
Open a virtual file.
Parameters
[in] virtualfile - LPCVIRTUALFILE of file to open
Returns
Upon successful completion, open() returns 0. On error, an nonzero value is returned and errno is set to indicate the error.
Implements FileIO.
Definition at line 65 of file buffer.cc.
References FileIO::set_virtualfile(), and FileIO::virtualfile().
Referenced by Cache_Entry::Cache_Entry(), and map_file().
open_file()
bool Buffer::open_file (uint32_t index, uint32_t flags)
Open cache file if not already open.
Parameters
[in] index - Index of segment file number [0..n-1].
[in] flags - CACHE_FLAG_* options
Returns
Returns true on success or file already open; false on error.
Definition at line 78 of file buffer.cc.
References CACHE_FLAG_RW, Logging::debug(), m_ci, m_cur_open, map_file(), and Logging::trace().
Referenced by FFmpeg_Transcoder::open_output(), FFmpeg_Transcoder::open_output_frame_set(), set_segment(), transcoder_read(), and transcoder_read_frame().
read()
size_t Buffer::read (void * data, size_t size) virtual
Not implemented.
Parameters
[out] data - unused
[in] size - unused
Returns
Always returns 0 and errno is EPERM.
Implements FileIO.
Definition at line 947 of file buffer.cc.
read_frame()
size_t Buffer::read_frame (std::vector< uint8_t > * data, uint32_t frame_no)
Write image data for the frame number into the Buffer.
Parameters
[out] data - Buffer to read data in.
[in] frame_no - Number of the frame to write.
Returns
Upon successful completion, read() returns the number of bytes read.
This may be less than size.
On error, the value 0 is returned and errno is set to indicate the error.
If at end of file, 0 may be returned by errno not set. error() will return 0 if at EOF. If the image frame is not yet read, the function also returns 0 and errno is EAGAIN.
Definition at line 954 of file buffer.cc.
References copy(), Buffer::_tagCACHEINFO::m_buffer_idx, m_cur_ci, m_mutex, and FileIO::virtualfile().
Referenced by transcoder_read_frame().
reallocate()
bool Buffer::reallocate (size_t newsize) private
Reallocate buffer to new size.
Ensure the allocation has at least size bytes available. If not, reallocate memory to make more available. Fill the newly allocated memory with zeroes.
Parameters
[in] newsize - New buffer size
Returns
Returns true on success; false on error.
Definition at line 883 of file buffer.cc.
References FileIO::filename(), reserve(), size(), and Logging::trace().
Referenced by write_prepare().
release()
bool Buffer::release (int flags = CACHE_CLOSE_NOOPT)
Release cache buffer.
Parameters
[in] flags - One of the CACHE_CLOSE_* flags.
Returns
Returns true on success; false on error.
Definition at line 465 of file buffer.cc.
References CACHE_CHECK_BIT, CACHE_CLOSE_DELETE, CACHE_FLAG_RO, CACHE_FLAG_RW, close_file(), flush(), is_open(), m_ci, m_mutex, remove_cachefile(), segment_count(), and unmap_file().
Referenced by close(), Cache_Entry::close_buffer(), and ~Buffer().
remove_cachefile()
bool Buffer::remove_cachefile (uint32_t segment_no = 0) protected
Remove the cachefile.
Parameters
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Returns true on success; false on error.
Definition at line 515 of file buffer.cc.
References Buffer::_tagCACHEINFO::m_cachefile, Buffer::_tagCACHEINFO::m_cachefile_idx, m_ci, m_cur_ci, and remove_file().
Referenced by init(), and release().
remove_file()
bool Buffer::remove_file (const std::string & filename) static
Remove (unlink) file.
Parameters
[in] filename - Name of file to remove.
Returns
Returns true on success; false on error.
Definition at line 933 of file buffer.cc.
References FileIO::filename(), and Logging::warning().
Referenced by remove_cachefile().
reserve()
bool Buffer::reserve (size_t size)
Reserve memory without changing size to reduce re-allocations.
Parameters
[in] size - Size of buffer to reserve.
Returns
Returns true on success; false on error.
Definition at line 595 of file buffer.cc.
References Logging::error(), Buffer::_tagCACHEINFO::m_buffer, Buffer::_tagCACHEINFO::m_buffer_size, Buffer::_tagCACHEINFO::m_cachefile, m_cur_ci, Buffer::_tagCACHEINFO::m_fd, m_mutex, and size().
Referenced by FFmpeg_Transcoder::open_output(), FFmpeg_Transcoder::open_output_frame_set(), reallocate(), and transcode_finish().
seek() [1/2]
int Buffer::seek (int64_t offset, int whence) virtual
Seek to position in file.
Repositions the offset of the open file to the argument offset according to the directive whence. May block for a long time if buffer has not been filled to the requested offset.
Parameters
[in] offset - offset in bytes
[in] whence - how to seek:
SEEK_SET: The offset is set to offset bytes.
SEEK_CUR: The offset is set to its current location plus offset bytes.
SEEK_END: The offset is set to the size of the file plus offset bytes.
Returns
Upon successful completion, seek() returns the resulting offset location as measured in bytes from the beginning of the file.
Implements FileIO.
Definition at line 727 of file buffer.cc.
Referenced by write_frame().
seek() [2/2]
int Buffer::seek (int64_t offset, int whence, uint32_t segment_no) virtual
Seek to position in file.
Repositions the offset of the open file to the argument offset according to the directive whence. May block for a long time if buffer has not been filled to the requested offset.
Parameters
[in] offset - offset in bytes
[in] whence - how to seek:
SEEK_SET: The offset is set to offset bytes.
SEEK_CUR: The offset is set to its current location plus offset bytes.
SEEK_END: The offset is set to the size of the file plus offset bytes.
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Upon successful completion, seek() returns the resulting offset location as measured in bytes from the beginning of the file.
Definition at line 732 of file buffer.cc.
References cacheinfo(), Buffer::_tagCACHEINFO::m_buffer, Buffer::_tagCACHEINFO::m_buffer_pos, size(), and tell().
segment_count()
uint32_t Buffer::segment_count ()
Get segment count.
Returns
Number of segments.
Definition at line 311 of file buffer.cc.
References m_ci, and m_mutex.
Referenced by cacheinfo(), clear(), current_segment_no(), flush(), init(), is_open(), release(), segment_exists(), and set_segment().
segment_exists()
bool Buffer::segment_exists (uint32_t segment_no)
Check if segment exists. Returns true if it exists, or false if it still has to be decoded.
Parameters
[in] segment_no - HLS segment file number [1..n].
Returns
Returns true if it exists, or false if not.
Definition at line 329 of file buffer.cc.
References file_exists(), m_ci, m_cur_ci, m_mutex, and segment_count().
Referenced by FFmpeg_Transcoder::process_single_fr(), and transcoder_read().
set_segment()
bool Buffer::set_segment (uint32_t segment_no)
Set the current segment.
Parameters
[in] segment_no - HLS segment file number [1..n].
Returns
Returns true on success; if segment_no is 0 or greated then segment_count() returns false and sets errno to EINVALID.
Definition at line 286 of file buffer.cc.
References CACHE_FLAG_RW, close_file(), current_segment_no(), m_ci, m_cur_ci, m_mutex, open_file(), and segment_count().
Referenced by FFmpeg_Transcoder::process_single_fr().
size() [1/2]
size_t Buffer::size () const virtual
Get the value of the internal buffer size pointer.
Returns
Returns the value of the internal buffer size pointer.
Implements FileIO.
Definition at line 808 of file buffer.cc.
Referenced by copy(), eof(), FFmpeg_Transcoder::open_output(), FFmpeg_Transcoder::open_output_frame_set(), reallocate(), reserve(), seek(), and transcode_until().
size() [2/2]
size_t Buffer::size (uint32_t segment_no) const virtual
Get the value of the internal buffer size pointer.
Parameters
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Returns the value of the internal buffer size pointer.
Definition at line 813 of file buffer.cc.
References const_cacheinfo().
tell() [1/2]
size_t Buffer::tell () const virtual
Get the value of the internal read position pointer.
Returns
Returns the value of the internal read position pointer.
Implements FileIO.
Definition at line 784 of file buffer.cc.
Referenced by eof(), FFmpeg_Transcoder::process_single_fr(), seek(), transcode_until(), and transcoder_buffer_tell().
tell() [2/2]
size_t Buffer::tell (uint32_t segment_no) const virtual
Get the value of the internal read position pointer.
Parameters
[in] segment_no - HLS segment file number [1..n] or 0 for current segment.
Returns
Returns the value of the internal read position pointer.
Definition at line 789 of file buffer.cc.
References const_cacheinfo().
type()
VIRTUALTYPE Buffer::type () const virtual
Get type of this virtual file.
Returns
Returns VIRTUALTYPE_BUFFER.
Implements FileIO.
Definition at line 55 of file buffer.cc.
References VIRTUALTYPE_BUFFER.
unmap_file()
bool Buffer::unmap_file (const std::string & filename, int * fd, uint8_t ** p, size_t * filesize) const private
Unmap memory from file.
Parameters
[in] filename - Name of cache file to unmap.
[in] fd - The file descriptor of the open cache file.
[in] p - Memory pointer to cache file.
[in] filesize - Actual size of the cache file.
Returns
Returns true on success; false on error.
Definition at line 415 of file buffer.cc.
References close(), Logging::error(), FileIO::filename(), and Logging::trace().
Referenced by close_file(), and release().
write()
size_t Buffer::write (const uint8_t * data, size_t length)
Write data to the current position into the buffer. The position pointer will be updated.
Parameters
[in] data - Buffer with data to write.
[in] length - Length of buffer to write.
Returns
Returns the bytes written to the buffer. If less than length this indicates an error, consult errno for details.
Definition at line 627 of file buffer.cc.
References increment_pos(), Buffer::_tagCACHEINFO::m_buffer, m_cur_ci, m_mutex, and write_prepare().
Referenced by FFmpeg_Transcoder::output_write(), and write_frame().
write_frame()
size_t Buffer::write_frame (const uint8_t * data, size_t length, uint32_t frame_no)
Write image data for the frame number into the buffer.
Parameters
[in] data - Buffer with data to write.
[in] length - Length of buffer to write.
[in] frame_no - Number of the frame to write.
Returns
Returns the bytes written to the buffer. If less than length this indicates an error, consult errno for details.
Definition at line 651 of file buffer.cc.
References buffer_watermark(), IMAGE_FRAME_TAG, Buffer::_tagCACHEINFO::m_buffer_idx, m_cur_ci, IMAGE_FRAME::m_frame_no, m_mutex, IMAGE_FRAME::m_offset, IMAGE_FRAME::m_size, IMAGE_FRAME::m_tag, seek(), FileIO::virtualfile(), and write().
Referenced by FFmpeg_Transcoder::encode_image_frame().
write_prepare()
uint8_t * Buffer::write_prepare (size_t length) private
Prepare write operation.
Ensure the Buffer has sufficient space for a quantity of data and return a pointer where the data may be written. The position pointer should be updated afterward with increment_pos().
Parameters
[in] length - Length of buffer to prepare.
Returns
Returns a pointer to the memory to write.
Definition at line 705 of file buffer.cc.
References Buffer::_tagCACHEINFO::m_buffer, Buffer::_tagCACHEINFO::m_buffer_pos, Buffer::_tagCACHEINFO::m_buffer_watermark, m_cur_ci, and reallocate().
Referenced by write().
The documentation for this class was generated from the following files:
src/buffer.h
src/buffer.cc