FFmpegfs Fuse Multi Media Filesystem: FFmpeg_Transcoder::StreamRef Class Reference
FFmpeg_Transcoder::StreamRef Class Reference
In/output stream reference data.
#include <ffmpeg_transcoder.h>
Public Member Functions
void set_codec_ctx (AVCodecContext *codec_ctx)
Set the AVCodecContext pointer. Will be shared and deleted after the last consumer freed it.
void close ()
Close (reset) AVCodecContext pointer.
Public Attributes
std::shared_ptr< AVCodecContext > m_codec_ctx
AVCodecContext for this encoder stream.
AVStream * m_stream
AVStream for this encoder stream.
int m_stream_idx
Stream index in AVFormatContext.
int64_t m_start_time
Start time of the stream in stream time base units, may be 0.
Detailed Description
In/output stream reference data.
<
Definition at line 102 of file ffmpeg_transcoder.h.
Member Function Documentation
set_codec_ctx()
void FFmpeg_Transcoder::StreamRef::set_codec_ctx (AVCodecContext * codec_ctx)
Set the AVCodecContext pointer. Will be shared and deleted after the last consumer freed it.
Parameters
[in] codec_ctx - AVCodecContext pointer to store
Definition at line 211 of file ffmpeg_transcoder.cc.
Referenced by FFmpeg_Transcoder::add_albumart_stream(), FFmpeg_Transcoder::add_external_subtitle_stream(), FFmpeg_Transcoder::add_stream(), FFmpeg_Transcoder::add_stream_copy(), FFmpeg_Transcoder::add_subtitle_stream(), FFmpeg_Transcoder::open_albumarts(), FFmpeg_Transcoder::open_bestmatch_audio(), FFmpeg_Transcoder::open_bestmatch_video(), FFmpeg_Transcoder::open_output_frame_set(), and FFmpeg_Transcoder::open_subtitles().
The documentation for this class was generated from the following files:
src/ffmpeg_transcoder.h
src/ffmpeg_transcoder.cc