FFmpegfs Fuse Multi Media Filesystem: src/cuesheetparser.h File Reference
cuesheetparser.h File Reference
Clue sheet parser.
#include <string>
Macros
#define TRACKDIR "tracks"
Functions
int check_cuesheet (const std::string &filename, void *buf=nullptr, fuse_fill_dir_t filler=nullptr)
Get number of titles in cue sheet.
Detailed Description
Clue sheet parser.
Author
Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Copyright
Copyright (C) 2018-2022 Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Definition in file cuesheetparser.h.
Macro Definition Documentation
TRACKDIR
#define TRACKDIR "tracks"
Extension of virtual tracks directory
Definition at line 39 of file cuesheetparser.h.
Function Documentation
check_cuesheet()
int check_cuesheet (const std::string & filename, void * buf = nullptr, fuse_fill_dir_t filler = nullptr)
Get number of titles in cue sheet.
Parameters
[in] filename - Path to check
[in,out] buf - The buffer passed to the readdir() operation.
[in,out] filler - Function to add an entry in a readdir() operation (see https://libfuse.github.io/doxygen/fuse_8h.html#a7dd132de66a5cc2add2a4eff5d435660)
Note
buf and filler can be nullptr. In that case the call will run faster, so these parameters should only be passed if to be filled in.
Returns
-errno or number or titles in cue sheet
Definition at line 368 of file cuesheetparser.cc.
References append_ext(), append_sep(), check_path(), Logging::error(), find_file(), find_file_from_orig(), parse_cuesheet_file(), parse_cuesheet_text(), remove_path(), replace_ext(), Logging::trace(), and TRACKDIR.
Referenced by ffmpegfs_getattr(), and ffmpegfs_readdir().