FFmpegfs Fuse Multi Media Filesystem: src/dvdparser.h File Reference
dvdparser.h File Reference
DVD parser.
#include <string>
Functions
int check_dvd (const std::string &path, void *buf=nullptr, fuse_fill_dir_t filler=nullptr)
Get number of titles on DVD.
Detailed Description
DVD parser.
This is only available if built with -DUSE_LIBDVD parameter.
Author
Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Copyright
Copyright (C) 2018-2022 Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Definition in file dvdparser.h.
Function Documentation
check_dvd()
int check_dvd (const std::string & path, void * buf = nullptr, fuse_fill_dir_t filler = nullptr)
Get number of titles on DVD.
Parameters
[in] path - Path to check
[in,out] buf - The buffer passed to the readdir() operation.
[in,out] filler - Function to add an entry in a readdir() operation (see0
Returns
-errno or number or titles on DVD
Definition at line 553 of file dvdparser.cc.
References add_dotdot(), append_sep(), check_path(), load_path(), parse_dvd(), and Logging::trace().
Referenced by ffmpegfs_getattr(), and ffmpegfs_readdir().