FFmpegfs Fuse Multi Media Filesystem: src/ffmpeg_utils.h File Reference
ffmpeg_utils.h File Reference
Various FFmpegfs utility functions.
#include "ffmpeg_compat.h"
#include <string>
#include <vector>
#include <regex>
#include <linux/limits.h>
#include <libavformat/avformat.h>
Classes
struct Format_Options
struct Format_Options::_tagFORMAT
class FFmpegfs_Format
The FFmpegfs_Format class.
struct comp
The comp struct to make std::string find operations case insensitive.
Macros
#define FFMPEFS_VERSION PACKAGE_VERSION
FFmpegfs version number.
#define __STDC_FORMAT_MACROS
Force PRId64 defines.
#define LAVR_DEPRECATE 0
Prefer libavresample (for Libav libswresample is not available)
#define HAVE_AV_FORMAT_INJECT_GLOBAL_SIDE_DATA (LIBAVFORMAT_VERSION_MICRO >= 100 && LIBAVFORMAT_VERSION_INT >= AV_VERSION_INT(57, 64, 101))
#define HAVE_MEDIA_TYPE_STRING (LIBAVUTIL_VERSION_MICRO >= 100 && LIBAVUTIL_VERSION_INT >= AV_VERSION_INT(55, 34, 101))
#define HAVE_VULKAN_HWACCEL (LIBAVUTIL_VERSION_MICRO >= 100 && LIBAVUTIL_VERSION_INT >= AV_VERSION_INT(56, 39, 100))
#define AV_ROUND_PASS_MINMAX 0
#define AV_CODEC_FLAG_GLOBAL_HEADER CODEC_FLAG_GLOBAL_HEADER
AV_CODEC_FLAG_GLOBAL_HEADER is missing in older FFmpeg versions.
#define FF_INPUT_BUFFER_PADDING_SIZE 256
FF_INPUT_BUFFER_PADDING_SIZE is missing in newer FFmpeg versions.
#define AV_CODEC_CAP_VARIABLE_FRAME_SIZE CODEC_CAP_VARIABLE_FRAME_SIZE
AV_CODEC_CAP_VARIABLE_FRAME_SIZE is missing in older FFmpeg versions.
#define BITRATE int
For FFmpeg bit rate is an int.
#define CODECPAR(s) ((s)->codecpar)
Map to codecpar.
#define STRINGIFY(x) #x
Stringification helper for STRINGIFY. Not to be used separately.
#define TOSTRING(x) STRINGIFY(x)
Convert a macro argument into a string constant.
Typedefs
typedef enum FILETYPE FILETYPE
typedef enum PROFILE PROFILE
typedef enum PRORESLEVEL PRORESLEVEL
typedef enum AUTOCOPY AUTOCOPY
typedef enum RECODESAME RECODESAME
typedef enum SAMPLE_FMT SAMPLE_FMT
typedef enum ENCODING ENCODING
Enumerations
enum FILETYPE {
FILETYPE_UNKNOWN , FILETYPE_MP3 , FILETYPE_MP4 , FILETYPE_WAV ,
FILETYPE_OGG , FILETYPE_WEBM , FILETYPE_MOV , FILETYPE_AIFF ,
FILETYPE_OPUS , FILETYPE_PRORES , FILETYPE_ALAC , FILETYPE_PNG ,
FILETYPE_JPG , FILETYPE_BMP , FILETYPE_TS , FILETYPE_HLS ,
FILETYPE_FLAC , FILETYPE_MKV
}
enum PROFILE {
PROFILE_INVALID = -1 , PROFILE_DEFAULT = 0 , PROFILE_MP4_FF = 1 , PROFILE_MP4_EDGE ,
PROFILE_MP4_IE , PROFILE_MP4_CHROME , PROFILE_MP4_SAFARI , PROFILE_MP4_OPERA ,
PROFILE_MP4_MAXTHON , PROFILE_HLS_DEFAULT = PROFILE_DEFAULT , PROFILE_MOV_DEFAULT = PROFILE_DEFAULT , PROFILE_PRORES_DEFAULT = PROFILE_DEFAULT ,
PROFILE_ALAC_DEFAULT = PROFILE_DEFAULT , PROFILE_WEBM_DEFAULT = PROFILE_DEFAULT
}
enum PRORESLEVEL {
PRORESLEVEL_NONE = -1 , PRORESLEVEL_PRORES_PROXY = 0 , PRORESLEVEL_PRORES_LT , PRORESLEVEL_PRORES_STANDARD ,
PRORESLEVEL_PRORES_HQ
}
enum AUTOCOPY {
AUTOCOPY_OFF = 0 , AUTOCOPY_MATCH , AUTOCOPY_MATCHLIMIT , AUTOCOPY_STRICT ,
AUTOCOPY_STRICTLIMIT
}
enum RECODESAME { RECODESAME_NO = 0 , RECODESAME_YES }
enum SAMPLE_FMT {
SAMPLE_FMT_DONTCARE = -1 , SAMPLE_FMT_8 , SAMPLE_FMT_16 , SAMPLE_FMT_24 ,
SAMPLE_FMT_32 , SAMPLE_FMT_64 , SAMPLE_FMT_F16 , SAMPLE_FMT_F24 ,
SAMPLE_FMT_F32 , SAMPLE_FMT_F64
}
enum ENCODING {
ENCODING_ASCII = -1 , ENCODING_UTF8_BOM = -2 , ENCODING_UTF16LE_BOM = -3 , ENCODING_UTF16BE_BOM = -4 ,
ENCODING_UTF32LE_BOM = -5 , ENCODING_UTF32BE_BOM = -6
}
Functions
const char * get_media_type_string (enum AVMediaType media_type)
av_get_media_type_string is missing, so we provide our own.
const std::string & append_sep (std::string *path)
Add / to the path if required.
const std::string & append_filename (std::string *path, const std::string &filename)
Add filename to path, including / after the path if required.
const std::string & remove_sep (std::string *path)
Remove / from the path.
const std::string & remove_filename (std::string *filepath)
Remove filename from path. Handy dirname alternative.
const std::string & remove_path (std::string *filepath)
Remove path from filename. Handy basename alternative.
const std::string & remove_ext (std::string *filepath)
Remove extension from filename.
bool allow_list_ext (const std::string &ext, const std::string &allowlist)
Find extension in allowlist, if existing.
bool find_ext (std::string *ext, const std::string &filename)
Find extension in filename, if existing.
const std::string & replace_ext (std::string *filepath, const std::string &ext)
Replace extension in filename, taking into account that there might not be an extension already.
const std::string & append_ext (std::string *filepath, const std::string &ext)
Append extension to filename. If ext is the same as.
char * new_strdup (const std::string &str)
strdup() variant taking a std::string as input.
std::string ffmpeg_geterror (int errnum)
Get FFmpeg error string for errnum. Internally calls av_strerror().
int64_t ffmpeg_rescale (int64_t ts, const AVRational &time_base)
Convert a FFmpeg time from time_base into standard AV_TIME_BASE fractional seconds.
std::string format_number (int64_t value)
Format numeric value.
std::string format_bitrate (BITRATE value)
Format a bit rate.
std::string format_samplerate (int value)
Format a samplerate.
std::string format_duration (int64_t value, uint32_t fracs=3)
Format a time in format HH:MM:SS.fract.
std::string format_time (time_t value)
Format a time in format "w d m s".
std::string format_size (uint64_t value)
Format size.
std::string format_size_ex (uint64_t value)
Format size.
std::string format_result_size (size_t size_resulting, size_t size_predicted)
Format size of transcoded file including difference between predicted and resulting size.
std::string format_result_size_ex (size_t size_resulting, size_t size_predicted)
Format size of transcoded file including difference between predicted and resulting size.
void exepath (std::string *path)
Path to FFmpegfs binary.
std::string & ltrim (std::string &s)
trim from start
std::string & rtrim (std::string &s)
trim from end
std::string & trim (std::string &s)
trim from both ends
std::string replace_all (std::string str, const std::string &from, const std::string &to)
Same as std::string replace(), but replaces all occurrences.
template<typename ... Args>
std::string string_format (const std::string &format, Args ... args)
Format a std::string sprintf-like.
int strcasecmp (const std::string &s1, const std::string &s2)
strcasecmp() equivalent for std::string.
void make_upper (std::string *input)
Convert string to upper case.
void make_lower (std::string *input)
Convert string to lower case.
std::string ffmpeg_libinfo ()
Get info about the FFmpeg libraries used.
int show_caps (int device_only)
Lists all supported codecs and devices.
const char * get_codec_name (AVCodecID codec_id, bool long_name)
Safe way to get the codec name. Function never fails, will return "unknown" on error.
int supports_albumart (FILETYPE filetype)
Check if file type supports album arts.
FILETYPE get_filetype (const std::string &desttype)
Get the FFmpegfs filetype, desttype must be one of FFmpeg's "official" short names for formats.
std::string get_filetype_text (FILETYPE filetype)
Convert FILETYPE enum to human readable text.
FILETYPE get_filetype_from_list (const std::string &desttypelist)
Get the FFmpegfs filetype, desttypelist must be a comma separated list of FFmpeg's "official" short names for formats. Will return the first match. Same as get_filetype, but accepts a comma separated list.
int print_stream_info (const AVStream *stream)
Print info about an AVStream.
std::string fourcc_make_string (std::string *buf, uint32_t fourcc)
int reg_compare (const std::string &value, const std::string &pattern, std::regex::flag_type flag=std::regex::ECMAScript)
Compare value with pattern.
const std::string & expand_path (std::string *tgt, const std::string &src)
Expand path, e.g., expand ~/ to home directory.
int is_mount (const std::string &path)
Check if path is a mount.
int mktree (const std::string &path, mode_t mode)
Make directory tree.
void tempdir (std::string &path)
Get temporary directory.
std::vector< std::string > split (const std::string &input, const std::string &regex)
Split string into an array delimited by a regular expression.
template<typename T , std::size_t N>
constexpr std::size_t countof (T const (&)[N]) noexcept
std::string sanitise_filepath (const std::string &filepath)
Sanitise file name. Calls realpath() to remove duplicate // or resolve ../.. etc.
std::string sanitise_filepath (std::string *filepath)
Sanitise file name. Calls realpath() to remove duplicate // or resolve ../.. etc. Changes the path in place.
bool is_album_art (AVCodecID codec_id, const AVRational *frame_rate=nullptr)
Minimal check if codec is an album art. Requires frame_rate to decide whether this is a video stream if codec_id is not BMP or PNG (which means its undoubtedly an album art). For MJPEG this may also be a video stream if the frame rate is high enough.
int nocasecompare (const std::string &lhs, const std::string &rhs)
nocasecompare to make std::string find operations case insensitive
size_t get_disk_free (std::string &path)
Get free disk space.
bool check_ignore (size_t size, size_t offset)
For use with win_smb_fix=1: Check if this an illegal access offset by Windows.
std::string make_filename (uint32_t file_no, const std::string &fileext)
Make a file name from file number and file extension.
bool file_exists (const std::string &filename)
Check if file exists.
const char * hwdevice_get_type_name (AVHWDeviceType dev_type)
int to_utf8 (std::string &text, const std::string &encoding)
Convert almost any encoding to UTF-8. To get a list of all possible encodings run "iconv --list".
int get_encoding (const char *str, std::string &encoding)
Try to detect the encoding of str. This is relatively realiable, but may be wrong.
int read_file (const std::string &path, std::string &result)
Read text file and return in UTF-8 format, no matter in which encoding the input file is. UTF-8/16/32 with BOM will always return a correct result. For all other encodings the function tries to detect it, that may fail.
void stat_set_size (struct stat *st, size_t size)
Properly fill in all size related members in stat struct.
bool detect_docker (void)
Detect if we are running under Docker.
template<typename T >
std::map< const std::string, const T, comp >::const_iterator search_by_value (const std::map< const std::string, const T, comp > &mapOfWords, T value)
Iterate through all elements in map and search for the passed element.
Detailed Description
Various FFmpegfs utility functions.
Author
Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Copyright
Copyright (C) 2017-2022 Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Definition in file ffmpeg_utils.h.
Macro Definition Documentation
AV_ROUND_PASS_MINMAX
#define AV_ROUND_PASS_MINMAX 0
Ignore if this is missing
Definition at line 133 of file ffmpeg_utils.h.
HAVE_AV_FORMAT_INJECT_GLOBAL_SIDE_DATA
#define HAVE_AV_FORMAT_INJECT_GLOBAL_SIDE_DATA (LIBAVFORMAT_VERSION_MICRO >= 100 && LIBAVFORMAT_VERSION_INT >= AV_VERSION_INT(57, 64, 101))
Allow use of av_format_inject_global_side_data when available
Definition at line 101 of file ffmpeg_utils.h.
HAVE_MEDIA_TYPE_STRING
#define HAVE_MEDIA_TYPE_STRING (LIBAVUTIL_VERSION_MICRO >= 100 && LIBAVUTIL_VERSION_INT >= AV_VERSION_INT(55, 34, 101))
Add av_get_media_type_string function if missing
Definition at line 106 of file ffmpeg_utils.h.
HAVE_VULKAN_HWACCEL
#define HAVE_VULKAN_HWACCEL (LIBAVUTIL_VERSION_MICRO >= 100 && LIBAVUTIL_VERSION_INT >= AV_VERSION_INT(56, 39, 100))
Min. FFmpeg version for VULKAN hardware acceleration support 2020-02-04 - xxxxxxxxxx - lavu 56.39.100 - hwcontext.h Add AV_PIX_FMT_VULKAN Add AV_HWDEVICE_TYPE_VULKAN and implementation.
Definition at line 127 of file ffmpeg_utils.h.
Typedef Documentation
AUTOCOPY
typedef enum AUTOCOPY AUTOCOPY
Auto copy options
ENCODING
typedef enum ENCODING ENCODING
Detected encoding types
FILETYPE
typedef enum FILETYPE FILETYPE
File types
PROFILE
typedef enum PROFILE PROFILE
MP4/MOV/ALAC profiles
PRORESLEVEL
typedef enum PRORESLEVEL PRORESLEVEL
Prores levels
RECODESAME
typedef enum RECODESAME RECODESAME
Recode to same format options
SAMPLE_FMT
typedef enum SAMPLE_FMT SAMPLE_FMT
List of sample formats. User selection, we don't care about planar or interleaved.
Enumeration Type Documentation
AUTOCOPY
enum AUTOCOPY
Auto copy options
Enumerator
AUTOCOPY_OFF
Never copy streams, transcode always.
AUTOCOPY_MATCH
Copy stream if target supports codec.
AUTOCOPY_MATCHLIMIT
Same as MATCH, only copy if target not larger transcode otherwise.
AUTOCOPY_STRICT
Copy stream if codec matches desired target, transcode otherwise.
AUTOCOPY_STRICTLIMIT
Same as STRICT, only copy if target not larger, transcode otherwise.
Definition at line 248 of file ffmpeg_utils.h.
ENCODING
enum ENCODING
Detected encoding types
Enumerator
ENCODING_ASCII
Some sort of ASCII encoding.
ENCODING_UTF8_BOM
UTF-8 with bottom mark.
ENCODING_UTF16LE_BOM
UTF-16 little-endian with bottom mark.
ENCODING_UTF16BE_BOM
UTF-16 big-endian with bottom mark.
ENCODING_UTF32LE_BOM
UTF-16 little-endian with bottom mark.
ENCODING_UTF32BE_BOM
UTF-16 big-endian with bottom mark.
Definition at line 924 of file ffmpeg_utils.h.
FILETYPE
enum FILETYPE
File types
Definition at line 179 of file ffmpeg_utils.h.
PROFILE
enum PROFILE
MP4/MOV/ALAC profiles
Enumerator
PROFILE_INVALID
Profile is invalid.
PROFILE_DEFAULT
No specific profile/Don't care.
PROFILE_MP4_FF
Firefox.
PROFILE_MP4_EDGE
MS Edge.
PROFILE_MP4_IE
MS Internet Explorer.
PROFILE_MP4_CHROME
Google Chrome.
PROFILE_MP4_SAFARI
Apple Safari.
PROFILE_MP4_OPERA
Opera.
PROFILE_MP4_MAXTHON
Maxthon.
PROFILE_HLS_DEFAULT
HLS/ts uses no profile.
PROFILE_MOV_DEFAULT
MOV uses no profile.
PROFILE_PRORES_DEFAULT
MOV/ProRes uses no profile.
PROFILE_ALAC_DEFAULT
MOV/ALAC uses no profile.
PROFILE_WEBM_DEFAULT
WebM uses no profile.
Definition at line 204 of file ffmpeg_utils.h.
PRORESLEVEL
enum PRORESLEVEL
Prores levels
Enumerator
PRORESLEVEL_NONE
No level.
PRORESLEVEL_PRORES_PROXY
Prores Level: PROXY.
PRORESLEVEL_PRORES_LT
Prores Level: LT.
PRORESLEVEL_PRORES_STANDARD
Prores Level: STANDARD.
PRORESLEVEL_PRORES_HQ
Prores Level: HQ.
Definition at line 235 of file ffmpeg_utils.h.
RECODESAME
enum RECODESAME
Recode to same format options
Enumerator
RECODESAME_NO
Never recode to same format.
RECODESAME_YES
Always recode to same format.
Definition at line 260 of file ffmpeg_utils.h.
SAMPLE_FMT
enum SAMPLE_FMT
List of sample formats. User selection, we don't care about planar or interleaved.
Enumerator
SAMPLE_FMT_DONTCARE
Don't care, leave to FFmpegfs to choose.
SAMPLE_FMT_8
8 bit integer
SAMPLE_FMT_16
16 bit integer
SAMPLE_FMT_24
24 bit integer
SAMPLE_FMT_32
32 bit integer
SAMPLE_FMT_64
64 bit integer
SAMPLE_FMT_F16
16 bit floating point
SAMPLE_FMT_F24
24 bit floating point
SAMPLE_FMT_F32
32 bit floating point
SAMPLE_FMT_F64
64 bit floating point
Definition at line 270 of file ffmpeg_utils.h.
Function Documentation
allow_list_ext()
bool allow_list_ext (const std::string & ext, const std::string & allowlist)
Find extension in allowlist, if existing.
Parameters
[in] ext - Extension, if found.
[in] allowlist - Allow list to inspect.
Returns
Returns true if extension was found, false if there was none
Definition at line 974 of file ffmpeg_utils.cc.
References split(), and strcasecmp().
Referenced by transcoded_name().
append_ext()
const std::string& append_ext (std::string * filepath, const std::string & ext)
Append extension to filename. If ext is the same as.
Parameters
[in] filepath - Filename to add extension to.
[in] ext - Extension to add.
Returns
Returns constant reference to filename.
Definition at line 1030 of file ffmpeg_utils.cc.
References strcasecmp().
Referenced by check_cuesheet(), parse_cuesheet(), and transcoded_name().
append_filename()
const std::string& append_filename (std::string * path, const std::string & filename)
Add filename to path, including / after the path if required.
Parameters
[in] path - Path to add filename to.
[in] filename - File name to add.
Returns
Returns constant reference to path.
Definition at line 910 of file ffmpeg_utils.cc.
References append_sep().
Referenced by find_original(), and Cache::load_index().
append_sep()
const std::string& append_sep (std::string * path)
Add / to the path if required.
Parameters
[in] path - Path to add separator to.
Returns
Returns constant reference to path.
Definition at line 900 of file ffmpeg_utils.cc.
Referenced by append_filename(), check_bluray(), check_cuesheet(), check_dvd(), check_vcd(), ffmpegfs_getattr(), ffmpegfs_opt_proc(), ffmpegfs_readdir(), VCDUTILS::get_directory(), insert_dir(), main(), parse_cuesheet(), remove_filename(), and transcoder_cache_path().
check_ignore()
bool check_ignore (size_t size, size_t offset)
For use with win_smb_fix=1: Check if this an illegal access offset by Windows.
Parameters
[in] size - sizeof of the file
[in] offset - offset at which file is accessed
Returns
If request should be ignored, returns true; otherwise false
Definition at line 1943 of file ffmpeg_utils.cc.
countof()
template<typename T , std::size_t N> constexpr std::size_t countof (T const(&)[N]) constexpr noexcept
Safe countof() implementation: Retuns number of elements in an array.
Definition at line 827 of file ffmpeg_utils.h.
detect_docker()
bool detect_docker (void)
Detect if we are running under Docker.
Returns
Returns true, if running under Docker, or false if not.
Definition at line 2290 of file ffmpeg_utils.cc.
Referenced by main().
exepath()
void exepath (std::string * path)
Path to FFmpegfs binary.
Parameters
[in] path - Path to FFmpegfs binary.
Definition at line 1694 of file ffmpeg_utils.cc.
Referenced by prepare_script().
expand_path()
const std::string& expand_path (std::string * tgt, const std::string & src)
Expand path, e.g., expand ~/ to home directory.
Parameters
[out] tgt - Expanded source path.
[in] src - Path to expand.
Returns
Omn success, returns expanded source path.
Definition at line 1773 of file ffmpeg_utils.cc.
Referenced by ffmpegfs_opt_proc(), main(), and transcoder_cache_path().
ffmpeg_geterror()
std::string ffmpeg_geterror (int errnum)
Get FFmpeg error string for errnum. Internally calls av_strerror().
Parameters
[in] errnum - FFmpeg error code.
Returns
Returns std::string with the error defined by errnum.
Definition at line 1060 of file ffmpeg_utils.cc.
References AV_ERROR_MAX_STRING_SIZE.
Referenced by FFmpeg_Transcoder::add_albumart_frame(), FFmpeg_Transcoder::add_albumart_stream(), FFmpeg_Transcoder::add_samples_to_fifo(), FFmpeg_Transcoder::add_stream(), FFmpeg_Transcoder::add_stream_copy(), FFmpeg_Transcoder::alloc_picture(), FFmpeg_Transcoder::convert_samples(), FFmpeg_Transcoder::create_audio_frame(), FFmpeg_Transcoder::decode(), FFmpeg_Transcoder::decode_audio_frame(), FFmpeg_Transcoder::decode_frame(), FFmpeg_Transcoder::decode_video_frame(), FFmpeg_Base::dict_set_with_check(), FFmpeg_Transcoder::encode_audio_frame(), FFmpeg_Transcoder::encode_image_frame(), FFmpeg_Transcoder::encode_video_frame(), ffmpegfs_readdir(), FFmpeg_Transcoder::flush_delayed_audio(), FFmpeg_Transcoder::flush_delayed_video(), FFmpeg_Transcoder::hwdevice_ctx_add_ref(), FFmpeg_Transcoder::hwdevice_ctx_create(), FFmpeg_Transcoder::hwframe_copy_from_hw(), FFmpeg_Transcoder::hwframe_copy_to_hw(), FFmpeg_Transcoder::hwframe_ctx_set(), FFmpeg_Transcoder::init_audio_output_frame(), FFmpeg_Transcoder::init_converted_samples(), FFmpeg_Transcoder::init_deinterlace_filters(), FFmpeg_Transcoder::init_resampler(), FFmpeg_Transcoder::open_bestmatch_decoder(), FFmpeg_Transcoder::open_input_file(), FFmpeg_Base::opt_set_with_check(), parse_embedded_cuesheet(), FFmpeg_Transcoder::process_single_fr(), FFmpeg_Transcoder::read_decode_convert_and_store(), FFmpeg_Transcoder::send_filters(), FFmpeg_Transcoder::skip_decoded_frames(), FFmpeg_Transcoder::store_packet(), FFmpeg_Transcoder::write_output_file_header(), and FFmpeg_Transcoder::write_output_file_trailer().
ffmpeg_libinfo()
std::string ffmpeg_libinfo ()
Get info about the FFmpeg libraries used.
Returns
std::tring with info about the linked FFmpeg libraries.
Definition at line 1144 of file ffmpeg_utils.cc.
ffmpeg_rescale()
int64_t ffmpeg_rescale (int64_t ts, const AVRational & time_base)
Convert a FFmpeg time from time_base into standard AV_TIME_BASE fractional seconds.
Avoids conversion of AV_NOPTS_VALUE.
Parameters
[in] ts - Source time.
[in] time_base - Time base of source.
Returns
Returns converted value, or AV_NOPTS_VALUE if ts is AV_NOPTS_VALUE.
Definition at line 1074 of file ffmpeg_utils.cc.
References AV_ROUND_PASS_MINMAX.
file_exists()
bool file_exists (const std::string & filename)
Check if file exists.
Parameters
[in] filename - File to check.
Returns
Returns true if file exists, false if not.
Definition at line 1971 of file ffmpeg_utils.cc.
Referenced by Buffer::segment_exists().
find_ext()
bool find_ext (std::string * ext, const std::string & filename)
Find extension in filename, if existing.
Parameters
[in] ext - Extension, if found.
[in] filename - Filename to inspect.
Returns
Returns true if extension was found, false if there was none
Definition at line 988 of file ffmpeg_utils.cc.
Referenced by check_cuesheet(), ffmpegfs_readdir(), find_original(), and transcoded_name().
format_bitrate()
std::string format_bitrate (BITRATE value)
Format a bit rate.
Parameters
[in] value - Bit rate to format.
Returns
Returns std::string with formatted value in bit/s, kbit/s or Mbit/s. If value == AV_NOPTS_VALUE returns "unset".
Definition at line 1424 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Transcoder::add_stream(), FFmpeg_Base::audio_info(), create_bluray_virtualfile(), create_dvd_virtualfile(), and FFmpeg_Base::video_info().
format_duration()
std::string format_duration (int64_t value, uint32_t fracs = 3)
Format a time in format HH:MM:SS.fract.
Parameters
[in] value - Time value in AV_TIME_BASE factional seconds.
[in] fracs - Fractional digits.
Returns
Returns std::string with formatted value. If value == AV_NOPTS_VALUE returns "unset".
Definition at line 1465 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Base::audio_info(), create_bluray_virtualfile(), create_cuesheet_virtualfile(), create_dvd_virtualfile(), create_vcd_virtualfile(), FFmpeg_Transcoder::decode_frame(), FFmpeg_Transcoder::decode_video_frame(), FFmpeg_Transcoder::store_packet(), and FFmpeg_Base::video_info().
format_number()
std::string format_number (int64_t value)
Format numeric value.
Parameters
[in] value - Value to format.
Returns
Returns std::string with formatted value; if value == AV_NOPTS_VALUE returns "unset"; "unlimited" if value == 0.
Definition at line 1409 of file ffmpeg_utils.cc.
format_result_size()
std::string format_result_size (size_t size_resulting, size_t size_predicted)
Format size of transcoded file including difference between predicted and resulting size.
Parameters
[in] size_resulting - Resulting size.
[in] size_predicted - Predicted size.
Returns
Returns std::string with formatted value in bytes plus difference; if value == AV_NOPTS_VALUE returns "unset"; "unlimited" if value == 0.
Definition at line 1582 of file ffmpeg_utils.cc.
References format_size().
format_result_size_ex()
std::string format_result_size_ex (size_t size_resulting, size_t size_predicted)
Format size of transcoded file including difference between predicted and resulting size.
Parameters
[in] size_resulting - Resulting size.
[in] size_predicted - Predicted size.
Returns
Returns std::string with formatted value in bytes plus KB, MB or TB and difference; if value == AV_NOPTS_VALUE returns "unset"; "unlimited" if value == 0.
Definition at line 1596 of file ffmpeg_utils.cc.
References format_size(), and string_format().
Referenced by transcode_finish().
format_samplerate()
std::string format_samplerate (int value)
Format a samplerate.
Parameters
[in] value - Sample rate to format.
Returns
Returns std::string with formatted value in Hz or kHz. If value == AV_NOPTS_VALUE returns "unset".
Definition at line 1445 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Transcoder::add_stream(), FFmpeg_Base::audio_info(), create_bluray_virtualfile(), and FFmpeg_Transcoder::init_resampler().
format_size()
std::string format_size (uint64_t value)
Format size.
Parameters
[in] value - Size to format.
Returns
Returns std::string with formatted value in bytes, KB, MB or TB; if value == AV_NOPTS_VALUE returns "unset"; "unlimited" if value == 0.
Definition at line 1543 of file ffmpeg_utils.cc.
Referenced by create_bluray_virtualfile(), create_dvd_virtualfile(), format_result_size(), and format_result_size_ex().
format_size_ex()
std::string format_size_ex (uint64_t value)
Format size.
Parameters
[in] value - Size to format.
Returns
Returns std::string with formatted value in bytes plus KB, MB or TB; if value == AV_NOPTS_VALUE returns "unset"; "unlimited" if value == 0.
Definition at line 1577 of file ffmpeg_utils.cc.
Referenced by transcode_finish(), transcode_until(), transcoder_predict_filesize(), and transcoder_set_filesize().
format_time()
std::string format_time (time_t value)
Format a time in format "w d m s".
Parameters
[in] value - Time value in AV_TIME_BASE factional seconds.
Returns
Returns std::string with formatted value. If value == AV_NOPTS_VALUE returns "unset".
Definition at line 1491 of file ffmpeg_utils.cc.
Referenced by start_timer().
fourcc_make_string()
std::string fourcc_make_string (std::string * buf, uint32_t fourcc)
Fill the provided buffer with a string containing a FourCC (four-character code) representation.
Parameters
buf - Upon return, filled in with the FourCC representation.
fourcc - The fourcc to represent
Returns
The buffer in input.
Definition at line 1685 of file ffmpeg_utils.cc.
get_codec_name()
const char* get_codec_name (AVCodecID codec_id, bool long_name)
Safe way to get the codec name. Function never fails, will return "unknown" on error.
Parameters
[in] codec_id - ID of codec
[in] long_name - If true, gets the long name.
Returns
Returns the codec name or "unknown" on error.
Definition at line 1272 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Transcoder::add_albumart_stream(), FFmpeg_Transcoder::add_stream(), FFmpeg_Base::audio_info(), FFmpeg_Transcoder::calculate_predicted_filesize(), FFmpeg_Transcoder::open_input_file(), transcoder_set_filesize(), and FFmpeg_Base::video_info().
get_disk_free()
size_t get_disk_free (std::string & path)
Get free disk space.
Parameters
[in] path - Path or file on disk.
Returns
Returns the free disk space.
Definition at line 1931 of file ffmpeg_utils.cc.
get_encoding()
int get_encoding (const char * str, std::string & encoding)
Try to detect the encoding of str. This is relatively realiable, but may be wrong.
Parameters
[in] str - Text string to be checked.
[out] encoding - Detected encoding.
Returns
Returns 0 if successful, or CHARDET_OUT_OF_MEMORY/CHARDET_MEM_ALLOCATED_FAIL on error.
Definition at line 2040 of file ffmpeg_utils.cc.
get_filetype()
FILETYPE get_filetype (const std::string & desttype)
Get the FFmpegfs filetype, desttype must be one of FFmpeg's "official" short names for formats.
Parameters
[in] desttype - Destination type (MP4, WEBM etc.).
Returns
On success returns FILETYPE enum; on error returns FILETYPE_UNKNOWN.
Definition at line 1362 of file ffmpeg_utils.cc.
References filetype_map.
Referenced by FFmpegfs_Format::init().
get_filetype_from_list()
FILETYPE get_filetype_from_list (const std::string & desttypelist)
Get the FFmpegfs filetype, desttypelist must be a comma separated list of FFmpeg's "official" short names for formats. Will return the first match. Same as get_filetype, but accepts a comma separated list.
Parameters
[in] desttypelist - Destination type list (MP4, WEBM etc.) separated by commas.
Returns
On success returns FILETYPE enum; on error returns FILETYPE_UNKNOWN.
Definition at line 1386 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Transcoder::open_input_file().
get_filetype_text()
std::string get_filetype_text (FILETYPE filetype)
Convert FILETYPE enum to human readable text.
Parameters
[in] filetype - FILETYPE enum value to convert.
Returns
FILETYPE enum as text or "INVALID" if not known.
Definition at line 1375 of file ffmpeg_utils.cc.
Referenced by transcoder_set_filesize().
get_media_type_string()
const char* get_media_type_string (enum AVMediaType media_type)
av_get_media_type_string is missing, so we provide our own.
Parameters
[in] media_type - Media type to map.
Returns
Pointer to media type string.
Definition at line 1090 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Transcoder::add_albumart_stream(), FFmpeg_Transcoder::add_stream(), ffmpegfs_readdir(), and FFmpeg_Transcoder::open_bestmatch_decoder().
hwdevice_get_type_name()
const char* hwdevice_get_type_name (AVHWDeviceType dev_type)
Save version of hwdevice_get_type_name: Get the string name of an AVHWDeviceType.
Parameters
[in] dev_type - Type from enum AVHWDeviceType.
Returns
Pointer to a static string containing the name, or "unknown" if the type is not valid.
Definition at line 1990 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Transcoder::get_hw_pix_fmt(), and FFmpeg_Transcoder::hwdevice_ctx_create().
is_album_art()
bool is_album_art (AVCodecID codec_id, const AVRational * frame_rate = nullptr)
Minimal check if codec is an album art. Requires frame_rate to decide whether this is a video stream if codec_id is not BMP or PNG (which means its undoubtedly an album art). For MJPEG this may also be a video stream if the frame rate is high enough.
Parameters
[in] codec_id - ID of codec.
[in] frame_rate - Video frame rate, if known.
Returns
Returns true if codec is for an image; false if not.
Definition at line 1897 of file ffmpeg_utils.cc.
Referenced by FFMPEGFS_PARAMS::guess_format_idx(), FFmpeg_Transcoder::is_video(), and FFmpeg_Transcoder::open_input_file().
is_mount()
int is_mount (const std::string & path)
Check if path is a mount.
Parameters
[in] path - Path to check.
Returns
Returns 1 if path is a mount point; 0 if not. On error returns -1. Check errorno for details.
Definition at line 1789 of file ffmpeg_utils.cc.
References new_strdup().
Referenced by ffmpegfs_opt_proc().
ltrim()
std::string& ltrim (std::string & s)
trim from start
Parameters
[in] s - String to trim.
Returns
Reference to string s.
Definition at line 1709 of file ffmpeg_utils.cc.
make_filename()
std::string make_filename (uint32_t file_no, const std::string & fileext)
Make a file name from file number and file extension.
Parameters
[in] file_no - File number 1...n
[in] fileext - Extension of file (e.g mp4, webm)
Returns
Returns the file name.
Definition at line 1966 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Transcoder::encode_finish(), ffmpegfs_getattr(), ffmpegfs_readdir(), Buffer::init(), and make_hls_fileset().
make_lower()
void make_lower (std::string * input)
Convert string to lower case.
Parameters
[in,out] input String to convert
Definition at line 1983 of file ffmpeg_utils.cc.
make_upper()
void make_upper (std::string * input)
Convert string to upper case.
Parameters
[in,out] input String to convert
Definition at line 1976 of file ffmpeg_utils.cc.
mktree()
int mktree (const std::string & path, mode_t mode)
Make directory tree.
Parameters
[in] path - Path to create
[in] mode - Directory mode, see mkdir() function.
Returns
On success, returns 0; on error, returns non-zero errno value.
Definition at line 1295 of file ffmpeg_utils.cc.
Referenced by Buffer::init(), and Cache::load_index().
new_strdup()
char* new_strdup (const std::string & str)
strdup() variant taking a std::string as input.
Parameters
[in] str - String to duplicate.
Returns
Copy of the input string. Remember to delete the allocated memory.
Definition at line 1045 of file ffmpeg_utils.cc.
Referenced by Buffer::init(), is_mount(), remove_filename(), and remove_path().
nocasecompare()
int nocasecompare (const std::string & lhs, const std::string & rhs)
nocasecompare to make std::string find operations case insensitive
Parameters
[in] lhs - left hand string
[in] rhs - right hand string
Returns
-1 if lhs < rhs; 0 if lhs == rhs and 1 if lhs > rhs
Definition at line 1926 of file ffmpeg_utils.cc.
Referenced by comp::operator()(), and transcoded_name().
print_stream_info()
int print_stream_info (const AVStream * stream)
Print info about an AVStream.
Parameters
[in] stream - Stream to print.
Returns
On success returns 0; on error negative AVERROR.
Definition at line 1636 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Transcoder::add_stream_copy().
read_file()
int read_file (const std::string & path, std::string & result)
Read text file and return in UTF-8 format, no matter in which encoding the input file is. UTF-8/16/32 with BOM will always return a correct result. For all other encodings the function tries to detect it, that may fail.
Parameters
[in] path - Path and filename of input file
[out] result - File contents as UTF-8
Returns
Returns one of the ENCODING enum values on success, or errno on error. Basically a return code > 0 means there is an error.
Definition at line 2082 of file ffmpeg_utils.cc.
Referenced by parse_cuesheet().
reg_compare()
int reg_compare (const std::string & value, const std::string & pattern, std::regex::flag_type flag = std::regex::ECMAScript)
Compare value with pattern.
Parameters
[in] value - Value to check.
[in] pattern - Regexp pattern to match.
[in] flag - On of the flag_type constants, see https://en.cppreference.com/w/cpp/regex/basic_regex for options. Mostly std::regex::icase is used to make matches case insensitive.
Returns
Returns 0 if pattern matches; 1 if not; -1 if pattern is no valid regex
Definition at line 1751 of file ffmpeg_utils.cc.
Referenced by get_bitrate(), get_samplerate(), get_size(), and get_time().
remove_ext()
const std::string& remove_ext (std::string * filepath)
Remove extension from filename.
Parameters
[in] filepath - Filename to remove path from.
Returns
Returns constant reference to filename.
Definition at line 960 of file ffmpeg_utils.cc.
Referenced by check_cuesheet(), and find_original().
remove_filename()
const std::string& remove_filename (std::string * filepath)
Remove filename from path. Handy dirname alternative.
Parameters
[in] filepath - Path to remove filename from.
Returns
Returns constant reference to path.
Definition at line 929 of file ffmpeg_utils.cc.
References append_sep(), and new_strdup().
Referenced by ffmpegfs_getattr(), find_original(), find_parent(), VCDUTILS::get_directory(), load_path(), parse_cuesheet(), and FileIO::set_virtualfile().
remove_path()
const std::string& remove_path (std::string * filepath)
Remove path from filename. Handy basename alternative.
Parameters
[in] filepath - Filename to remove path from.
Returns
Returns constant reference to filename.
Definition at line 945 of file ffmpeg_utils.cc.
References new_strdup().
Referenced by check_cuesheet(), find_original(), get_number(), load_path(), and parse_cuesheet().
remove_sep()
const std::string& remove_sep (std::string * path)
Remove / from the path.
Parameters
[in] path - Path to remove separator from.
Returns
Returns constant reference to path.
Definition at line 919 of file ffmpeg_utils.cc.
Referenced by find_parent(), load_path(), and make_hls_fileset().
replace_all()
std::string replace_all (std::string str, const std::string & from, const std::string & to)
Same as std::string replace(), but replaces all occurrences.
Parameters
[in] str - Source string.
[in] from - String to replace.
[in] to - Replacement string.
Returns
Source string with all occurrences of from replaced with to.
Definition at line 1726 of file ffmpeg_utils.cc.
Referenced by create_bluray_virtualfile(), create_cuesheet_virtualfile(), create_dvd_virtualfile(), create_vcd_virtualfile(), and parse_embedded_cuesheet().
replace_ext()
const std::string& replace_ext (std::string * filepath, const std::string & ext)
Replace extension in filename, taking into account that there might not be an extension already.
Parameters
[in] filepath - Filename to replace extension.
[in] ext - Extension to replace.
Returns
Returns constant reference to filename.
Definition at line 1008 of file ffmpeg_utils.cc.
Referenced by check_cuesheet(), and transcoded_name().
rtrim()
std::string& rtrim (std::string & s)
trim from end
Parameters
[in] s - String to trim.
Returns
Reference to string s.
Definition at line 1715 of file ffmpeg_utils.cc.
Referenced by Logging::Logger::~Logger().
sanitise_filepath() [1/2]
std::string sanitise_filepath (const std::string & filepath)
Sanitise file name. Calls realpath() to remove duplicate // or resolve ../.. etc.
Parameters
[in] filepath - File name and path to sanitise.
Returns
Returns sanitised file name and path.
Definition at line 1891 of file ffmpeg_utils.cc.
sanitise_filepath() [2/2]
std::string sanitise_filepath (std::string * filepath)
Sanitise file name. Calls realpath() to remove duplicate // or resolve ../.. etc. Changes the path in place.
Parameters
[in] filepath - File name and path to sanitise.
Returns
Returns sanitised file name and path.
Definition at line 1874 of file ffmpeg_utils.cc.
Referenced by ffmpegfs_opt_proc(), find_file(), find_original(), insert_file(), and translate_path().
search_by_value()
template<typename T > std::map<const std::string, const T, comp>::const_iterator search_by_value (const std::map< const std::string, const T, comp > & mapOfWords, T value)
Iterate through all elements in map and search for the passed element.
Parameters
[in] mapOfWords - map to search.
[in] value - Search value
Returns
If found, retuns const_iterator to element. Returns mapOfWords.cend() if not.
Definition at line 984 of file ffmpeg_utils.h.
Referenced by get_audio_codec_text(), get_autocopy_text(), get_level_text(), get_profile_text(), get_recodesame_text(), get_sampleformat_text(), and get_video_codec_text().
show_caps()
int show_caps (int device_only)
Lists all supported codecs and devices.
Parameters
[in] device_only - If true lists devices only.
Returns
On success returns 0; on error negative AVERROR.
Definition at line 1181 of file ffmpeg_utils.cc.
split()
std::vector<std::string> split (const std::string & input, const std::string & regex)
Split string into an array delimited by a regular expression.
Parameters
[in] input - Input string.
[in] regex - Regular expression to match.
Returns
Returns an array with separate elements.
Definition at line 1865 of file ffmpeg_utils.cc.
Referenced by allow_list_ext(), and get_desttype().
stat_set_size()
void stat_set_size (struct stat * st, size_t size)
Properly fill in all size related members in stat struct.
Parameters
[in,out] st stat structure to update
[in] size size value to copy
Definition at line 2280 of file ffmpeg_utils.cc.
Referenced by create_cuesheet_virtualfile(), FFmpeg_Transcoder::encode_finish(), ffmpegfs_fgetattr(), ffmpegfs_getattr(), init_stat(), load_path(), and transcoder_cached_filesize().
strcasecmp()
int strcasecmp (const std::string & s1, const std::string & s2)
strcasecmp() equivalent for std::string.
Parameters
[in] s1 - std:string #1
[in] s2 - std:string #2
Returns
Returns same as strcasecmp() for char *.
Definition at line 1737 of file ffmpeg_utils.cc.
Referenced by FFmpeg_Transcoder::add_stream(), allow_list_ext(), append_ext(), FFmpeg_Transcoder::copy_metadata(), and find_original().
string_format()
template<typename ... Args> std::string string_format (const std::string & format, Args ... args)
Format a std::string sprintf-like.
Parameters
[in] format - sprintf-like format string.
[in] args - Arguments.
Returns
Returns the formatted string.
Definition at line 1743 of file ffmpeg_utils.cc.
Referenced by ffmpeg_libinfo(), format_result_size_ex(), and make_hls_fileset().
supports_albumart()
int supports_albumart (FILETYPE filetype)
Check if file type supports album arts.
Parameters
[in] filetype - File type: MP3, MP4 etc.
Returns
Returns true if album arts are supported, false if not.
Definition at line 1356 of file ffmpeg_utils.cc.
tempdir()
void tempdir (std::string & path)
Get temporary directory.
Parameters
[out] path - Path to temporary directory.
Definition at line 1336 of file ffmpeg_utils.cc.
to_utf8()
int to_utf8 (std::string & text, const std::string & encoding)
Convert almost any encoding to UTF-8. To get a list of all possible encodings run "iconv --list".
Parameters
[in] text - Text to be converted
[in] encoding - Encoding of input text.
Returns
Returns 0 if successful and the converted text, or errno value on error and text is unchanged.
Definition at line 1996 of file ffmpeg_utils.cc.
trim()
std::string& trim (std::string & s)
trim from both ends
Parameters
[in] s - String to trim.
Returns
Reference to string s.
Definition at line 1721 of file ffmpeg_utils.cc.
Referenced by VCDUTILS::convert_txt2string().