FFmpegfs Fuse Multi Media Filesystem: VCDUTILS Namespace Reference
VCDUTILS Namespace Reference
Video CD utility functions.
Functions
std::string convert_txt2string (const char *txt, int size, bool trimmed=true)
Convert non zero terminated text to std::string.
bool locate_file (const std::string &path, const std::string &filename, std::string &fullname, bool &is_vcd)
Check if path is a S/VCD.
int locate_video (const std::string &path, int track_no, std::string &fullname)
Locate AVSEQ*DAT/MPEG video file for track_no.
std::string get_type_str (int type)
Return disk type as string.
std::string get_profile_tag_str (int tag)
get_profile_tag_str
void get_directory (const std::string &fullname, std::string *directory)
Check if fullname is a directory. Remove filename if necessary.
Detailed Description
Video CD utility functions.
Function Documentation
convert_txt2string()
std::string VCDUTILS::convert_txt2string (const char * txt, int size, bool trimmed = true)
Convert non zero terminated text to std::string.
Parameters
[in] txt - Text for conversion (not zero terminated)
[in] size - Length of string
[in] trimmed - If true, trim trailing white spaces
Returns
Converted text
Definition at line 39 of file vcdutils.cc.
References trim().
Referenced by VcdInfo::load_file(), and VcdEntries::load_file().
get_directory()
void VCDUTILS::get_directory (const std::string & fullname, std::string * directory)
Check if fullname is a directory. Remove filename if necessary.
Note
Really checks if fullname is a path even if the trailing slash is missing.
Parameters
[in] fullname - Path and optional filename
[out] directory - Directory without file name
Definition at line 151 of file vcdutils.cc.
References append_sep(), and remove_filename().
Referenced by VcdInfo::load_file(), and VcdEntries::load_file().
get_profile_tag_str()
std::string VCDUTILS::get_profile_tag_str (int tag)
get_profile_tag_str
Parameters
[in] tag - 1: VCD 1.0, VCD 2.0, SVCD, HQVCD, 2: VCD 1.1
Returns
Profile as human readable string
Definition at line 132 of file vcdutils.cc.
Referenced by VcdInfo::get_profile_tag_str(), and VcdEntries::get_profile_tag_str().
get_type_str()
std::string VCDUTILS::get_type_str (int type)
Return disk type as string.
Parameters
[in] type - 1: VCD 1.0, VCD 1.1, SVCD 1.0, HQVCD, 2: VCD 2.0
Returns
Disk type as human readable string
Definition at line 111 of file vcdutils.cc.
Referenced by VcdInfo::get_type_str(), and VcdEntries::get_type_str().
locate_file()
bool VCDUTILS::locate_file (const std::string & path, const std::string & filename, std::string & fullname, bool & is_vcd)
Check if path is a S/VCD.
Parameters
[in] path - path to check
[in] filename - file name to check, can per ENTRIES or INFO (extension .SVD or .VCD will be added automatically).
[out] fullname - path and filename or ENTRIES.SVC/VCD or INFO.SVC/VCD if found
[out] is_vcd - true if directory contains a Super Video CD, false if it's a Video CD
Returns
true if path contains a S/VCD, false if not
Definition at line 64 of file vcdutils.cc.
Referenced by VcdInfo::load_file(), and VcdEntries::load_file().
locate_video()
int VCDUTILS::locate_video (const std::string & path, int track_no, std::string & fullname)
Locate AVSEQ*DAT/MPEG video file for track_no.
Parameters
[in] path - path to search in
[in] track_no - track number (1...n)
[out] fullname - name and path of file if found
Returns
Definition at line 88 of file vcdutils.cc.
Referenced by VcdIO::open(), and VcdEntries::scan_chapters().