FFmpegfs Fuse Multi Media Filesystem: comp Struct Reference
comp Struct Reference
The comp struct to make std::string find operations case insensitive.
#include <ffmpeg_utils.h>
Public Member Functions
bool operator() (const std::string &lhs, const std::string &rhs) const
operator () to make std::string find operations case insensitive
Detailed Description
The comp struct to make std::string find operations case insensitive.
Definition at line 642 of file ffmpeg_utils.h.
Member Function Documentation
operator()()
bool comp::operator() (const std::string & lhs, const std::string & rhs) const inline
operator () to make std::string find operations case insensitive
Parameters
[in] lhs - left hand string
[in] rhs - right hand string
Returns
-1 if lhs < rhs; 0 if lhs == rhs and 1 if lhs > rhs
Definition at line 650 of file ffmpeg_utils.h.
References check_ignore(), get_disk_free(), and nocasecompare().
The documentation for this struct was generated from the following file:
src/ffmpeg_utils.h