FFmpegfs Fuse Multi Media Filesystem: FFMPEGFS_PARAMS Struct Reference
FFMPEGFS_PARAMS Struct Reference
Global program parameters.
#include <ffmpegfs.h>
Public Member Functions
FFMPEGFS_PARAMS (const FFMPEGFS_PARAMS &other)
Make copy from other FFMPEGFS_PARAMS object.
bool smart_transcode () const
Check for smart transcode mode.
const FFmpegfs_Format * current_format (LPCVIRTUALFILE virtualfile) const
Get FFmpegfs_Format for a virtual file.
FFMPEGFS_PARAMS & operator= (const FFMPEGFS_PARAMS &other) noexcept
Make copy from other FFMPEGFS_PARAMS object.
Public Attributes
std::string m_basepath
Base path: Files from this directory (including all sub directories) will be mapped to m_mountpath.
std::string m_mountpath
Mount path: Files from m_mountpath will be mapped to this directory.
AVCodecID m_audio_codec
Either AV_CODEC_ID_NONE for default, or a user selected codec.
AVCodecID m_video_codec
Either AV_CODEC_ID_NONE for default, or a user selected codec.
AUTOCOPY m_autocopy
Copy streams if codec matches.
RECODESAME m_recodesame
Recode to same format options.
PROFILE m_profile
Target profile: Firefox, MS Edge/IE or other.
PRORESLEVEL m_level
Level, currently proxy/hq/lt/HQ (ProRes only)
BITRATE m_audiobitrate
Output audio bit rate (bits per second)
int m_audiosamplerate
Output audio sample rate (in Hz)
int m_audiochannels
Max. number of audio channels.
SAMPLE_FMT m_sample_fmt
Sample format.
BITRATE m_videobitrate
Output video bit rate (bits per second)
int m_videowidth
Output video width.
int m_videoheight
Output video height.
int m_deinterlace
1: deinterlace video, 0: no deinterlace
int64_t m_segment_duration
Duration of one HLS segment file, in AV_TIME_BASE fractional seconds.
int64_t m_min_seek_time_diff
Minimum time diff from current to next requested segment to perform a seek, in AV_TIME_BASE fractional seconds.
HWACCELAPI m_hwaccel_enc_API
Encoder API.
AVHWDeviceType m_hwaccel_enc_device_type
Enable hardware acceleration buffering for encoder.
std::string m_hwaccel_enc_device
Encoder device. May be AUTO to auto detect or empty.
HWACCELAPI m_hwaccel_dec_API
Decoder API.
AVHWDeviceType m_hwaccel_dec_device_type
Enable hardware acceleration buffering for decoder.
std::string m_hwaccel_dec_device
Decoder device. May be AUTO to auto detect or empty.
HWACCEL_BLOCKED_MAP * m_hwaccel_dec_blocked
List of blocked decoders and optional profiles.
int m_no_subtitles
0: allow subtitles, 1: do no transcode subtitles
int m_noalbumarts
Skip album arts.
int m_enablescript
Enable virtual script.
std::string m_scriptfile
Script name.
std::string m_scriptsource
Source script.
int m_debug
Debug mode (stay in foreground.
std::string m_log_maxlevel
Max. log level.
int m_log_stderr
Log output to standard error.
int m_log_syslog
Log output to system log.
std::string m_logfile
Output filename if logging to file.
time_t m_expiry_time
Time (seconds) after which an cache entry is deleted.
time_t m_max_inactive_suspend
Time (seconds) that must elapse without access until transcoding is suspended.
time_t m_max_inactive_abort
Time (seconds) that must elapse without access until transcoding is aborted.
time_t m_prebuffer_time
Playing time that will be decoded before the output can be accessed.
size_t m_prebuffer_size
Number of bytes that will be decoded before the output can be accessed.
size_t m_max_cache_size
Max. cache size in MB. When exceeded, oldest entries will be pruned.
size_t m_min_diskspace
Min. diskspace required for cache.
std::string m_cachepath
Disk cache path, defaults to $XDG_CACHE_HOME.
int m_disable_cache
Disable cache.
time_t m_cache_maintenance
Prune timer interval.
int m_prune_cache
Prune cache immediately.
int m_clear_cache
Clear cache on start up.
unsigned int m_max_threads
Max. number of recoder threads.
int m_decoding_errors
Break transcoding on decoding error.
int m_min_dvd_chapter_duration
Min. DVD chapter duration. Shorter chapters will be ignored.
int m_oldnamescheme
Use old output name scheme, can create duplicate filenames.
MATCHVEC * m_include_extensions
Set of extensions to include. If empty, include all. Must be a pointer as the fuse API cannot handle advanced c++ objects.
MATCHVEC * m_hide_extensions
Set of extensions to block/hide. Must be a pointer as the fuse API cannot handle advanced c++ objects.
int m_win_smb_fix
Experimental Windows fix for access to EOF at file open.
Detailed Description
Global program parameters.
Definition at line 166 of file ffmpegfs.h.
Constructor & Destructor Documentation
FFMPEGFS_PARAMS()
FFMPEGFS_PARAMS::FFMPEGFS_PARAMS (const FFMPEGFS_PARAMS & other)
Make copy from other FFMPEGFS_PARAMS object.
Parameters
[in] other - Reference to source FFmpeg_Frame object.
Returns
Reference to new FFmpeg_Frame object.
Definition at line 149 of file ffmpegfs.cc.
Member Function Documentation
current_format()
const FFmpegfs_Format * FFMPEGFS_PARAMS::current_format (LPCVIRTUALFILE virtualfile) const
Get FFmpegfs_Format for a virtual file.
Parameters
[in] virtualfile - VIRTUALFILE struct of a file.
Returns
On success, returns pointer to format. On error, returns nullptr.
Definition at line 239 of file ffmpegfs.cc.
References ffmpeg_format.
Referenced by Cache_Entry::Cache_Entry(), FFmpeg_Transcoder::encode_finish(), ffmpegfs_getattr(), ffmpegfs_readdir(), get_format(), Buffer::init(), load_path(), make_hls_fileset(), FFmpeg_Transcoder::open_input_file(), transcode(), transcoder_read(), and transcoder_set_filesize().
operator=()
FFMPEGFS_PARAMS & FFMPEGFS_PARAMS::operator= (const FFMPEGFS_PARAMS & other) noexcept
Make copy from other FFMPEGFS_PARAMS object.
Parameters
[in] other - Reference to source FFmpeg_Frame object.
Returns
Reference to new FFmpeg_Frame object.
Definition at line 161 of file ffmpegfs.cc.
References m_basepath.
smart_transcode()
bool FFMPEGFS_PARAMS::smart_transcode () const
Check for smart transcode mode.
Returns
true if smart transcode is active, false if not
Definition at line 234 of file ffmpegfs.cc.
References ffmpeg_format.
Referenced by find_original(), get_format(), and guess_format_idx().
The documentation for this struct was generated from the following files:
src/ffmpegfs.h
src/ffmpegfs.cc