FFmpegfs Fuse Multi Media Filesystem: src/transcode.h File Reference
transcode.h File Reference
File transcoder interface (for use with by FUSE)
#include "ffmpegfs.h"
#include "fileio.h"
Functions
bool transcoder_cached_filesize (LPVIRTUALFILE virtualfile, struct stat *stbuf)
Simply get encoded file size (do not create the whole encoder/decoder objects)
bool transcoder_set_filesize (LPVIRTUALFILE virtualfile, int64_t duration, BITRATE audio_bit_rate, int channels, int sample_rate, AVSampleFormat sample_format, BITRATE video_bit_rate, int width, int height, bool interleaved, const AVRational &framerate)
Set the file size.
bool transcoder_predict_filesize (LPVIRTUALFILE virtualfile, Cache_Entry *cache_entry=nullptr)
Predict file size.
Cache_Entry * transcoder_new (LPVIRTUALFILE virtualfile, bool begin_transcode)
Allocate and initialise the transcoder.
bool transcoder_read (Cache_Entry *cache_entry, char *buff, size_t offset, size_t len, int *bytes_read, uint32_t segment_no)
Read some bytes from the internal buffer and into the given buffer.
bool transcoder_read_frame (Cache_Entry *cache_entry, char *buff, size_t offset, size_t len, uint32_t frame_no, int *bytes_read, LPVIRTUALFILE virtualfile)
Read one image frame from the internal buffer and into the given buffer.
void transcoder_delete (Cache_Entry *cache_entry)
Free the cache entry structure.
size_t transcoder_get_size (Cache_Entry *cache_entry)
Return size of output file, as computed by encoder.
size_t transcoder_buffer_watermark (Cache_Entry *cache_entry, uint32_t segment_no)
Return the current watermark of the file while transcoding.
size_t transcoder_buffer_tell (Cache_Entry *cache_entry, uint32_t segment_no)
Return the current file position in the file.
void transcoder_exit ()
Exit transcoding.
Detailed Description
File transcoder interface (for use with by FUSE)
Author
Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Copyright
Copyright (C) 2006-2008 David Collett
Copyright (C) 2008-2013 K. Henriksson
Copyright (C) 2017-2022 FFmpeg support by Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Definition in file transcode.h.
Function Documentation
transcoder_buffer_tell()
size_t transcoder_buffer_tell (Cache_Entry * cache_entry, uint32_t segment_no)
Return the current file position in the file.
Parameters
[in] cache_entry - corresponding cache entry
[in] segment_no - HLS segment file number.
Returns
Returns the current file position
Definition at line 731 of file transcode.cc.
References Cache_Entry::m_buffer, and Buffer::tell().
transcoder_buffer_watermark()
size_t transcoder_buffer_watermark (Cache_Entry * cache_entry, uint32_t segment_no)
Return the current watermark of the file while transcoding.
While transcoding, this value reflects the current size of the transcoded file. This is the maximum byte offset until the file can be read so far.
Parameters
[in] cache_entry - corresponding cache entry
[in] segment_no - HLS segment file number.
Returns
Returns the current watermark
Definition at line 726 of file transcode.cc.
References Buffer::buffer_watermark(), and Cache_Entry::m_buffer.
Referenced by ffmpegfs_fgetattr().
transcoder_cached_filesize()
bool transcoder_cached_filesize (LPVIRTUALFILE virtualfile, struct stat * stbuf)
Simply get encoded file size (do not create the whole encoder/decoder objects)
Parameters
[in] virtualfile - virtual file object to open
[out] stbuf - stat struct filled in with the size of the cached file
Returns
Returns true if file was found in cache, false if not (stbuf will be unchanged)
Definition at line 262 of file transcode.cc.
References cache, Cache_Entry::m_cache_info, CACHE_INFO::m_encoded_filesize, CACHE_INFO::m_predicted_filesize, Cache::open(), and stat_set_size().
Referenced by create_bluray_virtualfile(), create_cuesheet_virtualfile(), create_dvd_virtualfile(), and ffmpegfs_getattr().
transcoder_delete()
void transcoder_delete (Cache_Entry * cache_entry)
Free the cache entry structure.
Call this to free the cache entry structure.
The structure is reference counted, after calling this function, if the cache entry is not use by another thread, the cache entry may no longer be valid.
Parameters
[in] cache_entry - corresponding cache entry
Definition at line 716 of file transcode.cc.
References cache, and Cache::close().
Referenced by ffmpegfs_getattr(), ffmpegfs_release(), get_source_properties(), and kick_next().
transcoder_exit()
void transcoder_exit ()
Exit transcoding.
Send signal to exit transcoding (ending all transcoder threads).
Definition at line 736 of file transcode.cc.
References thread_exit.
Referenced by ffmpegfs_destroy(), and sighandler().
transcoder_get_size()
size_t transcoder_get_size (Cache_Entry * cache_entry)
Return size of output file, as computed by encoder.
Returns the file size, either the predicted size (which may be inaccurate) or the real size (which is only available once the file was completely recoded).
Parameters
[in] cache_entry - corresponding cache entry
Returns
The size of the file. Function never fails.
Definition at line 721 of file transcode.cc.
References Cache_Entry::size().
Referenced by ffmpegfs_getattr().
transcoder_new()
Cache_Entry* transcoder_new (LPVIRTUALFILE virtualfile, bool begin_transcode)
Allocate and initialise the transcoder.
Opens a file and starts the decoding thread if begin_transcode is true. File will be scanned to detect bit rate, duration etc. only if begin_transcode is false.
Parameters
[in] virtualfile - virtual file object to open
[in] begin_transcode - if true, transcoding starts, if false file will be scanned only
Returns
On success, returns cache entry object. On error, returns nullptr and sets errno accordingly.
Definition at line 354 of file transcode.cc.
References cache, CACHE_CLOSE_DELETE, Cache_Entry::clear(), Cache::close(), Logging::debug(), Cache_Entry::filename(), Cache_Entry::is_finished_success(), Cache_Entry::lock(), THREAD_DATA::m_arg, Cache_Entry::m_cache_info, THREAD_DATA::m_cond, FFMPEGFS_PARAMS::m_disable_cache, CACHE_INFO::m_duration, VIRTUALFILE::m_duration, CACHE_INFO::m_errno, CACHE_INFO::m_error, THREAD_DATA::m_initialised, Cache_Entry::m_is_decoding, THREAD_DATA::m_lock_guard, THREAD_DATA::m_mutex, CACHE_INFO::m_predicted_filesize, VIRTUALFILE::m_predicted_size, CACHE_INFO::m_video_frame_count, VIRTUALFILE::m_video_frame_count, Cache_Entry::open(), Cache::open(), Cache_Entry::outdated(), params, thread_pool::schedule_thread(), tp, Logging::trace(), transcoder_predict_filesize(), transcoder_thread(), Cache_Entry::unlock(), and Cache_Entry::virtname().
Referenced by ffmpegfs_getattr(), ffmpegfs_open(), get_source_properties(), and kick_next().
transcoder_predict_filesize()
bool transcoder_predict_filesize (LPVIRTUALFILE virtualfile, Cache_Entry * cache_entry = nullptr)
Predict file size.
Parameters
[in] virtualfile - virtual file object to open
[in] cache_entry - corresponding cache entry
Returns
On error, returns false (size could not be predicted) or true on success
Definition at line 329 of file transcode.cc.
References FFmpeg_Transcoder::close(), FFmpeg_Transcoder::duration(), FFmpeg_Transcoder::filename(), format_size_ex(), Cache_Entry::m_cache_info, CACHE_INFO::m_duration, CACHE_INFO::m_predicted_filesize, CACHE_INFO::m_segment_count, CACHE_INFO::m_video_frame_count, FFmpeg_Transcoder::open_input_file(), FFmpeg_Transcoder::predicted_filesize(), FFmpeg_Transcoder::segment_count(), Logging::trace(), and FFmpeg_Transcoder::video_frame_count().
Referenced by transcoder_new().
transcoder_read()
bool transcoder_read (Cache_Entry * cache_entry, char * buff, size_t offset, size_t len, int * bytes_read, uint32_t segment_no)
Read some bytes from the internal buffer and into the given buffer.
Note
buff must be large enough to hold len number of bytes.
Returns number of bytes read, may be less than len bytes.
Parameters
[in] cache_entry - corresponding cache entry
[out] buff - will be filled in with data read
[in] offset - byte offset to start reading at
[in] len - length of data chunk to be read.
[out] bytes_read - Bytes read from transcoder.
[in] segment_no - HLS segment file number.
Returns
On success, returns true. On error, returns false and sets errno accordingly.
Definition at line 470 of file transcode.cc.
References CACHE_FLAG_RO, FFMPEGFS_PARAMS::current_format(), FFmpegfs_Format::filetype(), Cache_Entry::is_finished_success(), Cache_Entry::m_buffer, Cache_Entry::m_seek_to_no, Buffer::open_file(), params, Buffer::segment_exists(), Logging::trace(), Cache_Entry::update_access(), Cache_Entry::update_read_count(), Cache_Entry::virtname(), and Cache_Entry::virtualfile().
Referenced by ffmpegfs_read().
transcoder_read_frame()
bool transcoder_read_frame (Cache_Entry * cache_entry, char * buff, size_t offset, size_t len, uint32_t frame_no, int * bytes_read, LPVIRTUALFILE virtualfile)
Read one image frame from the internal buffer and into the given buffer.
Note
buff must be large enough to hold len number of bytes.
Returns number of bytes read, may be less than len bytes.
Parameters
[in] cache_entry - corresponding cache entry
[out] buff - will be filled in with data read
[in] offset - byte offset to start reading at
[in] len - length of data chunk to be read.
[in] frame_no - Number of frame to return.
[out] bytes_read - Bytes read from transcoder.
[in,out] virtualfile - Birtual file object of image, may be modified.
Returns
On success, returns true. On error, returns false and sets errno accordingly.
Definition at line 601 of file transcode.cc.
References CACHE_FLAG_RO, Logging::error(), FRAME_TIMEOUT, GRANULARITY, Logging::info(), Cache_Entry::m_buffer, Cache_Entry::m_cache_info, CACHE_INFO::m_error, Cache_Entry::m_is_decoding, Cache_Entry::m_seek_to_no, VIRTUALFILE::m_st, MS, Buffer::open_file(), Buffer::read_frame(), stat_set_size(), thread_exit, Logging::trace(), Cache_Entry::update_access(), Cache_Entry::update_read_count(), Cache_Entry::virtname(), and Logging::warning().
Referenced by ffmpegfs_read().
transcoder_set_filesize()
bool transcoder_set_filesize (LPVIRTUALFILE virtualfile, int64_t duration, BITRATE audio_bit_rate, int channels, int sample_rate, AVSampleFormat sample_format, BITRATE video_bit_rate, int width, int height, bool interleaved, const AVRational & framerate)
Set the file size.
Parameters
[in] virtualfile - virtual file object to open.
[in] duration - duration of the file, in AV_TIME_BASE fractional seconds.
[in] audio_bit_rate - average bitrate of audio data (in bits per second).
[in] channels - number of channels (1: mono, 2: stereo, or more).
[in] sample_rate - number of audio samples per second.
[in] sample_format - Selected sample format
[in] video_bit_rate - average bitrate of video data (in bits per second).
[in] width - video width in pixels.
[in] height - video height in pixels.
[in] interleaved - true if video is interleaved, false if not.
[in] framerate - frame rate per second (e.g. 24, 25, 30...).
Returns
On error, returns false (size could not be set) or true on success.
Definition at line 289 of file transcode.cc.
References FFmpegfs_Format::audio_codec(), FFmpeg_Transcoder::audio_size(), cache, FFMPEGFS_PARAMS::current_format(), FFmpegfs_Format::desttype(), Logging::error(), FFmpegfs_Format::filetype(), format_size_ex(), get_codec_name(), get_filetype_text(), Cache_Entry::m_cache_info, CACHE_INFO::m_predicted_filesize, VIRTUALFILE::m_predicted_size, Cache::open(), params, FFmpeg_Transcoder::total_overhead(), Logging::trace(), FFmpegfs_Format::video_codec(), FFmpeg_Transcoder::video_size(), Cache_Entry::virtname(), and Logging::warning().
Referenced by create_bluray_virtualfile(), create_cuesheet_virtualfile(), and create_dvd_virtualfile().