FFmpegfs Fuse Multi Media Filesystem: src/vcdparser.h File Reference
vcdparser.h File Reference
Video CD and Super Video CD parser.
Functions
int check_vcd (const std::string &path, void *buf=nullptr, fuse_fill_dir_t filler=nullptr)
Get number of chapters on S/VCD.
Detailed Description
Video CD and Super Video CD parser.
This is only available if built with -DUSE_LIBVCD parameter.
Author
Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Copyright
Copyright (C) 2018-2022 Norbert Schlia (nschl.nosp@m.ia@o.nosp@m.blivi.nosp@m.on-s.nosp@m.oftwa.nosp@m.re.d.nosp@m.e)
Definition in file vcdparser.h.
Function Documentation
check_vcd()
int check_vcd (const std::string & path, void * buf = nullptr, fuse_fill_dir_t filler = nullptr)
Get number of chapters on S/VCD.
Parameters
[in] path - Path to check
[in,out] buf - The buffer passed to the readdir() operation.
[in,out] filler - Function to add an entry in a readdir() operation (see https://libfuse.github.io/doxygen/fuse_8h.html#a7dd132de66a5cc2add2a4eff5d435660)
Note
buf and filler can be nullptr. In that case the call will run faster, so these parameters should only be passed if to be filled in.
Returns
-errno or number of chapters on S/VCD.
Definition at line 163 of file vcdparser.cc.
References add_dotdot(), append_sep(), check_path(), load_path(), parse_vcd(), and Logging::trace().
Referenced by ffmpegfs_getattr(), and ffmpegfs_readdir().